### ISSUE TITLE
[Feature Request] align objects

### ISSUE THREAD

**Issue by sevku** [openstreetmap/iD#7175] opened 2019-12-26 09:38 UTC
I want to present you with an idea for a new feature,

![Screenshot_20191226_103526](https://user-images.githubusercontent.com/23403917/71470219-bf53b580-27cb-11ea-8013-dcdf5ba87bae.png)

It would be helpful if there would be an option to align several objects that are in line in the real world. In the editor, it's currently quite a challenge to do that.

**Comment by mmd-osm** [comment] 2019-12-26 18:58
That's probably a duplicate of #2987

**Closed** 2019-12-26 19:25 UTC
