### ISSUE TITLE
id warns about disconnected way when it is not

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8981] opened 2022-02-13 18:13 UTC
### How to reproduce the issue?

See vid.

If I move a node then the warning is gone. However, most of the time I've finished editing and in order to bypass this issue I need to move twice (move to another place and then back)

### Screenshot(s) or anything else?

https://user-images.githubusercontent.com/686438/153768641-31be6970-049f-4fcd-aacd-84456c35907f.mp4

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by arch0345** [comment] 2022-02-14 17:07
This looks like a duplicate of #8900

**Comment by nickrsan** [comment] 2023-12-05 20:52
Agree that this is duplicate of #8900 and newer issues duplicate this one too - thanks for the clear report - closing this now, but tagging/flagging the other one

**Closed as not planned by nickrsan** 2023-12-05 20:52 UTC
Labels: duplicate
