### ISSUE TITLE
Use Portuguese-limited images in pt-BR

### ISSUE THREAD

**Issue by virgilinojuca** [openstreetmap/iD#6156] opened 2019-04-08 02:40 UTC
In #3776 I mentioned that an unification from Portuguese (`Pt:`) and Brazilian Portuguese (`Pt-br:`) languages was carried out in the wiki. In iD, though, there are still two different localizations.

When iD is set to `pt-BR` and the ℹ️ button is clicked to get more info on a certain tag or key, it correctly retrieves text from the wiki item descriptions in Portuguese. However, they do not retrieve images that are _limited to language_ ([P26](https://wiki.openstreetmap.org/wiki/Property:P26)) _Portuguese-language documentation_ ([Q7807](https://wiki.openstreetmap.org/wiki/Item:Q7807)); they retrieve the image with no specific qualifier. A good example for testing this is `amenity=telephone` ([Q5027](https://wiki.openstreetmap.org/wiki/Item:Q5027)).

On the other hand, if iD is set to `pt`, it correctly shows the image with the [P26](https://wiki.openstreetmap.org/wiki/Property:P26):[Q7807](https://wiki.openstreetmap.org/wiki/Item:Q7807) qualifier. Can you make the same for `pt-BR`?

**Comment by 1ec5** [comment] 2019-04-08 03:54
I’m pretty sure the “[limited to language](https://wiki.openstreetmap.org/wiki/Property:P26)” qualifiers were intended as a temporary compatibility shim for the fact that different translations of a tag’s description page had diverged in terms of images, required tags, or other details – but I don’t think it was intended to be a way to promote such differences.

Pay phone designs are specific to regions, regardless of language. (An English speaker mapping in Brazil would benefit as much from seeing the [Belo Horizonte pay phone](https://wiki.openstreetmap.org/wiki/File:Cabinetelefone.JPG) as a Portuguese speaker would.) @nyurik, this sounds like a case for introducing an “in region” qualifier and geographical region items to go along with it.

**Comment by nyurik** [comment] 2019-04-08 04:33
@1ec5 I agree, we ought to start moving to "limited to region" qualifiers. I wonder if we should pre-populate all countries? Or create bigger regions? Or just let users create them as needed?

Regions are tricky because each editor will need to convert object's location to a locale ID - e.g. by downloading all country shapes, and calculating which country a point belongs to, and then looking at the data item's qualifier to determine the right value to use.  But at the same time we would often want multiple countries in the same region - e.g. many European countries might share the same image for a road sign, so we wouldn't want to list them all in every data item, but instead have one "Europe's common signs region" thingy :)

I would propose this path:
#### Data items:
* create a `region includes country code` wikibase `string` property (_country code is easier for editors to download than to download each item and convert it to a code_)
* start creating "regions", e.g. for this case:
  * `label = Brazil region` (should it include other nearby countries?)
  * `instance of = geographical region`
  * `region includes country code = BR`
* create a `limited to region` wikibase `item` property and use it on `amenity=telephone` (Q5027).
#### iD and other editors
* create a topojson file with ID == country code (possibly with a few extras that have a complex status)
* whenever code sees `limited to regions` property, download that data item(s), download the above topojson (this can pre-cached), convert current map position into a country ID, and check if the "region item" matches calculated country ID.

**Comment by 1ec5** [comment] 2019-04-08 07:40
> Regions are tricky because each editor will need to convert object's location to a locale ID - e.g. by downloading all country shapes, and calculating which country a point belongs to, and then looking at the data item's qualifier to determine the right value to use.

iD already has code that geocodes the current viewport down to a country level using Nominatim.

https://github.com/openstreetmap/iD/blob/3896b2282f032cd8799c6038a6e71effe9447f14/modules/ui/fields/address.js#L213

**Comment by nyurik** [comment] 2019-04-08 15:14
wonderful, thanks.  Any thoughts about the rest of the proposal?  Should we move it to Talk:Wiki or Talk:Data Item ?

**Comment by 1ec5** [comment] 2019-04-09 01:16
Yeah, let’s continue the discussion [on this wiki page](https://wiki.openstreetmap.org/wiki/Talk:Data_items#Geographical_regions_as_qualifiers). As a wiki contributor, I think it would be much less awkward to be able to qualify these images by countries rather than languages.

In the meantime, as a temporary workaround, the item can make two claims with the same image but qualified with different languages (`pt` versus `pt-BR`). iD should be able to pick up the right image in both localizations.

**Comment by bhousel** [comment] 2019-04-23 15:09
> In the meantime, as a temporary workaround, the item can make two claims with the same image but qualified with different languages (pt versus pt-BR).

I don't really understand this issue.. Can it be closed by the above (just add 2 properties to the wikibase)

**Comment by virgilinojuca** [comment] 2019-04-23 15:22
> > In the meantime, as a temporary workaround, the item can make two claims with the same image but qualified with different languages (pt versus pt-BR).
> 
> I don't really understand this issue.. Can it be closed by the above (just add 2 properties to the wikibase)

There is no "Brazilian Portuguese-language documentation" data item to use with the P26 property. I don't know how to create a new item nor I know if I should.

**Comment by nyurik** [comment] 2019-04-23 17:59
I just added a [new section](https://wiki.openstreetmap.org/wiki/Data_items#Storing_Geographical_Differences) describing how to set geographical regions.  @virgilinojuca if you want to create a new region, simply create a new data item using the [special page](https://wiki.openstreetmap.org/wiki/Special:NewItem), set instance-of = Q19531, and set P49 to "BR".  See first link for documentation.

Once added, iD should be able to easily pick the right value to show.

**Closed** 2019-04-23 18:30 UTC
Labels: localization
