### ISSUE TITLE
Add imagery date more prominently to editing screen

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3059] opened 2016-04-11 18:03 UTC
I've found that people often overwrite correct edits based on the Bing imagery, which can be old -- this happened a lot in DC for example with new construction that people would delete because it wasn't on Bing, and I bet it happens with HOT places where imagery is old. I think it would be helpful to put the imagery date more prominently for the editing screen, and/or some kind of warning that says "note: this imagery is X years old, so maybe you shouldn't delete."

I think there is a Bing imagery date tool? I forget who did that.

Of course, people can and should leave notes for why they added something, but I think the more ways to make it clear, the better.

**Comment by bhousel** [comment] 2016-04-11 19:08
This is a duplicate of #2492 - we haven't thought of a really good way to support this yet.  Only Bing supports response headers that tell us the vintage of their imagery, but to get them we'd need to make a separate api request for the date.

Bing coverage tools are listed here:
http://wiki.openstreetmap.org/wiki/Bing_imagery_analyzer_for_OSM
http://wiki.openstreetmap.org/wiki/Bing/Coverage

**Closed by bhousel** 2016-04-11 19:08 UTC

**Comment by aawiseman** [comment] 2016-04-11 19:52
Ah ok. I was thinking something like with the Tasking Manager where it shows the Task number in text within the square.
