### ISSUE TITLE
Discard `*:wikipedia` tags on preset change

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9936] opened 2023-10-09 07:13 UTC
### How to reproduce the issue?

1. Add a point
2. Apply Shell preset on it
3. Add `brand:wikipedia=en:foo` (for simulating a case where it already exists)
4. Change the preset to another brand (doesn't matter if it's petrol station, a supermarket or something completely diffrent)
5. (notice that all tags changed except `brand:wikipedia`)

The same is true for `operator:wikipedia` and possibly for `network:wikipedia`.

Since those tags are no longer maintained by NSI, it would be good to discard them on preset change. Also having `brand=Lidl + brand:wikipedia=en:Shell` seems a bit misleading.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.1

**Comment by gitgutgit** [comment] 2023-10-15 13:54
I would like to take on this issue. Please assign it to me. Thank you!

**Comment by tyrasd** [comment] 2024-02-16 12:19
this is essentially a duplicate of #9103

**Closed as completed by tyrasd** 2024-02-16 12:19 UTC
Labels: bug, preset, duplicate
