### ISSUE TITLE
"New Community Messages" Dialog for unresponsive mappers 

### ISSUE THREAD

**Issue by julcnx** [openstreetmap/iD#9745] opened 2023-07-10 01:01 UTC
# Background 

A lot of communication issues arise because users aren’t responsive to community messages.

Most of the time, senders think the recipients are purposely ignoring them, but as we’ve discussed here, some mappers may not even be getting the email notifications or they’re just not good with managing emails.

From what I’ve seen, many of these users are beginners who rely on iD as their main editor.

Implementing this feature would ensure that users who are currently uninformed become aware of the messages, and it would provide us with a clear indication if a user is intentionally ignoring them.

# Solution

To enhance user experience, I suggest to introduce functionality that utilizes a modal to notify users about the following:
- Unread messages
- Unreplied changeset comments

This modal should be displayed when users navigate to the iD editor (/edit or /id), provided there are any pending messages.

![demo](https://community-cdn.openstreetmap.org/uploads/default/original/2X/1/10213de356ff0ed1beb1d0fec5142a037f359bb4.png)

Since this dialog is targeting new users who never or rarely respond to messages/comments,  the dialog could be disabled based on certain statistics for experienced mappers (tbd)

Sources:
- https://community.openstreetmap.org/t/suspicious-user-activity-potential-fictional-mapping-vandalism/100336/12
- https://github.com/openstreetmap/openstreetmap-website/issues/4080

**Comment by nickrsan** [comment] 2023-07-10 05:35
I think this is a good idea, but I think iD is likely the wrong place to solve this problem at the current moment. I think gravitystorm's point in openstreetmap-website#4080 about building a proper notification system before solving this type of comment visibility issue is a good one - without that, iD would also struggle to know which notifications to surface (and wouldn't have a backing data store to record that information on its own), and would have to build out infrastructure that doesn't exist now, creating more fragmentation. I'm going to mark this as wontfix here for now, but leave it open until a maintainer of iD weighs in. I do hope that there is progress on it in the website repository though.

**Comment by nickrsan** [comment] 2023-07-10 19:12
It also looks like this is a duplicate of #8468 (which never got a response from maintainers either), so I'm going to close this issue now, but it's now cross-referenced with #8468, which I'm leaving open to track the idea.

**Closed as not planned by nickrsan** 2023-07-10 19:12 UTC
Labels: wontfix-not-iD, duplicate

**Comment by aawiseman** [comment] 2023-07-11 20:15
Part of my thought for suggesting this as an iD issue rather than OSM.org is it can be very time consuming to get people to agree to make changes to osm.org. Maybe there is some stopgap like a popup in iD, "Hey, you got a message! Click here to read"

**Comment by nickrsan** [comment] 2023-07-11 20:23
Yeah - and a maintainer would have to confirm, but I suspect iD will run into some of the same challenges that caused gravitystorm to balk at the concept for the website though - namely that without a proper notifications system, knowing that a changeset comment is new or not is non-trivial. We'd then need iD to store some kind of data tracking new/old comments, etc, or doing some fuzzy logic about dates and times. It also gets iD out of its core functionality a bit - not always bad, but like a challenge at the moment. It would be good to go through and do the work to solve the root problem fully and build out a full notifications system instead.

I don't want to sound down on this idea though - I think it's a very good idea that solves an important problem, but I don't personally think iD is the right tool to solve it at this moment. I'd be genuinely curious what the maintainers or other community members think - I'm just here to solicit additional information when needed, communicate with people, and perform ticket triage - I don't make the decisions.

**Comment by aawiseman** [comment] 2023-07-11 20:35
I understand. In my experience they don't really like any changes at all -- like the first person (who I think is a maintainer) who said it's not needed because there is already email. I'm not really sure how to get that conversation started and have it lead to some next steps. It's a tough issue to solve, for sure.
