### ISSUE TITLE
Context menu stays open

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7260] opened 2020-01-17 22:27 UTC
Master branch

**How to replicate**

1. Right click to open the context menu on any item.
2. Click on any of the fields in the "Inspecting" box or any of the buttons in the top row except for Center, Delete or Save.

**What happens**

The context menu stays open no matter what you do, until you you click on one of the options in the menu. You might not want to do this.

**What should happen**

The context menu should close, like it does if you click Center, Delete or Save.

Thanks!

**Comment by quincylvania** [comment] 2020-01-17 22:41
Thanks, I'm closing this since it's the same as #7143, but the steps to reproduce it are really helpful!

**Closed by quincylvania** 2020-01-17 22:41 UTC
