### ISSUE TITLE
Conflict can't be resolved

### ISSUE THREAD

**Issue by trofimich** [openstreetmap/iD#9697] opened 2023-06-12 09:10 UTC
### URL

https://www.openstreetmap.org/edit#map=19/50.07949/34.72675

### How to reproduce the issue?

I have two conflicts with user 'retrun'. I've tried to resolve the conflict, but i can't. After resolving editor hangs in infinite loop with message: Uploading changes to OpenStreetMap.  Checking for conflicts...

### Screenshot(s) or anything else?

![Screenshot 2023-06-12 120755](https://github.com/openstreetmap/iD/assets/36424453/849d76d3-764e-4857-8aae-8669136e80e9)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by nickrsan** [comment] 2023-06-27 05:38
Hi there - can you provide any more information about the conflicts you have with that user? The information right now doesn't provide the ability to reproduce your issue or track down a potential source. Is the issue still occurring?

For triage, this is likely a duplicate of #7199.

**Comment by trofimich** [comment] 2023-06-27 05:47
Hello, in version 4.4.7 problem still exists.


вт, 27 черв. 2023, 08:38 користувач Nick Santos ***@***.***>
пише:

**Comment by nickrsan** [comment] 2023-06-27 05:51
Could you clarify the version again? The released version of iD is only 2.25.2, so are you referring to the version of something else?

It sounds like the issue is that it never stops searching for conflicts. Can you confirm if issue #7199 describes the same issue you're having?

**Comment by trofimich** [comment] 2023-06-27 06:59
Ah, sorry, i've confused bug reports with osmand.

I currently can't check the behavior because i've made changes rollback.

And yes, this behavior is similar to #7199

вт, 27 черв. 2023, 08:52 користувач Nick Santos ***@***.***>
пише:

**Comment by nickrsan** [comment] 2023-06-28 02:30
Ok, I'm going to close this as a duplicate then since it is tracked in the other issue.

**Closed as duplicate by nickrsan** 2023-06-28 02:30 UTC
Labels: duplicate
