### ISSUE TITLE
way extender tug-arrow need to be move from underneath icon column

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9880] opened 2023-09-03 13:15 UTC
### How to reproduce the issue?

We are editing a way.
If the way extends beyond the screen, the little arrows (that
we can click on to tug on to add new nodes) get adjusted so
there will still be one somewhere on the screen.

So good so far.

The problem comes when the way extends underneath the column of
icons on the right side of the screen.

In this case the arrows need to be moved out of underneath the icons.

Else, even though we can see them, we can't click on them.

### Screenshot(s) or anything else?

![20230903T081106](https://github.com/openstreetmap/iD/assets/1230959/fe007c7a-a068-462e-bff5-d573cd18a53c)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

**Comment by 1ec5** [comment] 2023-09-04 04:32
Duplicate of #8192

**Closed as not planned by 1ec5** 2023-09-04 04:32 UTC
