### ISSUE TITLE
Saving changes to very large relations takes a very long time

### ISSUE THREAD

**Issue by bborkmiller** [openstreetmap/iD#4361] opened 2017-09-20 14:37 UTC
I think iD might have an issue editing very large relations. I made a minor edit to the Lake Huron relation and it took Chrome a very long time (> 1 hour) to finish saving the changes (in fact, it's still chugging away).* While it was in the process of saving Chrome's memory usage for that tab was very high:

![image](https://user-images.githubusercontent.com/5290258/30647018-8afb17ca-9de8-11e7-8d00-279a5ad3d2ef.png)

Chrome version 60.0.3112.113 on Windows, iD version 2.4.1

*Once my changeset finishes saving, I'll link to it here. I had a similar problem yesterday with [this changeset](http://www.openstreetmap.org/changeset/52193129) but the one I'm saving today is much simpler and it still is taking a long time to save.

**Comment by bhousel** [comment] 2017-09-20 14:41
Yes, I'm not surprised.. I think this is #3056

**Comment by bborkmiller** [comment] 2017-09-20 15:07
Makes sense! FYI, it looks like [my changeset from yesterday](http://www.openstreetmap.org/changeset/52193129) took about four hours to finish saving. I'm a little concerned (maybe without justification) that a conflict will crop up while iD is running its checks.

**Comment by bborkmiller** [comment] 2017-09-20 18:50
FWIW, my other changeset did successfully save, eventually. [Here's a link](http://www.openstreetmap.org/changeset/52217421), in case it helps to have a cleaner example.

Thanks for all your work on iD! I use it just about every day.

**Comment by bhousel** [comment] 2017-11-14 20:09
> Thanks for all your work on iD! I use it just about every day.

Thanks for the kind words! ...

**Comment by bhousel** [comment] 2017-11-14 20:09
closing as duplicate of  #3056

**Closed by bhousel** 2017-11-14 20:09 UTC
Labels: performance
