### ISSUE TITLE
Don't suggest upgrading to brands from incompatible countries

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#6513] opened 2019-06-10 07:02 UTC
iD say this node https://www.openstreetmap.org/node/2459170313 has outdated tags, and suggests the user updates them, however the changes made are incorrect.

iD adds https://en.wikipedia.org/wiki/Home_Hardware but the store is actually https://en.wikipedia.org/wiki/Home_Timber_%26_Hardware

I checked name-suggestion-index but all the "Home Hardware"'s have a `ca` countryCode, so iD shouldn't be suggesting it from name-suggestion-index.

**Comment by matkoniecz** [comment] 2019-06-10 17:02
And `ca` is not a recent addition - see https://github.com/osmlab/name-suggestion-index/blame/master/brands/shop/hardware.json

**Comment by quincylvania** [comment] 2019-06-10 17:28
Related: #6479

**Comment by 1ec5** [comment] 2019-06-11 02:09
Duplicate of #6448?

**Comment by bhousel** [comment] 2019-06-11 02:14
> Duplicate of #6448?

Oh yeah, I thought I saw this before - you are right.
FWIW I just upgraded the NSI matcher today to allow it to consider countryCode.  
We'll probably release a patch to iD in the next week or so.

**Comment by picsi** [comment] 2019-06-27 05:04
Conversely, I recently made good use this "bug". I used the Brazilian preset for a Brazilian bank with branches in Japan, and the only thing I needed was to add a Japanese translation of its name.

I think this can be useful for multinational companies.

**Comment by andrewharvey** [comment] 2019-06-27 05:06
> Conversely, I recently made good use this "bug". I used the Brazilian preset for a Brazilian bank with branches in Japan, and the only thing I needed was to add a Japanese translation of its name.

The correct way to deal with this is in name-suggestion-index, to either widen the supported county codes, or add a new entry for each country which usually means changing name to the local language.

**Comment by quincylvania** [comment] 2019-10-03 14:19
> FWIW I just upgraded the NSI matcher today to allow it to consider countryCode.
We'll probably release a patch to iD in the next week or so.

@bhousel Was this done?

**Closed** 2019-11-07 18:22 UTC
Labels: bug, validation
