### ISSUE TITLE
Save and cancel buttons disappearing in save mode

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4606] opened 2017-12-08 21:13 UTC
I tried to upload a larger changeset (188 edits) to OSM but when I pressed the save button, the save dialogue opened but the save button, the cancel button and the object list disappeared. 

![save button disappearing](https://user-images.githubusercontent.com/31667811/33783264-5b036358-dc5c-11e7-9a3e-5e9d271674ba.png)

It was impossible to cancel save mode for me and so I had to reload the tab. I was quite relieved when iD restored my changes, but when I pushed the save button once more, again neither the buttons nor the objects list were shown.

When I made some smaller edits in another tab everything worked fine. So it is definitely not a network issue. I had also disabled all JavaScript and ad blockers.

The console returned the following:
![image](https://user-images.githubusercontent.com/31667811/33783828-9e81a3f4-dc5e-11e7-83bc-0b6d7a77e5d6.png)

After restarting the browser and restoring the changes in iD I finally could upload my changeset.
Can someone please fix that strange bug? Or am I doing something wrong?

I'm using **OS X Yosemite 10.10.5** and **Firefox 57.0**.

**Comment by speedbiker** [comment] 2017-12-09 06:35
Same trouble here. 
I have worked on my Windows computer and uploaded several smaller changesets (with approx. 20-30 revisions). On my Mac computer I have a larger changeset with currently 60 revisions and there is no way to upload it. Save and cancel buttons do not appear.

**Comment by bhousel** [comment] 2017-12-09 16:31
Thanks this is a duplicate of #4108..

The workaround is to cancel the save, then undo your work back to whatever point doesn't cause the "entity not found" error anymore.  Nobody has yet been able to tell me what actual edit they did to get iD into this state, so I'd love if you can figure it out and add some info either here or on #4108.

**Closed by bhousel** 2017-12-09 16:32 UTC
