### ISSUE TITLE
Too difficut to select parent parking of parking space, add drop-down menu to select between all overlapping features nearby

### ISSUE THREAD

**Issue by Nekzuris** [openstreetmap/iD#10439] opened 2024-08-26 23:44 UTC
### Description

I'm aware of #2225 and #8264, but I was stuck for a long time trying to select the main parking area [here](https://www.openstreetmap.org/edit?way=849745943#map=21/53.2146861/5.8025116) because it's covered with parking spaces and the `Ctrl` + `↑` shortcut doesn’t work when the parking space is selected. You need to select the right point first, only then the shortcut goes to the parking area.
Also, the shortcut is hard to find and not intuitive.

I would suggest adding a drop-down menu to select between all overlapping features nearby. This menu could be opened with a right-click, middle-click, or simply by hovering the mouse over the area for 1 second (like in Autodesk Inventor).

**Comment by Dimitar5555** [comment] 2024-08-27 08:38
An easier change would be to make the `amenity=parking`'s inner padding wider, like it's done with `building` and `building:part`.

![image](https://github.com/user-attachments/assets/844a2cf1-d469-4f3d-b492-06a9f340d547)

**Comment by danieldegroot2** [comment] 2024-08-27 13:39
Duplicate of #10320.

**Comment by Nekzuris** [comment] 2024-08-27 15:32
Yes that would work for this case, but a menu would also help with other unforeseen issues.

**Closed as completed** 2024-09-03 14:24 UTC
Labels: usability
