### ISSUE TITLE
Impossible to move vertex where >2 ways meet

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3195] opened 2016-06-26 20:04 UTC
Hello, I select multiple node with lasso tool and get this error when trying to move the object (pressing 'M' or select move)
`Uncaught TypeError: _.all is not a function http://www.openstreetmap.org/assets/id-9ca207c97ef84deab28b6843fd32558f76813663630fcf0d2efec1741b4ca70c.js
t	@	id-9ca207c….js:80
r	@	id-9ca207c….js:17
Dt	@	id-9ca207c….js:17
r	@	id-9ca207c….js:80
p	@	id-9ca207c….js:80
n	@	id-9ca207c….js:82
overwrite	@	id-9ca207c….js:82
(anonymous function)	@	id-9ca207c….js:78
l	@	id-9ca207c….js:81
(anonymous function)	@	id-9ca207c….js:1`
All the cuted links are: http://www.openstreetmap.org/assets/id-9ca207c97ef84deab28b6843fd32558f76813663630fcf0d2efec1741b4ca70c.js

Note that I can move node by drag and drop.

**Comment by homersimpsons** [comment] 2016-07-06 11:20
Note that after this recent change are removed as in #3155

**Comment by tyrasd** [comment] 2016-07-07 11:10
Confirming the issue, but it happens only if in the selection a vertex which has more than 2 parent ways is included (e.g. a road intersection). And then it also happens when trying to move one of the involved ways using the move operation (but not when dragging the vertex itself).

**Comment by tyrasd** [comment] 2016-07-07 11:14
seems like the `.all` method of lodash is simply missing here: https://github.com/openstreetmap/iD/blob/master/Makefile#L132

**Comment by tyrasd** [comment] 2016-07-07 11:30
The crash is fixed in 50bae40 (newer lodash versions don't have `_.all` anymore, it's just `_.every` now).

But anyway, the behavior in this case feels quite strange:
[iD-issue-3195.ogv.zip](https://github.com/openstreetmap/iD/files/352024/iD-issue-3195.ogv.zip) Is this really the intended behavior?

**Comment by bhousel** [comment] 2016-07-07 18:23
> But anyway, the behavior in this case feels quite strange:
> iD-issue-3195.ogv.zip Is this really the intended behavior?

Nope, that looks like a bug. When moving entire ways, the code is supposed to slide the moving way along the fixed way.  However when moving individual nodes (as when you lasso them) it should just let you move them wherever you want to.  

The one possible exception to that rule:  if that vertex also connects to a hidden feature, I believe iD prevents you from moving it.

**Comment by homersimpsons** [comment] 2016-07-07 21:08
Is a deleted object consider as a 'hidden' feature?

**Comment by bhousel** [comment] 2016-07-07 21:26
@homersimpsons No, once deleted the object is gone.

"Hidden" in this sense means that iD is not drawing the feature because either the user unchecked it in the "Map Data" panel, or it is automatically culled because too many of them would be drawn on the screen (e.g. buildings).

See in this case below, I unchecked "Paths" and now the sidewalks and crossings are not rendered, but I'm prevented from moving anything that connects to them.

<img width="491" alt="screenshot 2016-07-07 17 24 09" src="https://cloud.githubusercontent.com/assets/38784/16670337/c267b0d2-4467-11e6-98b6-0aa835691e4c.png">

**Comment by homersimpsons** [comment] 2016-07-07 21:49
Then I can ensure you that this is not related to hidden object (because there weren't hidden object when trying to move).

**Comment by homersimpsons** [comment] 2016-07-17 18:41
Have a look there: http://www.openstreetmap.org/edit#map=20/46.70454/4.24953
Select (with lasso -tool) the 4 grouped building and try to move them. There is a point that don't move, while it's selected. 
I don't know why, nossing in console. 
[Impossible move_2.zip](https://github.com/openstreetmap/iD/files/368073/Impossible.move_2.zip)
(mkv video to show you)

**Closed** 2016-07-25 00:39 UTC
Labels: bug

**Comment by homersimpsons** [comment] 2016-08-11 21:52
This still doesn't move all nodes. You can try again with the same example.
Maybe you didn't push the release ?

**Comment by bhousel** [comment] 2016-08-12 05:38
> This still doesn't move all nodes. You can try again with the same example.
> Maybe you didn't push the release ?

Yes, 1.9.7 was released 27 days ago, so this fix isn't in it.  But you should be able to test the fix on https://openstreetmap.us/iD/master/ which is always updated with our latest code.

I don't have a plan for another release yet, but lately we've been releasing about once a month.
