### ISSUE TITLE
URL coordinates are reversed in any local deployment

### ISSUE THREAD

**Issue by tudorg-telenav** [openstreetmap/iD#3402] opened 2016-09-06 12:02 UTC
Hi,

I'm following all the steps described in the installation document, but what I end up with is a perfectly working local version of the ID editor that has it's URL coordinates **REVERSED**!!!!

Example:
**Manhattan on the official ID editor site:**
https://www.openstreetmap.org/edit?editor=id#map=14/40.7163/-73.9923
**Manhattan on my local ID editor site:**
http://localhost:8080/#background=Bing&map=14.64/-73.9973/40.7165

As you can see the coordinates are reversed in my version.
This is a problem only when trying to share a URL between sites. Very annoying.
Any idea on why this thing is happening.

By the way, I'm talking about any fresh copies (no changes from my part).

Thank you,
Tudor

**Comment by tmcw** [comment] 2016-09-06 12:49
Hi Tudor,

This is a duplicate of https://github.com/openstreetmap/iD/issues/1750 and was also filed as https://github.com/openstreetmap/iD/issues/2610 . Closing, since we've discussed this issue before.

- Tom

**Closed by tmcw** 2016-09-06 12:49 UTC

**Comment by bhousel** [comment] 2016-09-06 12:55
Hey @tudorg-telenav, yes, iD follows the d3/geojson convention of having longitude before latitude.  

You can change this in your fork pretty easily by swapping the values in `hash.js`
[here](https://github.com/openstreetmap/iD/blob/master/modules/behavior/hash.js#L13-L14) and [here](https://github.com/openstreetmap/iD/blob/master/modules/behavior/hash.js#L37-L39)

**Comment by tudorg-telenav** [comment] 2016-09-06 15:27
@bhousel thank you very much, I care very little for the dispute about the right order, but and very much for a somewhat tested&proven way of tinkering it
