### ISSUE TITLE
Standard browser link preview in lower left corner interfered by 'View on openstreetmap.org' link

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9701] opened 2023-06-12 21:24 UTC
### Description

Select an item on the map.
Here in the lower left corner of the screen the
'View on openstreetmap.org'
link is smack dab in the same spot as the standard browser hover link preview,
![20230612T161915](https://github.com/openstreetmap/iD/assets/1230959/5f739a40-9876-4aaf-9782-9817dbcbac5f)
which causes difficulties when trying to see where it will lead us.
One must use fancy hand motions, etc.

**Comment by 1ec5** [comment] 2023-06-12 23:49
Which browser are you using? In Firefox, for example, the link bar gets nudged to the lower-right corner when hovering over a link in the lower-left corner.

**Comment by jidanni** [comment] 2023-06-13 09:01
Chrome. On Linux.

**Comment by nickrsan** [comment] 2023-06-30 05:32
What version of Chrome are you running so we can reproduce? I don't see this behavior in Chrome on Windows - it pops the link preview to the other side.

**Comment by jidanni** [comment] 2023-06-30 12:38
115.0.5790.56 (Official Build) beta (64-bit)

But you know what, I think it more matters how the window system
interacts.
- in fullscreen mode, indeed the link is shown in the lower right
corner.
- otherwise, depending on if the browser thinks there is a row of (e.g.,
i3) window manager tabs below the browser, some attempt to show it in
place or sightly lower happens.

in other words it is one big mess. All the better reason to avoid those
corners.

**Comment by nickrsan** [comment] 2023-09-14 17:10
I'm going to close this one as not likely to happen right now since there are good alternatives and other priorities - that's not saying it's not a good idea to move it, just that I don't see it ending up on a roadmap. One alternative is using the history panel to link to objects on OSM.org instead, which doesn't present the link in the same location.

**Closed as not planned by nickrsan** 2023-09-14 17:10 UTC
Labels: waitfor-info, wontfix-low-impact, enhancement
