### ISSUE TITLE
Having a Streetview/Mapillary open image prevents standard ID operations

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/iD#10553] opened 2024-11-24 10:28 UTC
### URL

https://www.openstreetmap.org/edit?#map=19/-36.717050/141.372030

### How to reproduce the issue?

**Mapillary**

1. Using Chrome (I am using Windows 131)
2. Open the Map Data/Mapillary layer
3. Click one of the Mapillary icons and the image should be displayed.
4. Now try and square one of the buildings by moving a node slightly and then use the Q key <-- fails
5. Close the image and square one of the buildings by moving a node slightly and then use the Q key <-- success
6. Re-open the image and then do long drags of the map to the east <-- jerky and sometimes fails to move 
_mapillary-e7bb57e05dff3736762bd4a74954d7abac85ebf7f90cee2f7078c64ba9764b7e.js:59 Failed to cache periphery bounding box (810944086462485) Error {stack: 'Error\n    at https://www.openstreetmap.org/assets/…d7abac85ebf7f90cee2f7078c64ba9764b7e.js:15:11742)', name: 'EmptyError', message: 'no elements in sequence'}_

During this time the following messages was logged but I am not certain if this is related...

id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:59:13318)
    at id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:20:5711
    at Array.map (<anonymous>)
    at o (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:20:5701)
    at o (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:20:6640)
    at id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:20:8316
    at Cn.call (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:37:6263)
    at a.gatherStats (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:19:9065)
    at a (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:19:21910)
    at u (id-e8221ab7ed8a1fdee5857b0f9eaae02b84ca891e664067ef0c1162f5e76d0740.js:19:24770)

**Bing Streetview**
1. Repeat the same as above with no issues at https://www.openstreetmap.org/edit?#map=20/-37.7820954/144.9900292 

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome

**Comment by danieldegroot2** [comment] 2024-11-24 11:12
Failing an action with `Uncaught TypeError: Cannot read properties of undefined (reading 'transient')`

It should work if you try the development version at https://ideditor.netlify.app/
This will be available on the openstreetmap.org website at a later time.

Duplicate of #10417.

---
Regarding `Failed to cache periphery bounding box`

Reproduced in Chrome 131.0.6778.86 on Windows 10 but at a different position in this sequence.
I assume you were mapping along this sequence. Moving through a sequence too fast (and constantly having it at the edge of your screen) will trigger this.
clicking the 'next image' button repeatedly (and enabling 'play sequence') will eventually, after some CORS/rate-limiting errors, return

```
mapillary-e7bb57e05d…8c64ba9764b7e.js:59 Failed to cache periphery bounding box (222421790469429) MapillaryError: Failed to fetch data
    at mapillary-e7bb57e05d…9764b7e.js:57:30486
```
```
mapillary-e7bb57e05d…8c64ba9764b7e.js:21 
 GET https://graph.mapillary.com/images?s2=7696279131478032384&fields=id,computed_geometry,geometry,sequence net::ERR_FAILED 429 (Too Many Requests)
```
```
mapillary-e7bb57e05d…8c64ba9764b7e.js:59 Failed to cache periphery bounding box (232396206115295) 
Error {stack: 'Error\n    at https://www.openstreetmap.org/assets/…d7abac85ebf7f90cee2f7078c64ba9764b7e.js:15:11742)', name: 'EmptyError', message: 'no elements in sequence'}
```

These errors are more to notify you about rate limiting/CORS. You may also get mesh error warnings on certain sequences, which are returned if a sequence is too sparse to make a 3d reconstruction. This should not impact any actions.

**Comment by tordans** [comment] 2024-11-24 16:11
Ping @tyrasd to please release [the Bugfix](https://github.com/openstreetmap/iD/commit/31bef9f064e20116a5ed5c815a1f722cec5601c7) that was pushed 2 month ago so we can use iD with Mapillary properly again…

**Closed as completed** 2024-12-03 09:23 UTC
Labels: bug, duplicate
