### ISSUE TITLE
Disappearing Save/Cancel buttons?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4108] opened 2017-06-14 22:57 UTC
As reported here:  https://help.openstreetmap.org/questions/56164/save-button-disappeared

> I made a large quantity of small edits straightening roads and paths. Now when I try to save, I have no save button. If if close my browser and reopen, it allows me to restore my edits, but still the save buttons is gone. I am using Firefox 53.0.2 on Windows 7.

My guess is that there is some bad JavaScript in the `commit.js` that just gives up before the code where the buttons get rendered.

**Comment by boothym** [comment] 2017-09-29 17:12
Similar thing just happened to me. Did some editing, then moved away a bit to fix a gap in a relation. The relation I wanted to add didn't show up in dropdown, so I refreshed the page and reloaded the changes. It appeared, but when I clicked on it the relation name went into the box but didn't turn blue. 

When I tried to save, no buttons appeared and when I pressed ESC the comment box stayed where it was. Didn't want to lose all my changes, so eventually solved it by going back to the node shown in the error and deleting the way connected to it.

![untitled-1](https://user-images.githubusercontent.com/16965772/31020579-55192abc-a52b-11e7-85ef-539468876d19.jpg)
![untitled-2](https://user-images.githubusercontent.com/16965772/31020577-5425f2d4-a52b-11e7-9c7a-339168bfd8ca.jpg)

**Comment by Slawek234** [comment] 2017-10-12 08:24
I was the same problem. I using Opera 48.0.2685.35 in Windows 10 64-bit. In my cause was a **new restriction** type=restriction restriction=only_right_turn . All changes saved.

**Comment by pgavrilov** [comment] 2017-11-07 08:37
I have same problem.

If I close browser window and reopen it again, iD suggest me to restore not applied changes (so this changes aren't lost yet), but I again can't see save button.

Firefox 56.0.2. Win7 64bit.
I tried to disable adblock (Ublock Origin) - no effect
I tried to start Firefox in safe mode (without addons) - it even can't open iD editor page.
I tried to enter iD Editor with another browser with same login name - it doesn't see my changes.

List of changes too large to find and fix the element caused problem.

**Comment by bhousel** [comment] 2017-11-09 19:27
I have a feeling that bd639f2da might be the fix for this.
We'll release a new version of iD in the next few days, and watch to see if this issue goes away in the next few months.

**Comment by Slawek234** [comment] 2017-11-11 01:01
Today 00:40 I had the same problem in Opera(chrome similarly).
In my case, the id editor works better in Firefox.

"List of changes too large to find and fix the element caused problem."

**Comment by Slawek234** [comment] 2017-11-13 01:56
Today I lost 2h again. I'm forced to give up the widespread use of the ID editor because of this bug. 
This bug is scary in no way can save the data!

**Comment by systemed** [comment] 2017-11-13 08:44
> Today I lost over 2h my work again

You shouldn't trust two hours of work to _any_ online tool without saving. Save early, save often. Bugs happen.

**Comment by Slawek234** [comment] 2017-11-13 10:38
You are right, my fault, but that similar problem in the editor id I did not have before. This bug has been around for 2-3 months and I think the worst of all is.

The emergency saving in the web browser works perfectly.

**Comment by boothym** [comment] 2017-11-13 13:43
Next time I can only suggest using the undo button to go back and try to find out exactly where the save button becomes usable again.

**Comment by bhousel** [comment] 2017-11-13 13:57
> Today I lost over 2h my work again.

I'm sorry to hear this!  Nobody likes to lose data..

Like @boothym said, if you can do smaller edits and let me know specifically what change it was that you made that caused the "Entity nnnnn not found" message that's preventing the save buttons from appearing, that would be fantastic.   We know from your comment above that there might be an issue with adding turn restrictions.  

An ideal bug report would be something like: "I went to this specific intersection and tried to add a no right turn from this way to that way, and after that the save buttons became broken".   I would really like you to continue using iD, since you are one of the only people that seems to hit this bug regularly!

There is a lot of unusual data in OSM and it would not surprise me if iD gets confused by intersections that have some redundant turn restrictions put on them.

**Comment by Slawek234** [comment] 2017-11-13 20:13
I still use and will continue to use the editor ID. Thank you very much for creating and developing editor ID. It is amazing! As soon as I get a problem with the button, I'll try to describe it.
I do not know exactly where the problem is. The problem with the disappearing button I noticed at the end of August the beginning of September. Appears in Chrome, Opera, Firefox with the least Firefox (in my opinion) When editing, I have a lot of open tabs in the background.

Last case maybe it was related to the fact that I had 216 changes to send. I pressed the submit button I waited about 20min changed was still not sent. Firefox reported that it is hung every few seconds (this is normal for a few weeks) I decided to restart the web browser and re send after web browser reboot. After reboot I already had about 213 changes to send but has not resumed sending again due to lack of button.
At the moment I do not know exactly where the problem lies in the browser, the editor, maybe the behavior of the user or somewhere else.

**Comment by boothym** [comment] 2017-11-13 22:44
Over 200 changes is quite a lot - I worry when I get close to 100 in case something happens! 😄  But like I said, press the undo button until you get the save button back - I did this the last time and was able to find the problem and not lose any changes.

**Comment by Slawek234** [comment] 2017-11-24 20:10
Hello. A few days was fine. Today, unfortunately, the situation was repeated.
During map editing, Firefox crashed and after reboot, was unable to send data. The send button has traditionally disappeared.
Method with "press the undo button until you get the save button back" did not work.
I had this time about 240 changes. Every 50 changes I checked to save. It was OK.
The last one was at 207 change.
Firefox crashed while editing this line https://www.openstreetmap.org/way/108570480#map=16/51.9323/19.2701 A crash report was sent to Firefox.

**Comment by boothym** [comment] 2017-12-06 22:29
My previous issue where clicking on the "untagged area" error message when saving made strange things happen seems to have gone away. 😄 I was able to click the message, go to the area and tag it, then save without any issue.

**Comment by boothym** [comment] 2017-12-22 01:13
Unfortunately got this error again with 180 changes pending. I was only checking occasionally if it saved, but it took me until I was back to about 30 changes until I could save again. I then used redo and amazingly got all of the changes back - lots of clicking!

**Comment by leveskockaa** [comment] 2018-01-18 10:33
This happened to me around 5 to 7 times, always with larger changesets, but it's hard to predict when it'd happen. It is still present in the current (2.5.1) version. What's interesting is that once I was able to save my edits after some time, I'm not sure how this is possible, but just as I was planning to cancel the edits to allow me to use iD again, the buttons have somehow appeared and I could save it. I believe it was [this](https://www.openstreetmap.org/changeset/54464218) changeset

**Comment by boothym** [comment] 2018-02-13 14:11
Had this occur again. I was panning the map and noticed the landuse jump a bit so thought I might get the error - made some more changes and sure enough, the save button disappeared. 

I did the same as before, undoing then redoing my changes. But when I got the Error: entity n<node> not found, I found that node in another tab, then panned to that location in iD. I was able continue redoing, and eventually save the changes.

**Comment by mvl22** [comment] 2018-03-03 14:15
I've just run into this for the first time. The console (in Chrome) shows me:

![screen shot 2018-03-03 at 14 14 10](https://user-images.githubusercontent.com/361423/36935238-4806cb54-1eed-11e8-9f0b-4d54d882b869.png)

**Comment by bhousel** [comment] 2018-09-21 03:56
> Has this been worked on ? Happened to me again today. Very annoying.

Nope, sorry - it never happens to me.  I wish it did so I could fix it.

**Comment by boothym** [comment] 2018-09-21 18:53
@bhousel try making some edits (say, 10+) in one place, then closing the tab. Open a new tab somewhere completely different, restore the edits and try to save. 

If I do that and the save button disappears, I check the console for an error node, then refresh the page and restore my edits. Paste the error node into the search box, and zoom to that node - once I've done that and clicked save, the button reappears as normal.

So to me that indicates that iD has trouble loading all of the things that is supposed to which causes an error?

**Comment by dendik** [comment] 2019-01-07 15:20
@bhousel Hit the bug myself today. Worked around as described above.

Then I set to reproduce the bug, and this sequence doest it repeatedly:

 - open editor above any highway=*
 - add a new crossroads (create new line from a point on the road; add some highway=* tag)
 - scroll away far enough for the selected crossroad to not be pulled upon reload (I scrolled four screenfuls away from the highway=* to be safe)
 - reload the webpage and recover history
 - attempt to save

While testing this scenario, I found a simpler workaround for this bug: after reloading scroll over all edited land before hitting "save".

Very distressing bug, as it only affects those who make huge changesets and only if a crash happened during editing.

**Comment by Martin868** [comment] 2019-01-21 22:34
I can confirm this bug happen with Safari, so that makes it at least two browsers.

**Comment by quincylvania** [comment] 2019-01-22 15:04
> I can confirm this bug happen with Safari, so that makes it at least two browsers.

@Martin868 Thanks for noting this! I checked, and the steps I posted will produce the same error on Safari, Firefox, Chrome, and probably any browser. Hopefully this makes it easier to track down.

**Closed** 2019-01-22 17:56 UTC
Labels: bug, waitfor
