### ISSUE TITLE
Problems with Mapillary layer

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#8614] opened 2021-08-01 22:50 UTC
Hi there.

Since last iD update, I stopped having access to Mapillary image layer.
I didn't see this mentioned elsewhere, so maybe some kind of local issue, but I tested this with Firefox, Chrome and Opera (all last versions for W10). Firefox shows a black screen when clicking on a image in the image stream. Chrome and Opera shows nothing (not even the stream).

**Comment by tohaklim** [comment] 2021-08-02 10:42
Yep, also having some issues, seeminly CORS related
![image](https://user-images.githubusercontent.com/7071423/127849484-fe128294-f6c9-44de-a6fd-3318fd46073c.png)

**Comment by nickplesha** [comment] 2021-08-02 14:53
Hi!
We're working on fixing this soon, it is indeed not a local issue: the CORS headers on Mapillary vector tiles are not set correctly right now.
Sorry for the inconvenience, I'll post an update when the issue is fixed!

**Comment by mbrzakovic** [comment] 2021-08-02 15:40
Thanks for raising this @AntMadeira.
I remember testing this when v2.20.0 was deployed and it was working. @nickplesha I suppose you had some recent changes to mapillary services? Can this be addressed by updating services on your side only?

**Comment by nickplesha** [comment] 2021-08-02 16:48
Yes, this will be fixed on our side.

**Comment by nickplesha** [comment] 2021-08-03 07:34
Hi! The vector tile issue has been fixed now. Sorry for the inconvenience!

**Closed as completed** 2021-08-03 07:38 UTC
