### ISSUE TITLE
Can't select or interect with elements in Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by redsteakraw** [openstreetmap/iD#4552] opened 2017-11-21 16:04 UTC
When trying to edit in the latest Firefox release you can no longer select or interact with any elements.  The loading spiral is stuck even after all the content is downloaded and the mouse icon is stuck on the hand drag cursor icon.  All satellite imagery and right side panel elements work and can be interacted with including Mapillary overlays, zoom in and out, ect.  Furthermore the create point / line / area don't work.  So no new OSM data can be created or modified.  I tested this with Firefox 57 on a Linux desktop.

**Comment by bhousel** [comment] 2017-11-21 16:08
Yeah this is a duplicate of #4542, #4547, and maybe others. 
It seems to happen mostly on Linux systems with Firefox, so I won't be able to test it, but hopefully somebody from the community will step up to help squash this bug! 👍

**Closed by bhousel** 2017-11-21 16:08 UTC

**Comment by redsteakraw** [comment] 2017-11-21 18:37
Please re open this as there wasn't a problem on Firefox 56 and all the elements are loaded. All the nodes, ways, and what not, and if you move the map to a new area it loads the new objects and renders them. Furthermore, the architecture before Firefox 57 is drastically different and has a completely different rendering engine.

**Comment by bhousel** [comment] 2017-11-21 18:39
I've tested both Firefox 56 and 57 on my Mac and I don't have any issues.  I agree there is probably a bug, but it's already covered by #4542

**Comment by redsteakraw** [comment] 2017-11-21 19:21
I disagree all the data is visible I just can't interact with it.  So #4542 doesn't apply.  Since it is practically a different browser and the way this is manifesting is unique it deserves its own bug.  Yes this also may be Linux specific but they are different Linux bugs.

**Comment by bhousel** [comment] 2017-11-21 19:24
> I disagree all the data is visible I just can't interact with it. So #4542 doesn't apply. Since it is practically a different browser and the way this is manifesting is unique it deserves its own bug. Yes this also may be Linux specific but they are different Linux bugs.

whatever, I'll just reopen #4547, since there is more info on that one.

**Comment by eehpcm** [comment] 2017-11-21 19:49
> Please re open this as there wasn't a problem on Firefox 56 and all the elements are loaded. All the nodes, ways, and what not, and if you move the map to a new area it loads the new objects and renders them. Furthermore, the architecture before Firefox 57 is drastically different and has a completely different rendering engine.

I started #4547 and I'm on Firefox 52 on Linux, so it's not just 57 with its new architecture.  It all went wrong for me on the 16th.  iD was updated to 2.5.1 on the 15th.  I **strongly** suspect the two are connected.  Especially as I get the same behaviour in Edge on Win 10.

When did you upgrade Firefox?  Also, are you running on old, slow hardware, like me?
