### ISSUE TITLE
Degenerate ways with two identical nodes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2318] opened 2014-08-10 18:17 UTC
iD has been creating ways with two nodes, where both nodes are the same. This is an error.

Examples

[296790119](https://www.openstreetmap.org/way/296790119)
[296745175](https://www.openstreetmap.org/way/296745175)
[296678600](https://www.openstreetmap.org/way/296678600)

**Comment by jfirebaugh** [comment] 2016-02-06 01:49
Duplicate of #1296.

**Closed by jfirebaugh** 2016-02-06 01:49 UTC
