### ISSUE TITLE
"Unmarked crossing has incomplete tags"

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#9922] opened 2023-09-30 02:59 UTC
### URL

https://www.openstreetmap.org/edit?note=3757731#map=20/-27.63115/152.61089

### How to reproduce the issue?

1. Add unmarked crossing (crossing=unmarked) via presets
2. Connect to road
3. When saving you get an error message that it has "incomplete tags" to up, & suggests an upgrade to crossing:markings=no, despite "No Road Markings" already being defined

### Screenshot(s) or anything else?

![Unmarkd crossings](https://github.com/openstreetmap/iD/assets/35707521/56c31ecf-9563-433a-a96e-d794a8314f01)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment] 2023-10-02 10:57
Duplicate of #9525

**Closed as completed by 1ec5** 2023-10-02 10:57 UTC
