### ISSUE TITLE
A simpler way of entering opening hours?

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7919] opened 2020-08-21 20:31 UTC
Hey. First off, I totally get it if this is too much work. 

But I just wanted to mention that I've found the opening hours thing very confusing for a very long time. I had to not only read the documentation, but often opening it again and check and double check if I do it right, even after doing it before. I've been thinking about manually finding the places in StreetComplete to enter the information there instead.

I would love it if there was some sort of drop-down select weekdays and clock kind of thing when clicking the opening hours field. Not sure exactly how to implement it, but maybe we could brainstorm that here in this thread?

Thanks!

**Comment by bhousel** [comment] 2020-08-21 20:59
Thanks, yes improving opening_hours entry is #974

**Comment by maro-21** [comment] 2020-08-21 20:59
Duplicate of https://github.com/openstreetmap/iD/issues/974.

Opening hours format it's not so difficult, for majority of cases you use something like `Mo-Fr 08:00-19:00; Sa-Su 10:00-19:00`.
You can also use this tool: https://projets.pavie.info/yohours

**Closed as completed by bhousel** 2020-08-21 20:59 UTC
