### ISSUE TITLE
"Fill" polygone tool option?

### ISSUE THREAD

**Issue by int-ua** [openstreetmap/iD#1631] opened 2013-07-10 03:37 UTC
It seems that there are a lot of situations where already mapped roads or other objects outline some areas of one type (woods, fields, residential areas) and where mapper has to fill these areas manually while it can be done by just filling an empty space between the objects with polygone by a script. The one aspect of such feature I'm not sure about is how to implement controlling minimum distance to other objects while filling.

**Comment by bhousel** [comment] 2016-03-12 03:07
This is a duplicate of #1614

**Closed by bhousel** 2016-03-12 03:07 UTC
Labels: enhancement
