### ISSUE TITLE
Handle potentially dangerous changes to relations

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/iD#2503] opened 2015-01-10 18:30 UTC
## Problem
Relations are depending on their members and changes that are made to them can cause serious problems. Typical change-operations are deleting, splitting or merging ways. There are a lot of reports and complains about iD in that context. There is a thread in the german forum where relation problems/broken relations are collected that have been created by iD (one example: borders of Vietnam collapsed after a deletion of way). Of course every OSM editor has the potential to break things, but the user should at least be warned, that he's doing something malicious. Of course editing a existing relation does not mean by default you're breaking anything, but there are indicators, that can be used to detect this case (e.g. removed outer member and didn't add a new one etc).

## Suggestion
I know big dialog boxes for confirming editing or modals are not welcome. So I'm suggesting two things:

**1.** show a small nearly transparent bar or tooltip close to the right buttom corner that gives information why this change might be critical e.g. "This way is part of relation 1234. Deleting it could cause trouble | Undo"
So the user will get at least a ordinary hint that this change would break something. It might be important to show it immediately (not only on saving process) because the user know what change affected this and it might be easy to repair/undo as if there were plenty of merging operations s.o.

I was thinking of something like an toast view on Android:
![Android flashbar/toast view](http://i.imgur.com/MaXn6LM.png)
It should be designed unflashy and should be easy to get rid of this message (clicking somewehere)

**2.** integrate relation errors to the warnings in the save dialog.

There is already a warning dialog on the save process: (here way without any tags)
![iD editor save dialog warnings](http://i.imgur.com/OmFnfsU.jpg)
I would like to see short but meaningful errors regarding errors - e.g. "Broken Multipolygon missing outer"

## Discussion
I would like to discuss the current state and potential improvements to warn about errors affecting relations.

**Comment by kerosin** [comment] 2015-01-10 18:46
Okay, close related to #1461 and  #2014

**Comment by bhousel** [comment] 2015-01-14 02:23
Thanks for this, I'm closing this one as it's a duplicate of #1461 
I agree, it's a high priority issue...

**Closed by bhousel** 2015-01-14 02:23 UTC

**Comment by kerosin** [comment] 2015-01-14 12:20
Just as a comment:
A UI element like the proposed transparent bar/Tooltip/Toast (however you may call it), might be useful to indicate that you haven't saved your changes for a long time - like mentioned in  #2378 
Potlatch2 editor is making this based on time ("30min since your last save. Please save regulary" or something). Imho a warning based on number of changes in combination of time would  be perfect.
Thanks for attention!
