### ISSUE TITLE
Shortcut for "Toggle location panel" isn't working

### ISSUE THREAD

**Issue by korolenok** [openstreetmap/iD#7942] opened 2020-09-01 11:38 UTC
We have a lot of hotkeys that make editing easier, but one of them is out of order. Now we do not see the panel with the location of the area when using **Cmd+shift+L**. 
<img width="1390" alt="Screen Shot 2020-09-01 at 14 27 23" src="https://user-images.githubusercontent.com/42146546/91844158-9db2a400-ec5f-11ea-9d64-40088a672aea.png">

Only Measurement, History and Background shortcuts are working correctly
<img width="1029" alt="Screen Shot 2020-09-01 at 14 28 27" src="https://user-images.githubusercontent.com/42146546/91844171-a2775800-ec5f-11ea-9df3-997787135345.png">

**Comment by Zetkun** [comment] 2020-09-01 11:50
Hi! It will be great if you can quickly fix this problem. Without this hotkey, data processing speed by our folks has decreased. Thanks! 
cc: @shvrm @abrohood

**Comment by quincylvania** [comment] 2020-09-01 21:10
Welcome, @korolenok. What browser/system are you using? I don't see a problem with this shortcut on Firefox, Safari, nor Chrome on macOS.

You can also open the Location Panel in the Background Settings menu.

![Screen Shot 2020-09-01 at 5 08 47 PM](https://user-images.githubusercontent.com/2046746/91906328-00af3580-ec76-11ea-8111-3cf848facb61.png)

**Comment by korolenok** [comment] 2020-09-01 21:31
@quincylvania I've checked the shortcut on Firefox and Safari - this works correctly for them.
But chrome for some reason doesn't allow using the shortcut (Version 84.0.4147.135 (Official Build) (64-bit)), so it looks like the problem is not on your side. Am I right?
Thank's for advising the Location Panel in the Background Settings menu 👍

**Comment by quincylvania** [comment] 2020-09-01 21:35
Hmm I'm running Chrome `85.0.4183.83 (Official Build) (64-bit)` and it's working okay—must be a bug in 84! Closing this unless it reappears…

**Comment by Andygol** [comment] 2022-06-16 13:24
@tyrasd It seems that we have some sort of regression here. In Chrome (Version 102.0.5005.115 (Official Build) (arm64)) `Cmd`+`Shift`+`L` does not show Location panel, but in Safari everything works fine.

**Comment by tyrasd** [comment] 2022-06-20 17:34
Odd, it works for me (Chrome `Version 102.0.5005.115 (Official Build) (64-bit)` on Ubuntu). Are you observing this on a Mac?

**Comment by Andygol** [comment] 2022-06-21 08:06
Yes, this issue was observed on macOS with Apple M1 Pro CPU.

**Comment by tyrasd** [comment] 2022-06-21 08:30
OK. Unfortunately, I don't have a mac available at the moment to debug this. :/

**Comment by 1ec5** [comment] 2022-06-21 09:23
I can’t reproduce the issue in Firefox 101 or Chrome 104 on macOS. However, I’ve noticed for a while now that none of the shortcuts works when you have a text field, checkbox, or radio button focused. Does the shortcut work if you first click somewhere on the map canvas?

Also, are you using the English localization or a different one? What keyboard layout are you using?

**Comment by Andygol** [comment] 2022-06-21 09:58
I've tested another MacBook Pro 3.3 GHz Dual-Core Intel Core i7, macOS 12.4 and got same results when focus is on the map view. `Cmd`+`Shift`+`L` does not work for Google Chrome. 

In case you don't move focus to the page content, Chrome will use its built-in behavior for iD shortcuts: 
- `Cmd`+`Shift`+`H` - back to home page, 
- `Cmd`+`Shift`+`B` - toggle bookmarks bar, 
- `Cmd`+`Shift`+`M` - switch between users, 
- `Cmd`+`Shift`+`L` - do nothing for Chrome.

Firefox 101.0.1 (64-bit) | Safari 15.5 (17613.2.7.1.8) | Google Chrome 102.0.5005.115 (Official Build) (x86_64)
--- | --- | --- 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/369696/174768805-ddbdf4f7-8567-46d2-a854-668b4a96d9d6.png"> | <img width="1552" alt="image" src="https://user-images.githubusercontent.com/369696/174770591-cf791186-8197-41fe-8d48-ad2e2d1d2a24.png"> | <img width="1552" alt="image" src="https://user-images.githubusercontent.com/369696/174769648-ae91f681-3bb5-4aec-942a-2b79c9d7fa25.png">
All shortcuts work as expected. | All shortcuts work as expected.  | `Cmd`+`Shift`+`L` does not work

**Comment by 1ec5** [comment] 2022-06-21 10:00
> In case you don't move focus to the page content

OK, that’s probably the cause for confusion above. For what it’s worth, Firefox 101 behaves the same way: if a form field is focused, the shortcut is bound to a system shortcut instead. On my system, the default system shortcut for ⇧⌘L is the “Search in [default search engine]” service under the Services submenu of the application menu. A possible workaround would be to disable that service in System Preferences: go to the Keyboard panel, then the Shortcuts tab, then select Services.

**Comment by Andygol** [comment] 2022-06-21 11:46
@1ec5 I've disabled "Search With Google" in System Preferences, restarted Chrome but it changed nothing :(. ⇧⌘L doesn't work in iD using Chrome.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/369696/174791430-f1a98692-022c-4107-b3a8-d161f6e156be.png">

**Comment by Andygol** [comment] 2022-06-21 13:33
@1ec5 I see that you use pre-release version of Chrome 104 on macOS, while I use current official release version of Chrome 102. Maybe it is why you have no issues on your side.

**Comment by evgeniyakarnaukhova** [comment] 2022-06-23 07:19
hello folks, just adding my info here 
I'm using Ubuntu on Lenovo with official version of Chrome as @Andygol I think and the shortcut doesn't work.
![image](https://user-images.githubusercontent.com/52066436/175239201-c30588b6-ae54-475d-b8f9-71e7c3e36afa.png)
![image](https://user-images.githubusercontent.com/52066436/175239433-98f57ff2-538a-435b-a31a-1342f1900c33.png)

**Comment by 1ec5** [comment] 2022-06-23 07:27
Does it work in Incognito Mode? Do you have any extensions installed that are assigned to ⇧⌘L? chrome://extensions/shortcuts

**Comment by evgeniyakarnaukhova** [comment] 2022-06-23 07:34
I had for 1Password (which I use all the time) on Lock the extension.
I removed and it's working!
![image](https://user-images.githubusercontent.com/52066436/175242421-67cb94c8-bd08-4250-934a-c53456ec09eb.png)

O_o
thank you @1ec5 so much!

**Comment by Andygol** [comment] 2022-06-23 07:48
@1ec5 TY for hints.

⌘⇧L shortcut was assigned to 1Password in Chrome, I disengaged it, and it started to work as expected in iD.

@tyrasd the reason of the issue was identified, and it didn't connect with iD, feel free to close this ticket. Thank you for patience.

**Closed as completed** 2022-06-23 13:59 UTC
