### ISSUE TITLE
Species:wikidata hints dropdown became invalid

### ISSUE THREAD

**Issue by afanasovich** [openstreetmap/iD#9135] opened 2022-05-27 11:41 UTC
### How to reproduce the issue?

Now, if you select the `species:wikidata` key for the tree node, now with hints it contains labels [object Object] instead of the necessary hint. Everything was working correctly before

### Screenshot(s) or anything else?

![wikidata](https://user-images.githubusercontent.com/75438207/170692586-960fb92b-44d7-4c4e-a015-69e9f55f853a.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by danieldegroot2** [comment] 2022-05-28 15:59
This is a duplicate of #9067.

If this resolves the issue, feel free to close it yourself. You can find the purple Close issue button below alongside the green Comment button. Make sure to check for similar issues using the :detective: search function in the future.

**Closed as completed** 2022-06-06 08:45 UTC
Labels: duplicate
