### ISSUE TITLE
Tip of the day

### ISSUE THREAD

**Issue by kepta** [openstreetmap/iD#3746] opened 2017-01-12 06:48 UTC
iD is growing everyday, keeping a check on all of the new features added could be a big task. 

I suggest that we add a small tip of the day to the splash screen screen.
![tipoftheday](https://cloud.githubusercontent.com/assets/6966254/21879874/7aa715d2-d8c1-11e6-923e-baf5af92bbc4.jpg)

**Comment by bhousel** [comment] 2017-01-12 06:54
This is kind of like #1856 - maybe just adding a little red dot off in the corner (like what slack does when there is a new release), and link it to our Release Notes.   We could store the last seen version of iD in localstorage and display the dot if the current version is newer than last seen version.

**Comment by bhousel** [comment] 2017-01-13 01:38
> (like what slack does when there is a new release)

I just saw in fact Slack have changed the dot to a red gift wrapped present icon, but same idea.  @kepta, want to put something down next to the iD version when a new version is available?

**Comment by kepta** [comment] 2017-01-13 05:41
@bhousel I was thinking more of a tooltip rather than a link to release notes.
For this we could create a shortlist of all the useful productivity tips and cycle through them. 
What do you think?

**Comment by bhousel** [comment] 2017-03-02 21:00
So, I'm going to close this because, while I like the idea of collecting shortcuts, hacks, and tips someplace, I just don't want to maintain it in the app.  I think we can continue to blog those things, which is better anyway because then we're free to add more explanation, revise them later, add animated gifs, etc.. 

I would be ok if there were some place that collected all these iD tips, like on our ideditor.com site that we don't really use, or on the OSM wiki, or something like that.  And we could link to it from within iD's help, or the splash screen or something.

We can discuss more on this issue how we want to collect tips, but I'm closing it just to make sure somebody doesn't build this feature and surprise us with a PR that I don't really want to merge. Sound good?

**Closed by bhousel** 2017-03-02 21:00 UTC
Labels: considering

**Comment by slhh** [comment] 2017-03-03 01:32
>We can discuss more on this issue how we want to collect tips, but I'm closing it just to make sure somebody doesn't build this feature and surprise us with a PR that I don't really want to merge. Sound good?

Of course an unwanted PR should be prevented, but I would suggest to use labels like "not wanted", or "needs different solution". Closing an issue restricts discussion due to being mixed up with the mess of solved, duplicate, or wrong issues. In addition the issue is hidden because searching for open issues is the default setting.

In many or even most cases the original request isn't the right solution which should be implemented in iD anyway. Therefore, someone preparing a PR should read the comments of the issue. In case the comments and the label are clearly indicating that this is not wanted for a good reason, this should be sufficient.

An invisible (closed) issue might led to an pull request too, because the information that the somewhat useful feature is not wanted for some reason is not visible. And rejecting such an PR would be worse than rejecting a pull request of someone who has ignored the comments.

Btw, issues which have been sufficiently discussed, and where a PR is really wanted should be indicated by labels too. The same applies for issues, where a PR is not wanted because you want to fix it yourself or which have to wait for other changes.

**Comment by bhousel** [comment] 2017-03-03 15:07
> Of course an unwanted PR should be prevented, but I would suggest to use labels like "not wanted", or "needs different solution". Closing an issue restricts discussion due to being mixed up with the mess of solved, duplicate, or wrong issues. In addition the issue is hidden because searching for open issues is the default setting.

Thanks @slhh, this is a good idea.. I have been using labels for wanted features, but have avoided adding "wontfix" style labels for unwanted features because I have always thought they were kind of petty/mean, and also because I really do see closed issues as something that we can always reopen later if the situation changes.  I see how just closing something without labeling it could lead to more confusion.  

Understand also that I really need to close issues because this is a busy project with really just me maintaining it, and a handful of other core contributors who work on whatever interests them.  When I respond to issues I try to be fair and respectful, but it takes a lot of time and so to keep things progressing a little bit each day, I need to close out issues regularly that go stale or don't align with the core design goals of iD.

> Btw, issues which have been sufficiently discussed, and where a PR is really wanted should be indicated by labels too. The same applies for issues, where a PR is not wanted because you want to fix it yourself or which have to wait for other changes.

Yes I do have a "system" with the labels, and it's constantly evolving but I should write down somewhere (CONTRIBUTING.md?) how the issue labels work and maybe some overview of how I approach the issues.. I will do that today 👍

**Comment by slhh** [comment] 2017-03-03 23:04
>Yes I do have a "system" with the labels, and it's constantly evolving but I should write down somewhere (CONTRIBUTING.md?) how the issue labels work and maybe some overview of how I approach the issues.

How about using the wiki of the project? I think this would be more visible for users who aren't contributing code yet. In addition Contributing.md needs to link to it.
