### ISSUE TITLE
feature suggestion: draggable direction for nodes

### ISSUE THREAD

**Issue by j47996** [openstreetmap/iD#9193] opened 2022-07-03 23:36 UTC
### Description

For nodes with a direction= tag, a mouse-access method for setting the value.
Possibly the existing sequence used for rotating a building area could be used
(select object, 'r" ,  mouse-move referred to the centre of the object).

My use case is for entering solar panels, and speed cameras; this is merely to speed up the
operation by avoiding the "guess that's about 195.... nope, 215" sequence.

**Comment by danieldegroot2** [comment] 2022-07-04 14:56
Duplicate of #5530 ( see https://github.com/openstreetmap/iD/issues/5530#issuecomment-1065971502 ).
Make sure to check for existing issues, please.

cc: @tyrasd

**Closed as completed** 2022-07-11 12:13 UTC
Labels: duplicate
