### ISSUE TITLE
Custom Background Settings: allow specifying a maximum zoom level 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8215] opened 2020-11-21 23:24 UTC
These Custom Background Settings are great, except they seem to lack a way to say
- There are no tiles available higher then zoom level Z, so don't bother requesting them from the server. Just locally magnify the current tiles beyond that. (But what if they do add those tiles on next year's aerial survey run? Then we will never eventually enjoy them.)

Or maybe that need not be necessary:

- If the server responds 404, then just magnify the current tiles automatically.

In any case, be sure there is an alternative to just painting the background black!
```
Supported WMS tokens:
{proj}: requested projection (EPSG:3857 only)
{wkid}: same as proj, but without the EPSG (3857 only)
{width}, {height}: requested image dimensions (256 only)
{bbox}: requested bounding box (e.g. minX,minY,maxX,maxY)
Supported TMS tokens:
{zoom} or {z}, {x}, {y}: Z/X/Y tile coordinates
{-y} or {ty}: flipped TMS-style Y coordinates
{switch:a,b,c}: DNS server multiplexing
{u}: quadtile (Bing) scheme
{@2x} or {r}: resolution scale factor
```

**Comment by boothym** [comment] 2021-12-09 10:49
Think this is a duplicate of #5686

**Closed as completed** 2021-12-14 17:15 UTC
