### ISSUE TITLE
When hovering over an object with a field icon, the field icon goes over the border

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9910] opened 2023-09-20 11:51 UTC
Displays scroll bars, indicating icon is too large / box is too small to be displayed by default.
Example: tree node with leaf type set.

It does not seem resolution or zoom dependent.

See also #9070

### How to reproduce the issue?

1. Open the editor with the "Edit" button (or manually with the down arrow menu to the right of it).
![image](https://github.com/openstreetmap/iD/assets/67521919/80b7d662-b473-4306-b13e-960a460cbd4f)
2. Create (or select) an object with a 'sub-type' field which usually has an icon, i.e. a tree with "leaf type" can be "broadleaved".

Let's add a node
![image](https://github.com/openstreetmap/iD/assets/67521919/819aaa20-441f-454f-abc9-f6c0d1e2c715)
...make this node a regular tree by selecting from the presets
![image](https://github.com/openstreetmap/iD/assets/67521919/decf28ab-137e-4003-8834-821c857cc589)
...and then select a sub-type. Here it is for example "leaf type". Let's select "Broadleaved tree".
![image](https://github.com/openstreetmap/iD/assets/67521919/7772abab-775f-4b1b-88ea-33bf31542c44)

I have now specified a sub-type for the object. It looks like this when it is selected.

![image](https://github.com/openstreetmap/iD/assets/67521919/361be459-0f1b-415d-a729-a4814f20d22c)

6. Deselect the object by clicking anywhere on the map. The UI will change to a search bar as usual.
![image](https://github.com/openstreetmap/iD/assets/67521919/0ee125e6-3db6-49a4-bd2f-0d6c313068b9)

8. **Hover over** the object, i.e. a tree node. The UI will change to a preview of the object, as usual.

The "Broadleaved tree" icon is used for the preset "Broadleaved tree (deciduous)" itself at the top, in this case.
It is also present in the "leaf type" field to give users a visual indication of the subtype regardless.
If you look at the field "leaf type" it will have the "broadleaved tree" icon, but there *it is obscured by two sliders*, indicating the icon or the box it is in may not fit inside the UI properly when you hover over it. (*incorrect behaviour*)

![image](https://github.com/openstreetmap/iD/assets/67521919/8db8327e-c95b-4eb9-9023-33dd274f1216)

9. **Select** the object

If we actually select it again, it looks fine. There are no sliders or similar obscuring the icon and the icon itself is fully visible and fits inside the box in the UI. (*expected behaviour*)

![image](https://github.com/openstreetmap/iD/assets/67521919/361be459-0f1b-415d-a729-a4814f20d22c)

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/67521919/4b47e012-cfeb-4551-8f12-2a0e69268956)

(Rapid does not have hover UI.)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.27.1, 2.28.0-dev

### Which browsers are you seeing this problem on?

Chrome, Microsoft Edge

**Comment by RohitChauhan98** [comment] 2023-09-21 12:57
Please write detailed instructions to regenerate the issue... it's not sufficient for new contributors...

**Comment by danieldegroot2** [comment] 2023-09-21 13:43
I have added some instructions, I hope they help. If you have any questions, feel free to post them here.

This is likely a really low-priority issue, as noone ever really looks at the previews. ;-)
Have you looked at [good first issues](https://github.com/openstreetmap/iD/labels/good%20first%20issue)? I assume you are already familiar with this concept where such issues are specifically labeled for new beginners to look at.
It may take some time to get going btw, since OpenStreetMap and related projects rely mostly on volunteers.

**Comment by RohitChauhan98** [comment] 2023-09-21 19:19
I was able to regenerate to the issue... Thank you for helping me out...but when i went to fix the issue in the code base i was not able to find that... I tried several keyword to search but could'nt find... please can you guide me to do so...

**Comment by RohitChauhan98** [comment] 2023-09-22 13:45
I am new to D3.js... I tried to find the issue in the project but was not able find... can you help me out how the project code is structured... sorry to ask but i have spent good amount of time understanding it...

**Comment by nickrsan** [comment] 2023-09-23 06:44
Gonna take a bit of an uneducated guess, since I don't know the codebase, but do know CSS, and say that I suspect it may be located here in the code: https://github.com/openstreetmap/iD/blob/68ff64b01d5a125950474dbf567bc0a9fa3b9edd/css/80_app.css#L4133-L4142

The combination of those two selectors seems like it would add 1px to each side of the box *and* trigger scrollbars on overflow. I don't know that class is active on that element, but seems plausible that it could be the culprit. But I don't know right now where else it's used to suggest what an actual fix looks like and I haven't verified that it's the cause of the issue - if I can come back to this issue I'll see if I can reproduce and inspect the classes.

**Comment by draunger** [comment] 2024-11-06 16:45
hey @1ec5  @RohitChauhan98 @danieldegroot2  is this issued solved ? if yes then close this issue because it makes problem for a beginner like me

**Comment by tyrasd** [comment] 2024-12-03 17:56
fixed with 18de00a7bfd26155cb5fe25789c926a6aff27ec5

**Closed as completed by tyrasd** 2024-12-03 17:56 UTC
