### ISSUE TITLE
phone:mobile=* and similar contact fields shouldn't suggest data

### ISSUE THREAD

**Issue by VictorIE-OSM** [openstreetmap/iD#7821] opened 2020-07-21 19:49 UTC
If I add the key phone:mobile then ID will suggest data for the value. It shouldn't suggest any data, as that data is invariably going to be the contact details for someone else. This is is common to all or nearly all contact fields, e.g. contact:twitter and contact:linkedin, but not contact:email.

Certain contact keys do not suggest data, e.g. website=*, email=*, phone=*, fax=* and this needs to be replicated.

![OSM phone-mobile](https://user-images.githubusercontent.com/68613273/88098703-1b2fc280-cb92-11ea-90c6-c7742202d1d8.png)

**Comment by quincylvania** [comment] 2020-07-22 14:04
See #7485 for discussion about this functionality. You're right that iD shouldn't show suggestions, but the problem is there are hundreds of tags like this and it's unrealistic to manually exclude them all. We could theoretically do this intelligently if iD knew the data type for each tag, but for now I'm closing this as low impact. If you care a lot about it then feel free to open a PR.

**Closed as completed by quincylvania** 2020-07-22 14:04 UTC
Labels: wontfix-low-impact
