### ISSUE TITLE
Boundaries not hidden by default on OSM.org instance

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9877] opened 2023-08-31 07:30 UTC
### URL

https://www.openstreetmap.org/edit#map=19/44.11953/-123.13321

### How to reproduce the issue?

1. If you're signed in, clear your browser cache and sign back in.
2. Click on the url above. The welcome screen should show up:
![image](https://github.com/openstreetmap/iD/assets/85302075/239d3551-6ebe-4577-bd2b-8c0da7387956)
3. Click on 'Edit now'
4. Open the Map Data menu and scroll down to 'Map Features'. Every category, including 'Boundaries' is checked:
![image](https://github.com/openstreetmap/iD/assets/85302075/b4fa5a0a-3a4a-41f7-b967-1b6d5e781bf0)

When opening the same area on the [release mirror](https://ideditor-release.netlify.app/#map=19/44.11953/-123.13321), boundaries are hidden:
![image](https://github.com/openstreetmap/iD/assets/85302075/6cd297b0-cc24-4549-9cea-91920785afca)

### Screenshot(s) or anything else?

It looks like boundaries have been hidden by default since #4292

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.1

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by 1ec5** [comment] 2023-08-31 09:38
This is a duplicate of #8454, and probably only solvable upstream in openstreetmap/openstreetmap-website: https://github.com/openstreetmap/iD/issues/8454#issuecomment-1295765626.

> If you're signed in, clear your browser cache and sign back in.

iD remembers your Map Features settings across sessions using Local Storage. You probably have the `disabled-features` set to the empty string. Clearing your cache might not clear this entry, though in this case it doesn’t matter because openstreetmap-website is effectively overriding it anyways.

**Comment by 1ec5** [comment] 2023-08-31 09:38
Duplicate of #8454

**Closed as not planned by 1ec5** 2023-08-31 09:38 UTC
