### ISSUE TITLE
Allowing OSM Notes to be visible as a switchable default

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#8919] opened 2022-01-27 06:45 UTC
### Description

Currently, OSM Notes are only visible in iD by going into the Map Data tab & turning them on. If you then close that editing page, & open a new one, you have to turn Notes on again. This is very annoying when you are working through the list of outstanding Notes, & trying to resolve them!

Could this be enabled as a feature that can be turned on or off, but which then appears by default until you change the setting again?

### Screenshots

![image](https://user-images.githubusercontent.com/35707521/151305984-ab441460-4586-4118-95c6-d8bb0a0f187a.png)

**Comment by tordans** [comment] 2022-01-29 06:10
This would be a great candidate to add to https://github.com/openstreetmap/iD/blob/develop/API.md as an URL Param as well. 

---


And likely something to tag as "good first issue", Martin.

**Comment by tordans** [comment] 2022-01-29 11:43
For the iD Editor on OSM.org, we could also recognize on the Cookie `_osm_location=13.4408|52.4738|16|MN` where the `N` seems to save the on/off-state of the notes-overlay.

<img width="499" alt="Bildschirmfoto 2022-01-29 um 12 39 34" src="https://user-images.githubusercontent.com/111561/151659638-01f32aa9-1774-49cb-820b-39576c9be8f2.png">
<img width="483" alt="Bildschirmfoto 2022-01-29 um 12 39 20" src="https://user-images.githubusercontent.com/111561/151659639-526fc6d0-47fd-4f95-9287-add7a8f67f01.png">

This would likely need to happen as part of the iframe-initializer on osm.org, see also https://github.com/openstreetmap/openstreetmap-website/issues/3031.

**Comment by k-yle** [comment] 2022-02-01 07:13
#8042 would fix this, but that PR has been open for over a year...

**Comment by tordans** [comment] 2024-09-15 05:02
I will close this as a duplicate of https://github.com/openstreetmap/iD/issues/9312

The notes feature was improved a bit recently for the use case osmorg > editor, see https://github.com/openstreetmap/iD/pull/8042#issuecomment-2351369155

**Closed as completed by tordans** 2024-09-15 05:02 UTC
