### ISSUE TITLE
Extrating a bus stop (highway=bus_stop) node doesn't keep relation

### ISSUE THREAD

**Issue by wolfy1339** [openstreetmap/iD#10234] opened 2024-05-07 22:57 UTC
### URL

https://www.openstreetmap.org/edit?node=304828058#map=19/46.81263/-71.21529

### How to reproduce the issue?

1. Select a bus stop node that is part of a road
2. Extract the bus stop node
3. Notice that the extracted node wasn't retained in the relation

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29

### Which browsers are you seeing this problem on?

Firefox

**Comment by Dimitar5555** [comment] 2024-05-08 09:25
Duplicate of #8929

**Closed as completed** 2024-05-08 10:46 UTC
