### ISSUE TITLE
Deselecting a key with no value in the tag editor removes the key

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#10145] opened 2024-03-03 14:32 UTC
### Description

Hello everyone, at first I thought this was some sort of validation improvement, but didn't see it on the changelogs.

Steps to reproduce:

1. Open the tag editor pane (the UI one, issue is not present in the plain text editor)
2. Press the + Add button to add a new line
3. Input a new key, either using the dropdown autocomplete or manually
4. Without inputting the tag value, switch to another line in the editor or click anywhere else out of it

Expected behaviour (how it was previously):
The key with no tag value set is retained for the editing session. Discarded during upload if no value is added.

Current behaviour:
Key line with no value is cleared as soon as deselected. In the recording I am using shift/tab keys to switch between fields.

Is this by design?

### Screenshots

![gif](https://github.com/openstreetmap/iD/assets/7071423/77fd7787-45f5-4b28-8fd6-424b14ca5d73)

**Comment by danieldegroot2** [comment] 2024-03-03 17:34
Workaround: Use the raw tag editor

![image](https://github.com/openstreetmap/iD/assets/67521919/5474c12e-5892-4bef-8e97-08008f8207e5)

**Comment by tohaklim** [comment] 2024-03-03 17:56
Yes, but I do like the autofill suggestions

**Comment by tyrasd** [comment] 2024-03-14 19:22
This is in principle by design: As empty-valued tags would be deleted silently anyway, removing them immediately from the tag list makes it more clear to the user that these tags will be discarded.

> The key with no tag value set is retained for the editing session.

Do you have a use case that would benefit from this?

**Comment by tohaklim** [comment] 2024-03-14 19:37
For example I start typing in a tag value pair, but switch to a wiki tab to check a definition, or simply shift focus from the text field. The whole line is removed, and has to be retyped.
Looks like #10151 might actually fix this

**Comment by tyrasd** [comment] 2024-03-15 00:06
Ah, I see. Yes, that's a good argument in favor of restoring the previous behavior. :+1:

**Comment by tyrasd** [comment] 2024-03-15 00:14
should be fixed now with #10151

**Closed as completed by tyrasd** 2024-03-15 00:14 UTC
Labels: usability

**Comment by maro-21** [comment] 2024-04-24 19:57
Thanks, it helps.
