### ISSUE TITLE
Imagery offset not remembered

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5046] opened 2018-05-21 13:31 UTC
A feature request.

iD is good at remembering things across browser sessions.  It remembers which background image I was using.  It even remembers if I was in the middle of editing and didn't save (very nice if you get a power cut).

Yesterday I switched to Esri because Bing wasn't clear enough in one particular area.  Of course, Esri always requires me to adjust the imagery offset, since most of the locality had been mapped with Bing and there are quite large offsets (-11.45, 4.26) which vary somewhat depending upon locality.  Today, iD remembered where I was on the map yesterday, as it always does.  It remembered which background I was using, which it always does.  What it didn't do is remember the offset I used, so I had to tediously adjust it again.

It would be really nice if iD remembered the imagery offset (on a per-background basis, of course, not a global offset applied to all backgrounds).  Even though the Bing/Esri offset is somewhat variable, remembering the value I used when I last edited with Esri is going to be closer to what I need the next time I use Esri than 0,0 is.

**Comment by bhousel** [comment] 2018-05-25 04:35
Good suggestion, this is a duplicate of #2947 and I agree we should have it..

**Closed by bhousel** 2018-05-25 04:35 UTC
