### ISSUE TITLE
Prerelease mirror returning 404

### ISSUE THREAD

**Issue by ajithranka** [openstreetmap/iD#3937] opened 2017-03-30 09:54 UTC
We have been using https://openstreetmap.us/iD/release to embed iD in [to-fix](osmlab.github.io/to-fix). Recently the link is returning 404s. Is this a temporary glitch?

cc: @bhousel @geohacker

**Comment by althio** [comment] 2017-03-30 09:58
duplicate of https://github.com/openstreetmap/iD/issues/3912

**Comment by bhousel** [comment] 2017-04-05 14:13
yeah I'll update #3912 to make it clear that we need both `release` and `master` mirrors to be stable

**Closed by bhousel** 2017-04-05 14:13 UTC
