### ISSUE TITLE
Raw HTML escapes seen on heavy load message

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6618] opened 2019-07-04 08:07 UTC
Raw HTML shown to the user:
```
Errors occurred while trying to save
<h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
```
I.e., #5621 is still an issue.

**Comment by jidanni** [comment] 2019-07-04 08:08
I didn't even read the message. I just am remarking about the raw HTML.

**Comment by quincylvania** [comment] 2019-07-05 13:04
Duplicate of #3366.

**Closed by quincylvania** 2019-07-05 13:04 UTC
