### ISSUE TITLE
Osmose issues list for selected feature

### ISSUE THREAD

**Issue by nlehuby** [openstreetmap/iD#5893] opened 2019-02-16 16:40 UTC
As a follow up for #5830, it could be great to add Osmose issues list for the selected feature in the editor sidebar.

You can get the list of the Osmose issues for a feature with this endpoint:
http://osmose.openstreetmap.fr/en/api/0.3beta/issues?osm_type=relation&osm_id=2545707&full=true

**Comment by tordans** [comment] 2019-02-17 07:19
This is a duplicate of https://github.com/openstreetmap/iD/issues/5682, right @nlehuby?

**Comment by nlehuby** [comment] 2019-02-17 08:01
Not exactly:
* #5682 is about creating a new layer with Osmose issues around
* this one is about adding Osmose issues about a feature inside the sidebar of the selected feature

**Comment by bhousel** [comment] 2019-02-17 12:42
Duplicate

**Closed by bhousel** 2019-02-17 12:42 UTC
