### ISSUE TITLE
Dark mode support?

### ISSUE THREAD

**Issue by Vectorial1024** [openstreetmap/iD#10542] opened 2024-11-15 02:20 UTC
### Description

A very recent update from the OSM website team itself: https://en.osm.town/@osm_tech/113482687301656785

> 🚀 https://www.openstreetmap.org/ is now also available in [#DarkMode](https://en.osm.town/tags/DarkMode) 🕶️ 🔦 🤓  [#Black](https://en.osm.town/tags/Black) [#OpenStreetMap](https://en.osm.town/tags/OpenStreetMap) [#UI](https://en.osm.town/tags/UI)

Then, obviously, the next question to ask is whether the iD editor would get a dark mode update in the future.

### Screenshots

As of now, there seems to have no dark mode options for the iD editor, which results in UI inconsistencies, like this example (ignore the green line):

![image](https://github.com/user-attachments/assets/29f506b0-f2e1-4532-af95-0c4e7b6b9685)

**Comment by 1ec5** [comment] 2024-11-15 05:21
Duplicate of #8214

**Closed as not planned by 1ec5** 2024-11-15 05:21 UTC
