### ISSUE TITLE
Error when selecting a line or area

### ISSUE THREAD

**Issue by Pablotis** [openstreetmap/iD#2685] opened 2015-06-09 19:06 UTC
I cannot select any area or line for editing properties on Chrome 44.0.2403.30 beta-m (64-bit) Windows 8.1,  can just select points, it works ok on Firefox, it doesn't have any javascript output on the log.

**Comment by ernop** [comment] 2015-06-10 03:37
I've been getting this consistently over the last week in Chrome 43.0.2357.81 m but no problem in Firefox, on the iD version up on openstreetmap.org.

**Comment by pnorman** [comment] 2015-06-21 06:10
probably #2151

**Comment by jfirebaugh** [comment] 2016-01-24 22:21
Yes, closing as duplicate of #2151.

**Closed by jfirebaugh** 2016-01-24 22:21 UTC
