### ISSUE TITLE
raw raw editor: idea of fully support to copy just keys

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7297] opened 2020-01-28 14:07 UTC
Thanks again for the great raw raw-editor (tag-copy) function.

Recently i tried to copy just some shown keys (instead of often used well working full tag copies actions). The copy function seems working, but the transformation of the key information from the raw-raw-editor view to the raw-editor view is currently not available see movie:

![raw-editor copy key support](https://user-images.githubusercontent.com/47290585/73270571-3ae7be80-41df-11ea-902b-7b9f41740abc.gif)

**Comment by bhousel** [comment] 2020-01-28 14:17
oh yeah.. thanks for flagging this.
It probably just doesn't work with empty values.
(the parsing step expects a bunch of `k=v\n` pairs)

**Comment by DujaOSM** [comment] 2020-01-29 08:36
The "raw raw" editor erases empty tags as soon as the control loses keyboard focus. Similar thing happens when you e.g. select a new language for an object's name but do not populate the value immediately -- the control and the associated tag are lost soon after.

I've always assumed it's a feature, not a bug, although I also find it slightly annoying.

**Comment by sun-geo** [comment] 2020-01-29 22:10
> oh yeah.. thanks for flagging this.

You are welcome. I think it's nice-to-have (not urgent low priority)

**Comment by cz2h** [comment] 2020-02-16 19:10
Hi, I'd like to contribute to this feature and I would like to double check if I understand this feature properly.

We just simply want to display tags with emtpy contents right ? And there is no other specification.

**Comment by quincylvania** [comment] 2020-03-13 21:17
This was fixed in #7363 by @zengchu2 🎉

**Closed by quincylvania** 2020-03-13 21:17 UTC
Labels: bug
