### ISSUE TITLE
 Universal Language Selector for iD

### ISSUE THREAD

**Issue by yogiks** [openstreetmap/iD#2888] opened 2015-12-27 18:10 UTC
It would be helpful for users if there's an option to use/enable [Universal Language Selector](https://github.com/wikimedia/jquery.uls) in iD which can make it easier for adding multilingual names with in-browser input method rather than depending on system input method.

**Comment by bhousel** [comment] 2015-12-29 19:18
I don't think bringing in a jQuery dependency makes sense for iD, but I'm open to improving the input method for multilingual names.  We might be able to build something with D3 that does the same thing.

Can you describe more what the issue is? 

This is what it looks like currently:

<img width="369" alt="screenshot 2015-12-29 14 17 13" src="https://cloud.githubusercontent.com/assets/38784/12040440/001981f2-ae37-11e5-8674-00360a9da211.png">

**Comment by bhousel** [comment] 2015-12-29 19:20
Put another way, how is this different from #2882?  (which I just saw)

**Comment by yogiks** [comment] 2015-12-30 01:08
I was pointing at having multilingual input tool within iD which can help users switch between multiple languages easily while typing like in below snap-shot:

![github](https://cloud.githubusercontent.com/assets/6291913/12044728/c0f3b26e-aebc-11e5-948a-3378083cbb61.png)

#2882 is also useful where the default language for translating existing name would be selected from OSM-user preferences instead of choosing from long dropdown as @planemad pointed out. But the issue of input-method for typing multiple languages is slightly different.

**Comment by jfirebaugh** [comment] 2016-02-05 04:16
Isn't configuration of input method the job of the browser or OS? It doesn't make sense for every website to implement its own UI for this.

**Comment by planemad** [comment] 2016-02-05 06:24
@jfirebaugh @bhousel 

The reason WMF developed this tool was to support language tools in machines like XP which is still the most popular OS in internet cafes at least in India. 

While the tools looks like an ugly fit, it works great and has become a very important tool to increase contributions to Asian language Wikimedia projects. There is no other language tool/OS which has [this range of coverage for languages and input methods](https://github.com/wikimedia/jquery.ime/tree/master/rules).

@yogiks just to be clear, you are talking about the input method editor https://github.com/wikimedia/jquery.ime and not jquey.uls right?

**Comment by yogiks** [comment] 2016-03-09 13:36
Apologies for the delay in responding!

@jfirebaugh I agree that this shouldn't be there for every website. But this can help the users of multilingual project like OpenStreetMap where users usually are interested to see their language names on the map whenever they contribute to it. And this can also be one of the workaround for #3023 as currently iD expects the language name to be added in its own script(autonym) for auto-completion.

@planemad yes, I meant the input method editor.

**Comment by bhousel** [comment] 2016-03-09 15:24
Sorry, I'm with @jfirebaugh.. This is out of scope for iD..

**Closed by bhousel** 2016-03-09 15:24 UTC
Labels: enhancement, localization

**Comment by yogiks** [comment] 2016-03-10 05:31
That's okay, thank you!
