### ISSUE TITLE
You have made too many edits to back up warning

### ISSUE THREAD

**Issue by martinoscag** [openstreetmap/iD#8946] opened 2022-02-03 19:09 UTC
### How to reproduce the issue?

1. Go on a editing session
2. Do as many edits as needed to receive the warning "You have made too many edits to back up. Consider saving your changes now."
3. Now continue, at every new change a repeated line of the warning will be added to the red warning banner below.
4. You have made too many edits to back up. Consider saving your changes now. You have made too many edits to back up. Consider saving your changes now. You have made too many edits to back up. Consider saving your changes now. You have made too many edits to back up. Consider saving your changes now. You have made too many edits to back up. Consider saving your changes now.

### Screenshot(s) or anything else?

I don't know if this behavior is intended, but it's very annoying anyway.
In the case it was intented consider this a very bad feedback for this new feature.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment] 2022-02-03 19:49
Duplicate of #8930.

**Closed as completed by 1ec5** 2022-02-03 19:49 UTC
Labels: duplicate
