### ISSUE TITLE
Name autocomplete should take into account the current tags

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5564] opened 2018-12-06 16:41 UTC
Drew a line, clicked on the river preset and typed in the first three letters - then the autocomplete gives me three suggestions of shops names (and even fills in the field with the first one).

Expected behaviour should be to take into account the tags already on the way, and only suggest names of other rivers. Although I'm not sure if that's even something which is I'd find useful as it's not like shops where you have lots of things with the same name.  

Same issue with shops - no point in suggesting a clothing store name when you've added a gift shop like in #5558 

![cjksdajk](https://user-images.githubusercontent.com/16965772/49597775-11355d80-f975-11e8-974c-a2f395b173b9.jpg)

**Comment by bhousel** [comment] 2018-12-06 16:58
Hmm ok, I will check this.  It should not suggest you anything when you use the river preset.

It is useful for other presets like shops though, because people often start out using the wrong tags, so it can suggest them the right ones to go with the feature.  

For example, if you add an `amenity=restaurant` and start typing `McD` in the name, you should still get "McDonald's - Fast Food" suggested to you, and should get the `amenity=restaurant` tag swapped out for `amenity=fast_food`.  (But this shouldn't happen on the River preset because there are not brands for rivers).

**Comment by bhousel** [comment] 2018-12-08 04:58
@boothym I'm having trouble reproducing the issue, but I've made a bunch of changes to the brand suggestion dropdown, and I'm not sure whether this might be fixed now.

Can you test in http://preview.ideditor.com/master/ and see if you still see this issue?
If so, can you let me know your browser and OS.. If it's still buggy, can you share which river you are editing?

**Comment by boothym** [comment] 2018-12-09 14:57
I can see why you'd do it for shops, though my only suggestion would be to consider whether to actually fill the name field - maybe just provide a dropdown of options instead? 

Tried again to add rivers on the OSM website in a few locations but I can't recreate the issue - it doesn't suggest any name at all. So it looks to be sorted (though it's the same iD version, 2.12.1). :blush:

**Comment by bhousel** [comment] 2018-12-09 15:05
> I can see why you'd do it for shops, though my only suggestion would be to consider whether to actually fill the name field - maybe just provide a dropdown of options instead?

Great - that's what the dropdown does now, after #5558  👍  
The dropdown is shown but without autocomplete, so nothing gets filled unless the user actually clicks on an option or uses the arrow keys to navigate to one.

I also think #5573 *might* have fixed the issue with having suggestions show up on rivers, though I'm not completely sure.  I'm closing for now, but will reopen if the issue still occurs after the next patch release.

**Closed by bhousel** 2018-12-09 15:05 UTC
Labels: bug, waitfor-info
