### ISSUE TITLE
Remember last selected layer

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3782] opened 2017-01-20 20:57 UTC
It whould be nice if iD could remember the last selected layer.

**Comment by manfredbrandl** [comment] 2017-01-21 10:10
@yaugenka Can you please describe where exactly the last selected layer should be remembered?

**Comment by yaugenka** [comment] 2017-01-21 16:58
![layers](https://cloud.githubusercontent.com/assets/14937001/22176110/d05c20c2-e013-11e6-96bf-d1c44df586e3.png)

**Comment by bhousel** [comment] 2017-01-21 19:21
Thanks this looks like a duplicate of #1756

**Closed by bhousel** 2017-01-21 19:21 UTC
