### ISSUE TITLE
Allow download of all members of relation

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#9486] opened 2023-02-03 23:03 UTC
### Description

I don't know if this was already asked here, but I would like to have an option to download all members of a relation when selecting a relation.
For example, if I select a piece of a highway and choose one relation that it is member of, it would be very useful to press "Z" and have an option to download all its members, so that I can go to a piece of that relation easily, without haveing to download one by one to try and guess which is it. JOSM as this and it's most useful.

**Comment by sekerob** [comment] 2023-02-16 14:15
Asked before in a different way, like JOSM has a button in the relations screen to download all members not yet pulled in. It sure would help to ensure that the MP being saved with ID is current. 

Case in point, was today correcting and editing in a large forest relation with JOSM, added few scree zones and tagged them as inner to the relation, the member counter went up by 4. Saved the set. Not a minute later an ID mapper working east on same saved the forest MP, loosing all the inner additions and corrects I did to include leaving an outline tagless that was mapped around multiple inner areas that shared one side. He incredulously noted. "Should the scree not be inner to the relation?". Well sure, the scree was rendering incorrectly with the forest tree symbols overlaying.

My french got a refresher.

**Comment by 1ec5** [comment] 2023-04-30 05:04
Duplicate of #5420, which also includes some ideas for mitigating any performance hit from downloading all the members.

**Closed as not planned by 1ec5** 2023-04-30 05:04 UTC
