### ISSUE TITLE
Don't allow adding the same member to a relation if it is already present in it

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9311] opened 2022-09-28 22:50 UTC
iD allows us to add a member to a relation, as many times as we please!

Please just only allow unique members.

What good does having the same member reoccur twice in a relation?

**Comment by jidanni** [comment] 2022-09-29 01:01
Oops, there are plenty of routes we one might legitimately go over the same place twice. 

However it's still  possible in iD to just to keep on clicking on something same place five times in a row. That wouldn't make sense.

**Comment by 1ec5** [comment] 2022-09-29 21:12
Right, this can legitimately happen for a route that doubles back on itself. Offhand, I can’t think of another good reason for a member to appear twice, though there is a long tail of exotic relation types out there that we should continue to support minimally.

The PTv2 scheme and [route directions](https://wiki.openstreetmap.org/wiki/Route_directions) require creating multiple relations for the same route, which have similar labels in iD. To avoid confusion, when you choose a relation to add the current feature to, the list of available relations could sort already added relations to the end of the list, or the label could be grayed out or italicized to indicate that there’s something special about it.

A validator warning for unexpected duplicate memberships would also be valuable for non-route relations.

**Comment by DujaOSM** [comment] 2022-10-06 14:39
Related: #8167

**Comment by danieldegroot2** [comment] 2022-10-24 10:36
This issue is a duplicate of #7648.

( cc: @tyrasd )

**Comment by jleedev** [comment] 2022-10-24 10:48
This is how `restriction=no_u_turn` works.

**Comment by 1ec5** [comment] 2024-10-15 19:56
We should visually distinguish any existing relation membership without preventing the user from adding it: #10501.

**Closed as not planned by 1ec5** 2024-10-15 19:56 UTC
