### ISSUE TITLE
shop=chemist preset should not be called drugstore in en-US

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#3213] opened 2016-07-02 06:31 UTC
Although it can be argued that a “chemist’s shop” in British English may contain a pharmacy counter and is thus equivalent to the U.S. “drugstore”, the OSM Wiki is clear about [`shop=chemist`](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dchemist) being reserved for health products shops that lack a pharmacy counter:

> For a shop that dispenses prescription drugs – that is, a pharmacy or a drugstore in American English – see `amenity=pharmacy`. For British English speakers, it is important to recognise that chemist and pharmacy are not synonymns on OSM.

Meanwhile, [`amenity=pharmacy`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpharmacy) (emphasis mine):

> Stores that sell other items typically found in pharmacies such as personal care items, but that **do not sell regulated medications**, should be not be tagged as `amenity=pharmacy`, but instead perhaps as `shop=chemist`.

The distinction between `shop=chemist` and `amenity=pharmacy` is not whether it’s housed in a separate building but rather whether it can fill prescriptions or sell prescription drugs.

https://github.com/osmlab/name-suggestion-index/issues/30#issuecomment-228798011 reasoned that:

> We should instead encourage `amenity=pharmacy` to be tagged as a point node within drug stores or whatever other business.

As part of the proposal in that comment, #3201 changed the `shop=chemist` preset from “Chemist” to “Drugstore”, and the OSM Wiki would be edited to match.

A discussion on a relatively obscure GitHub repo followed by an OSM Wiki edit is not the most effective way to change entrenched OSM tagging practices. For one thing, iD is not the only editor; all the other editors have `amenity=pharmacy` presets and now contradict iD. As much as I personally loathe doing so, if you think the established usage of such a common tag should change, you should start a discussion on the tagging@ mailing list or a tagging proposal on the OSM Wiki.

/cc @bhousel @math1985 @pmailkeey

**Comment by pmailkeey** [comment] 2016-07-02 12:04
Pharmacy (="Dispensary"): a counter where prescription drugs are dispensed.
Chemist (?=Drug store): A retail shop shop selling beauty/health/hygiene etc. chemicals, associated products and contains a pharmacy.
A building tagged as a pharmacy does not sell toothpaste, soap or other chemicals and is most likely to be found within hospital grounds or a doctors' premises.

**Comment by bhousel** [comment] 2016-07-02 12:36
@1ec5 I haven't really changed anything yet, only the preset name.

Do you agree that:
1. We can't call it "Chemist"
2. the closest translation of UK "Chemist" in US is "Drugstore"
?

**Comment by pmailkeey** [comment] 2016-07-02 13:00
Do all drug stores have a pharmacy ?
Can iD not display 'chemist' in UK and 'drugstore' in US? (as it appears to have differences for other objects - like 'tracks' and 'community gardens' ?
I'm totally happy with chemist = drug store but even though "drugstore" appears acceptable in UK it doesn't seem to be correct. cf 'conveniencestore' - which clearly doesn't seem right !
Concern: is 'drugstore' a registered trademark of drugstore.com ?

**Comment by bhousel** [comment] 2016-07-02 13:04
> Do all drug stores have a pharmacy ?

In US possibly, but not world wide

> Can iD not display 'chemist' in UK and 'drugstore' in US?

Yes that's the new behavior introduced in e664c35 that @1ec5 thinks will cause confusion.

> Concern: is 'drugstore' a registered trademark of drugstore.com ?

It's ok, words in common use we can use it this way.

**Comment by pmailkeey** [comment] 2016-07-02 13:08
I'm not sure how it'll cause confusion. The Wiki will need a page for both - ideally one simply being a redirect to the other.

**Comment by 1ec5** [comment] 2016-07-04 09:20
> the closest translation of UK "Chemist" in US is "Drugstore"

It may be the closest, but it’s still problematic. Now an American iD user who wants to tag a Rite Aid may search for “drugstore” and end up tagging the building with `shop=chemist`; it’s unlikely that they’ll also tag the pharmacy counter separately, having already tagged a “drugstore”. An American JOSM user could see that the building is now tagged “Shops/Other/Chemist” and change it to “Facilities/Health/Pharmacy”, because the meaning of “chemist” in OSM has always referred to non-dispensing shops – a stricter definition than the one commonly used in Britain – and they had no reason to believe that iD would unilaterally change the definition. A renderer that wanted to mark only dispensing shops with a caduceus used to be able to just look for `amenity=pharmacy`, but now it also has to look for `shop=chemist` (and only those tagged using iD). Meanwhile, another American iD user may want to tag the CVS across from the Rite Aid; searching for “pharmacy”, they’ll end up tagging the building with `amenity=pharmacy`.

[<img width="330" height="196" alt="CVS pharmacy" src="https://github.com/user-attachments/assets/6ce0bd0d-74c1-46c3-9a23-c22e49a32ab1" />](https://commons.wikimedia.org/wiki/File:CVS_Pharmacy_Modesto,_California.jpg)

The confusion is that the proposal in https://github.com/osmlab/name-suggestion-index/issues/30#issuecomment-228798011 affects the interpretation of 170,000 `amenity=pharmacy`s and 17,000 `shop=chemist`s and creates ambiguity about newly tagged objects. OSM tagging is awash with idiosyncrasies, and I share your enthusiasm about sorting them out, but there are established ways of doing so that make sure everyone’s on the same page.

**Comment by pmailkeey** [comment] 2016-07-04 18:34
Noting your image, other valid tags would be drive thru and perhaps convenience store. A pharmacy within a chemist is potentially a different entity - just because the chemist's shop is open does not necessarily mean the pharmacy is. In the UK we have the same issue with Post Offices - even buildings run as a Post Office may not offer Post Office services all the time the shop is open. While in the UK assuming all chemists have a pharmacy is a good idea, I don't think OSM should accept that and hence encourage pharmacy node tagging within chemists.
Similarly, again prompted by the image, many chemists offered photo processing - so that should be a separate thing. Can an object be tagged shop=chemist and amenity=pharmacy ? - yes - but then what does the map show ? Searching for pharmacies will no doubt find them but the map should also show this.
But then, OSM seems a very very good idea but is a complete nightmare!

**Comment by math1985** [comment] 2016-07-04 20:40
I had a closer look at this now. I'm afraid the issue is not that easy to solve, and whatever we choose, there are disadvantages. Some points:

- According to the wiki, shops that sell prescription drugs should not be tagged as shop=chemist
- In both the UK and the US, shops that sell both beauty and medicines (such as Boots in the UK and Walgreens and CVS in the US are typically tagged as amenity=pharmacy, not shop=chemist
- Therefore, a scheme that suggests shops like Walgreens and CVS should be tagged as shop=chemist goes both against the wiki and current practice
- I think therefore a scheme in which Walgreens and CVS should be tagged as shop=chemist should be discussed with the (US?) community first

**Comment by 1ec5** [comment] 2016-07-04 20:56
@pmailkeey, you’re right about full-service stores, like any supermarket, having different departments with different hours and so forth – no argument there. If someone wants to micromap a supermarket with its post office counter, pharmacy counter, florist, and ATM, there’s never been anything stopping them from adding those amenities as POIs within the supermarket building.  The same is true about stores such as CVS. Most OSM renderers and search engines can handle this sort of tagging.

My argument for reverting #3201, pending wider discussion, boils down to two things:

1. In American English, the words “pharmacy” and “drugstore” each describe a store that _necessarily_ contains a prescription-filling pharmacy counter, so there’s little incentive for a mapper to separately map the pharmacy counter. The end result is that, iD’s UI aside, newly mapped areas in the U.S. will lack places to fill prescriptions, because no other OSM software recognizes `shop=chemist` as a prescription-filling establishment the way iD currently does.
1. It’s well within iD’s right to formalize a popular tagging scheme by offering presets for it. Other OSM software, such as [the Standard renderer](https://github.com/gravitystorm/openstreetmap-carto), do the same on a regular basis. It’s quite another matter for iD to unilaterally influence the way its users interpret existing POIs and tag new POIs, without any trace of the change being reflected in tags. I’m confident that any change made to the wiki solely on the basis of iD’s UI, without broader discussion, would be reverted anyhow.

In the past, the community has resolved confusing situations like `amenity=pharmacy` versus `shop=chemist` by adopting an altogether new, unambiguous set of tags. But that can’t happen until the discussion moves to the mailing lists.

**Comment by 1ec5** [comment] 2016-07-04 21:34
Incidentally, CVS still operates a couple stores that lack pharmacies in New England. The [signage](https://www.mapillary.com/map/im/u8gjN3x_PhSXCoybYlzo6Q/photo) on these stores conspicuously lacks the word “pharmacy”. The only [example](http://www.openstreetmap.org/node/1957901891) I’ve found on OSM is currently tagged `amenity=pharmacy` `dispensing=no` `shop=convenience`. Because (by law) they’d sell cold medicine behind the counter but not fill prescriptions, these tags would technically be consistent with [the documentation](http://wiki.openstreetmap.org/wiki/Key:dispensing). However, the Standard style renders this POI with a pill bottle based on `amenity=pharmacy`, which can be misleading.

This CVS store would be a reasonable candidate for `shop=chemist` as it’s currently defined on the wiki, except that no American would ever find the preset for it whether it’s labeled “chemist” or “drugstore”. Personally, if I didn’t know about `shop=chemist`, I’d go with just `shop=convenience` because it happens to sell the same things as a gas station convenience store, plus photo processing, minus the motor oil.

**Comment by 1ec5** [comment] 2016-07-05 14:54
> Why not when they are a chemist ?

Maybe they’re “chemists” in standard British English usage of that term, but that doesn’t necessarily make them `shop=chemist`. Unfortunately, tag names often differ from conventional English usage, a fact made abundantly clear to any American mapper. 😉

> Well I've been retagging them.
> …
> So if the wiki says not to tag as chemist, that leaves tagging as 'drug store' !

What you’re advocating for (and apparently doing) is removing meaning from POIs, such that to a data consumer, an establishment that once filled prescriptions no longer does. Hopefully you’re careful to map the pharmacy counter when you do so, making sure to place the `amenity=pharmacy` POI in the correct corner of the store.

Let’s suppose, for the sake of argument, that the British term for a supermarket were “department store”. (The analogy is apt: some department store chains like Walmart contain all the departments of a supermarket, but a department store does not a supermarket make.) Would it make sense, then, to relabel the `shop=department_store` preset to “Supermarket” for just American iD users and retag American supermarkets like Kroger and Albertson’s as `shop=department_store` on that basis, all without consulting the talk-us or tagging list?

**Comment by bhousel** [comment] 2016-07-05 14:56
What has been done so far:
* `shop=chemist` now says "Drugstore" in `en-US`, and still says "Chemist" in `en-GB`.

That all.

Saying that I "unilaterally influence the way its users interpret and use a well established tag, without any way for the rest of the OSM ecosystem to detect that change" is not really fair. 

Closing here.  Please discuss on @tagging or @talk-us if you think that any discussion there might lead to US-UK tag harmonization, which I agree is a worthy goal.  We can make a friendly wager offline about whether or not this will result in any meaningful progress.

---

*(opinion follows)*

Yes I agree with @pmailkeey.
Some discussion on [osm wiki from last year](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dpharmacy#Superstore_pharmacies) suggests the same.

* `amenity=pharmacy` should be for a counter where a pharmacist dispenses prescriptions or other controlled medicines.
* `shop=chemist` should be for a drug store
* `dispensing` should go away, as it reflects only the laws in the jurisdiction where the business operates.  When the laws change, are we going to retag all of these features?  Of course not.

Pharmacy counters can exist within drugstores, groceries, hospitals, warehouse clubs, or be standalone.  They have separate phone numbers and operating hours, and sometimes separate building entrance.  We should not be using this tag to mean "maybe a counter, or maybe in the US a store with a counter, or in rare cases in the US a store without a counter".

**Closed by bhousel** 2016-07-05 14:56 UTC

**Comment by pmailkeey** [comment] 2016-07-05 15:02
1ec5 said

My argument for reverting #3201, pending wider discussion, boils down to two things:

In American English, the words “pharmacy” and “drugstore” each describe a store that necessarily contains a prescription-filling pharmacy counter, so there’s little incentive for a mapper to separately map the pharmacy counter. The end result is that, iD’s UI aside, newly mapped areas where people say “drugstore” instead of “pharmacy” will lack places to fill prescriptions, because no other OSM software recognizes shop=chemist as a prescription-filling establishment the way iD currently does.

But my argument against that is that it's a step backwards. We should aim to move forward and in this case that's getting the rest of OSM to recognise a pharmacy exists in both chemists and drug stores. - OR we go along with tagging chemists as drug stores - as you say they always have a pharmacy [[unless tagged pharmacy=no]]

If we go along with iD making UK Chemist = US drugstore then there's no problem since you say drug stores contain a pharmacy.

As for your second point about discussions with e-mail lists - I read in the wiki that we are encouraged to make edits - and basically in the UK tagging a chemist as a chemist is an obvious correction not needing discussion.

One of our other chemists' chains is "Rowlands Pharmacy", and another "Lloyds Pharmacy" - so tagging as a chemist still shows a pharmacy exists. However, there'll be a clear misunderstanding with such a name that these chemists are in fact chemists and not mere pharmacies ! However, I've come across this same idiosyncratic situation elsewhere - so chemists/pharmacy is not on its own in this confusing respect.

Re 'chemist' v 'convenience store', 'chemist' is a speciality like greengrocer (fruit & veg). A convenience store may well sell fruit & veg but it's not 100% guaranteed. Similarly, I wouldn't expect to get Potassium Permanganate from a convenience store but would from a chemist.

Tagging CVS as a convenience store sounds like an error. As a drugstore with pharmacy=no I think would be correct. 'Dispensing' I guess should be assumed with all pharmacies - so whether that particular CVS has a pharmacy or not, I don't know. This is getting more complex....

If the shop doesn't give advice re the products it sells, it won't be a chemist. Do drug stores give advice about the compounds they sell?

I think we're all going to have to tread carefully with all these names !

**Comment by 1ec5** [comment] 2016-07-05 15:13
@bhousel, upon rereading your change, I see that someone searching for “drugs” will see “Drugstore” followed by “Pharmacy”. That’s less problematic than what I thought would happen, which is that the user would see only “Drugstore”. It’s still suboptimal, though: the only way to distinguish between these two synonyms is the shopping cart versus the pill bottle. Moreover, there’s still no prompt to map the pharmacy counter, prescriptions being the most important amenity offered in a drugstore.

Anywho, I’ll mosie on over to talk-us where we can hash this out further.

**Comment by pmailkeey** [comment] 2016-07-05 15:29
I have created a wiki discussion page: http://wiki.openstreetmap.org/wiki/Talk:Tag:shop%3Dchemist and added relevant definitions for the UK. Perhaps those with experiences of similar outlets can generate definitions for their country - then perhaps we can see where the common ground lies and how we can work around the differences ?

**Comment by 1ec5** [comment] 2016-07-05 15:51
> I read in the wiki that we are encouraged to make edits

Sure, as long as the wiki’s tag pages reflect consensus among mappers and established convention, and proposals are clearly marked as such. Feel free to edit the pages within that one constraint; also, other pages are fair game.

I started a discussion on the [talk-us](https://lists.openstreetmap.org/pipermail/talk-us/2016-July/016519.html) and [tagging](https://lists.openstreetmap.org/pipermail/tagging/2016-July/029569.html) lists. If nothing else, it’ll be an educational exercise for U.S. mappers, because I’m sure I’m not the only one who (for better or worse) has been tagging drugstores as `amenity=pharmacy`.

**Comment by pmailkeey** [comment] 2016-07-05 16:05
In the UK if you're looking for drugs, you'd go to a 'head shop' but if you want medicines, you'd go to the chemist.

**Comment by pmailkeey** [comment] 2016-07-05 16:41
There appears to be confusion regarding 'hierarchy'. A pharmacy is part of a drugstore and part of a 'building'. Not the other way around in both cases !

**Comment by 1ec5** [comment] 2016-07-06 04:24
> A pharmacy is part of a drugstore and part of a 'building'. Not the other way around in both cases !

Um, of course. I’m not talking about a physical hierarchy, I’m talking about what makes a drugstore a drugstore. Anyways, now that the mailing list thread has been started, let’s please move the discussion there.

**Comment by 1ec5** [comment] 2017-07-05 10:40
#4127 proposes a validator to nudge mappers to map pharmacy counters along with the drugstores, since there does appear to be a discoverability problem.

**Comment by bhousel** [comment] 2019-01-04 06:12
Happy 2019!
Now seems like as good a time as any to rename "Pharmacy" to "Pharmacy Counter" in iD, so I did that in https://github.com/openstreetmap/iD/commit/a1bc6b3e31a899179b98bb51d402db518192a68a

Since around 2015 some people ([see wiki talk page](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dpharmacy)) have suggested mapping 2 features:  the outer store as a `shop=chemist` (aka "Drug Store") and the inner pharmacy counter as an `amenity=pharmacy`.  This makes sense, as they often have separate `opening_hours` and contact information, and it's also the only way that works when a pharmacy operates a separate space inside a larger business like a Target or Costco.

Hope this change helps clear up the previous `chemist` vs `pharmacy` confusion!

**Comment by bhousel** [comment] 2019-01-04 06:39
> In order to address the discoverability concerns raised above, both the `shop=chemist` and `amenity=pharmacy` presets need to appear when searching for either “pharmacy” or “drugstore”. Otherwise, a mapper who calls drugstores “pharmacies” may search for “pharmacy” and come away unaware that the overall drugstore can be tagged too; likewise, a mapper who calls them “drugstores” may not be aware of the Pharmacy Counter preset.

Very good point @1ec5  - I just adjusted the synonyms so this now works.  They'll both show up for either search.

<img width="280" alt="screenshot 2019-01-04 01 37 03" src="https://user-images.githubusercontent.com/38784/50676276-84a4ac00-0fc1-11e9-8c2e-e588929c22fb.png">

☝️ It would be great to adjust the wording slightly on these documentation lookups.
