### ISSUE TITLE
ID shows Warnings, but no corrective actions suggested

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#6898] opened 2019-09-29 15:31 UTC
ID used to show the Warning (Tags, Conections, etc) and also Corrective actions to be taken. Now is just the Warnings.

**Comment by quincylvania** [comment] 2019-09-30 08:54
@jjiglesiasg We didn't remove the fixes. Can you provide a screenshot of where you are seeing the issue?

**Comment by quincylvania** [comment] 2019-10-12 12:11
Closing this as unable to reproduce and lacking further info.

**Closed by quincylvania** 2019-10-12 12:11 UTC
Labels: bug-cant-reproduce, validation
