### ISSUE TITLE
KeepRight error is not showing what is the error 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#9150] opened 2022-06-07 15:53 UTC
### URL

https://www.openstreetmap.org/edit?editor=id&node=8922128860#map=24/50.07568/19.92293

### How to reproduce the issue?

Open https://www.openstreetmap.org/edit?editor=id&node=8922128860#map=24/50.07568/19.92293

Enable KeepRight error display

select error

become confused when error is not explained

happens with disabled adblock

### Screenshot(s) or anything else?

![screen03](https://user-images.githubusercontent.com/899988/172425765-9fa9cb6f-5c0b-436a-b419-22f78de503b0.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by matkoniecz** [comment] 2022-06-07 15:54
appears to be not covered by #5679 and #9068 is not happening

**Comment by arch0345** [comment] 2022-06-07 21:31
This looks like a duplicate of #8963, see if this is still an issue in v2.21.0:
https://ideditor-release.netlify.app/

The fixes in https://github.com/openstreetmap/iD/commit/fe15d69b0cd4994c75b30fb5be300a11e26db699 haven't shown up on osm.org yet since it's still on v2.20.4

**Comment by arch0345** [comment] 2022-06-08 15:37
The version on osm.org just got updated to v2.21.0 and it seems to be working now:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/85302075/172658430-740f4de9-ed38-4eb0-95f2-faeeb3006a84.png">

**Closed as completed** 2022-06-09 16:34 UTC
