### ISSUE TITLE
Hidden roads and paths that are not able to be deleted

### ISSUE THREAD

**Issue by afropoker** [openstreetmap/iD#5135] opened 2018-07-12 11:44 UTC
Hello,

There is this a false road and pedestrian path in Ulaanbaatar, Mongolia. You can see it by in Edit mode and zoom out till where you cannot edit, you will be able to see a road from Sukhbaatar square to south over the train road, like a triangular. But when you zoom in to edit, it disappears. This is really annoying because this false road shows on Facebook maps, a road does not even existed. 
Screenshots below:
[https://imgur.com/a/5U8DTcv](url)

Thanks

**Comment by afropoker** [comment] 2018-07-12 12:31
https://i.imgur.com/sD9fbS1_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

https://i.imgur.com/GqMmwnO_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

https://i.imgur.com/OKWtMGE_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by tastrax** [comment] 2018-07-12 12:50
I removed some spurious points where they converged in the south but I can’t see anything at the northern end of the lines

 

Points had no tags – may or may not fix the issue

 

https://www.openstreetmap.org/#map=16/47.9065/106.9217 

 

Cheers - Phil

**Comment by tastrax** [comment] 2018-07-12 13:03
It may be something to do with the duplicate of the park boundary that looks to intersect some pathways

 

https://www.openstreetmap.org/edit?editor=id#map=18/47.91711/106.91830 

 

From: Phil Wyatt [mailto:phil@wyatt-family.com] 
Sent: Thursday, 12 July 2018 10:51 PM
To: 'openstreetmap/iD'
Subject: RE: [openstreetmap/iD] Hidden roads and paths that are not able to be deleted (#5135)

 

I removed some spurious points where they converged in the south but I can’t see anything at the northern end of the lines

 

Points had no tags – may or may not fix the issue

 

https://www.openstreetmap.org/#map=16/47.9065/106.9217 

 

Cheers - Phil

**Comment by afropoker** [comment] 2018-07-12 15:53
I cant seem to find a way to delete. Seems like a bug to me. Any one can help?

**Comment by bhousel** [comment] 2018-07-12 18:04
Thanks for fixing @tastrax  -  I don't see any issue here now.

@afropoker, iD doesn't allow users to edit very large features (where you can't see the entire feature).  As a workaround, you can delete individual points until the feature is small enough to work with, or use another editor like level0 or JOSM.

**Closed by bhousel** 2018-07-12 18:04 UTC

**Comment by afropoker** [comment] 2018-07-12 20:35
Excuse me. The issue is not fixed!

**Comment by bhousel** [comment] 2018-07-12 20:39
> Excuse me. The issue is not fixed! Please reverse

Can you link to the osm object that you aren't able to delete?  Or share the way id?  I looked at the map around https://www.openstreetmap.org/#map=16/47.9065/106.9217 and nothing really stood out as broken.

Your screenshots were from rendered maps - not actual OSM data as it appears in iD.

**Comment by tastrax** [comment] 2018-07-13 05:00
https://www.openstreetmap.org/edit?editor=id#map=15/47.9118/106.9230 It seems to be the spurious lines converging into a point. When you zoom in to edit level they disappear

 

Cheers - Phil

**Comment by bhousel** [comment] 2018-07-13 05:12
Thanks for clarification @tastrax  - The spurious lines are in the raster "locator overlay" layer.

That locator overlay layer that displays at low zooms is not part of the iD project - it is an external layer managed by Mapbox cartography team. It is updated sometimes, but often contains older data.  I don't know how often it is updated, but the important thing is that the real data in OSM has been fixed already.

**Comment by afropoker** [comment] 2018-07-13 05:29
Is there a way to contact Mapbox team? That line has been there for over 2 year as I always see it on facebook map
Thanks a lot for your help.

**Comment by tastrax** [comment] 2018-07-13 05:54
https://www.mapbox.com/contact/

**Comment by bhousel** [comment] 2018-07-13 12:48
> Is there a way to contact Mapbox team? That line has been there for over 2 year as I always see it on facebook map
> Thanks a lot for your help.

It sounds like @tastrax only fixed this artifact 1-2 days ago.  It takes some time for other rendered maps to catch up.

see https://www.reddit.com/r/openstreetmap/comments/6ynboz/how_long_does_it_take_for_a_edit_to_get_published/

I think @ericfischer may be the person who knows most about how frequently the Locator Overlay map is updated.
