### ISSUE TITLE
Deutsche Übersetzung: Wald- / Feldweg wurde durch 'Nicht erhaltene Straße' ersetzt (?)

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#3031] opened 2016-03-13 07:23 UTC
Was bis vor kurzem noch ein (bestens) genutzter und ausgebauter Feld- und Waldweg war, ist nun als 'Nicht erhaltene Straße' bezeichnet.
Bitte wieder zurück zur vorherigen Bezeichnung.

**Comment by kepta** [comment] 2016-03-13 08:37
Hey @st-anton, welcome to iD. 
If this is a duplicate of #3032 can I close this ?

**Comment by manfredbrandl** [comment] 2016-03-13 09:15
The tag highway=track has been renamed from "track" to "unmaintained track road" and my initial Translation (in Transifex) was wrong and has been corrected already. It will arrive at the users with the next release.

**Comment by st-anton** [comment] 2016-03-13 15:21
I wrote in german, because it's a german issue :-) Anyway, as long as users know what tag they should take..
Naturally the wiki needs to be adapted as well like [http://wiki.openstreetmap.org/wiki/Hiking](url)

**Comment by bhousel** [comment] 2016-03-13 16:28
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) and that is the best place to fix issues with translated strings.  As @manfredbrandl mentioned, this preset label has already been changed on the Transifex site, and the new translation will be used when we make a new release of iD.

**Closed by bhousel** 2016-03-13 16:28 UTC
