### ISSUE TITLE
Add field / key autosuggestion for tag dog=

### ISSUE THREAD

**Issue by RayBB** [openstreetmap/iD#10526] opened 2024-11-03 18:21 UTC
### Description

Hello,
I'm mapping some cafes in my area and many are explicit with yes/no for dogs.
Ultimately, I'd like to make a little interactive tool for my area to show dog friendly cafes (kinda like https://mapcomplete.org/pets.html?z=16.5&lat=4.731443461978699&lon=-74.04162554409845#node/703563897)
It would be nice if dog was part of the fields autocomplete so I don't have to manually enter the key each time.

https://wiki.openstreetmap.org/wiki/Key%3Adog

Thanks!

### Screenshots

<img width="383" alt="image" src="https://github.com/user-attachments/assets/3772fb5a-9ea1-463b-8ec2-11f8b256e1f3">

**Comment by k-yle** [comment] 2024-11-03 22:43
Duplicate of https://github.com/openstreetmap/id-tagging-schema/issues/1380

**Closed as not planned by k-yle** 2024-11-03 22:43 UTC
Labels: duplicate
