### ISSUE TITLE
The /edit?way=... does not pan/zoom the editor

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#4295] opened 2017-08-29 06:16 UTC
A url for editing an object, such as `/edit?way=...` or `/edit?relation=...` do not pan or zoom the map in the editor. On the other hand, `node=...` works fine (as it is clearly much easier to position).

Originally reported at https://github.com/openstreetmap/openstreetmap-website/issues/1622

**Comment by yaugenka** [comment] 2017-08-29 19:27
The same issue is observed when you click on an item in the search panel. Although it is not consitent - sometimes it pans to the object, sometime it just switches to it but does not pan the map.

**Comment by yaugenka** [comment] 2017-08-29 23:21
This is quite a big issue since you have to search for an object twice to get to its geometry.

**Comment by tyrasd** [comment] 2017-08-30 07:34
@yaugenka – good observation. It's very likely caused by the same issue in iD, which is that [`zoomToEntity`](https://github.com/openstreetmap/iD/blob/d493ee9a8986b6a68d85bea0eeee56e39b65f6bb/modules/core/context.js#L118-L125) doesn't properly take all the data it loads into account (e.g. the nodes of a way) to determine the extent/bbox to [zoom to](https://github.com/openstreetmap/iD/blob/master/modules/renderer/map.js#L652).

**Comment by bhousel** [comment] 2017-09-11 15:57
This is a duplicate of #4276

**Closed by bhousel** 2017-09-11 15:57 UTC
Labels: bug
