### ISSUE TITLE
Uncaught Error Entity xxxx not found - not able to save changes

### ISSUE THREAD

**Issue by 07pepa** [openstreetmap/iD#2736] opened 2015-07-19 08:02 UTC
if i make many changes ( over 100) it is not able to save it

**Comment by bhousel** [comment] 2015-07-27 18:22
Which browser are you using?   Can you open a developer window and see if you are getting any script or network errors?

**Comment by Mairie-Lesparre** [comment] 2015-08-28 15:44
I've this issue too with Chrome browser.

Here is the error detected in the developer window:
```PUT http://www.openstreetmap.org/api/0.6/changeset/create net::ERR_CONNECTION_RESET
id-98fb6f05162f92dd0530aa9929cb3dc0.js:5```

Can you help me?

**Comment by pnorman** [comment] 2015-08-28 21:00
> I've the same issue with Chrome browser.

Do you get it consistently, and only with large changesets?

**Comment by ultinate** [comment] 2015-08-28 22:26
I have the same problem: I press Ctrl+S, then I click the button to save my 200+ edits. Nothing happens. 
Browser: Chrome 44

F12 shows "Uncaught Error: entity n3501497837 not found" in http://www.openstreetmap.org/assets/id-98fb6f05162f92dd0530aa9929cb3dc0.js

**Comment by andrew-hill** [comment] 2015-09-07 10:37
I was getting this frequently when I did a lot of changes, and have partially tracked it down to merging features (or at least this was one cause of the issue). If any feature was both edited and merged, I couldn't save and would have to start again, losing all edits.

**Comment by Bonbadil** [comment] 2015-11-24 08:38
I have the same problem and this error in the Firefox Developer Edition 44.0a2 Console window:
```
Error: entity n3223662399 not found
iD.Graph.prototype.entity()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:81
iD.Graph.prototype.childNodes()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:81
o/<()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:81
Z()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:17
ve/<()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:17
o()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:81
i()
 id-c5a06268c29796565bab3e116e4aa52eabf3c76a7bd74335b458626662ba05f9.js:81
```
It count only 18 changes, and I don't think there is any segments merge. I will keep this use case a bit...

**Comment by bagage** [comment] 2015-12-13 18:27
Hitting the same issue since last release (twice in 3 days). Currently, I have only 3 modifications and get error:

> Error: entity n3517604336 not found

My 3 changes are (from oldest to newest):

1. Add name to an unnamed way "Allée des"
2. Correct previous name (I think there is something wrong here). "Allée des Églantines"
3. Add name to another unnamed way "Allée des Pommiers".

**Closed** 2015-12-23 04:36 UTC
Labels: bug

**Comment by bhousel** [comment] 2015-12-23 04:39
As mentioned in that commit message:  Entity not found is caused by subtle bugs elsewhere in the iD code and it should not prevent users from saving their work because it can't be thoroughly conflict checked.  So I'm ignoring those exceptions in the save code only.

I've been spending a few days looking for other things we do elsewhere in the code that can cause the graph to become inconsistent, so hoping to make a few other changes to improve stability.
