### ISSUE TITLE
Add an option to display Grid Lines as an overlay

### ISSUE THREAD

**Issue by ianp5a** [openstreetmap/iD#3369] opened 2016-08-21 14:14 UTC
Problem: When examining large areas zoomed in close, it is difficult to know where you have already examined. This is typical with the Missing Maps Project with vast desolate areas with few details. Today we follow roads or other features. But in between we are lost. And try to scan back and forth.

ENHANCEMENT Suggestion: An Option on the layers menu to display a Grid of Horizontal and Vertical Lines with a given spacing. The lines can be marked a number flag, on the line, so you can note which areas you've viewed.  
Spacing:  -  A value or slider lets the user set the spacing. The vertical and horizontal spacing is the same. i.e. a square grid.  A typical grid spacing will be just 2 vertical and 2 horizontal lines visible when zoomed in close for editing.
Display:   - The grid lines are not selectable. The grid can be temporarily hidden. The line colour, thickness and intensity can be set to be non intrusive.  Or the colour can be the negative of the underlying map for clarity. The number flag will always be on screen when it's grid line is on screen.
Origin:   -   The origin of the grid can be at a default position. E.G. Centre of the current screen. Or a given position by click or coordinate. Or last coordinate. So it can be reused later.
An "Absolute" or "world" grid of degrees/minutes/seconds would also be acceptable.
Minimap:  -   As additional enhancements, if the Minimap overview thumbnail is on, the grid is also visible there. Click on any square on the Minimap, and the main view zooms in to that square. To speed up zooming.

**Comment by bhousel** [comment] 2016-08-24 15:21
We can improve on this, but in the meantime you can enable tile debugging, which would give you a grid.   

What I'm describing is not easy for most users to do, and I don't consider it a solution for your request, but just something fun to try out.  We could use a similar technique to render more useful graticules on the map.

For example, using Chrome browser, on openstreetmap.org
1. open dev console
2. change target to `id-embed`
3. type `id.setDebug('tile')`

![screenshot 2016-08-24 11 10 59](https://cloud.githubusercontent.com/assets/38784/17936105/b1392fa8-69eb-11e6-8207-c5628d5806d3.png)

Will show this:
<img width="600" alt="screenshot 2016-08-24 11 11 43" src="https://cloud.githubusercontent.com/assets/38784/17936169/e39c0182-69eb-11e6-9529-34210b53c12d.png">

**Comment by ianp5a** [comment] 2016-08-25 14:30
Thanks. Those lines would actually be acceptable for this request. But the text labels not.
I don't use Chrome browser so I'll have to wait.

**Comment by bhousel** [comment] 2017-10-01 15:06
Closing here.. If somebody wants to make some transparent overlay tiles with lat/lon graticules on them, and submit a PR to [editor-layer-index](https://github.com/osmlab/editor-layer-index), I'd accept it.

**Closed by bhousel** 2017-10-01 15:06 UTC
Labels: considering

**Comment by pnorman** [comment] 2017-10-02 04:02
duplicate of #2186
