### ISSUE TITLE
Road Names

### ISSUE THREAD

**Issue by Tntdruid** [openstreetmap/iD#7416] opened 2020-03-09 11:25 UTC
The road names does not always render in lates FireFox.

Any way to fix that?
![firefox_2020-03-09_12-23-11](https://user-images.githubusercontent.com/72948/76208955-082ede00-6201-11ea-8ee5-ef6b34ca96fb.jpg)

https://www.openstreetmap.org/edit#map=19/55.75584/12.34834

**Comment by quincylvania** [comment] 2020-03-09 16:52
Hello and welcome, @Tntdruid.

This looks like a duplicate of #7132. This started happening in Firefox 70. I'm not quite sure what's going wrong :/

**Closed as completed by quincylvania** 2020-03-09 16:52 UTC

**Comment by Tntdruid** [comment] 2020-03-09 17:10
@quincylvania thanks.
