### ISSUE TITLE
Tooltips a bit off in tutorial

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3463] opened 2016-09-28 20:23 UTC
The tooltips seem a bit off in the tutorial, like they don't have quite the correct surface dimensions to work with, or maybe elements they are point at moved and the tooltips didn't catch up.

<img width="536" alt="screenshot 2016-09-28 16 21 36" src="https://cloud.githubusercontent.com/assets/38784/18930870/c8670f02-8597-11e6-8301-814265e9b66b.png">

**Comment by pnorman** [comment] 2016-09-29 11:01
I believe this is a duplicate of another issue, but can't find it from my phone.

**Closed** 2016-10-27 18:16 UTC
Labels: bug
