### ISSUE TITLE
Continue area drawing

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4610] opened 2017-12-11 23:55 UTC
Sometimes you might need to continue drawing an area, e.g. river bed. Right now you have to cut the line, detach, continue drawing from one of the ends and merge the lines at the end. It would be nice to have a possibility to continue drawing an area from any node.

**Comment by boothym** [comment] 2017-12-13 00:17
This also happens when you accidentally close an area - would be good to be able to undo and continue in area edit mode again.

**Comment by bhousel** [comment] 2017-12-13 03:11
This is a duplicate of #2272
We might also support a modifier key or some other special mode to let you extend areas or lines
see https://github.com/openstreetmap/iD/issues/1711#issuecomment-92989335

**Closed by bhousel** 2017-12-13 03:11 UTC
