### ISSUE TITLE
I want to access Map Notes within iD

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3090] opened 2016-04-27 13:44 UTC
My work flow is:
- switching on Map Notes
- finding a Note I can close
- switching to Edit mode (with iD Editor)
- editing
- saving
- switching back to "Normal Mode"
- switching on Map Notes
- closing Note

I would prefer the following loop:
- Note reading
- editing
- saving
- Note closing

**Comment by tyrasd** [comment] 2016-04-27 14:13
Duplicate of #2629

**Closed by tyrasd** 2016-04-27 14:13 UTC
