### ISSUE TITLE
Convert decimal separator "," to"."

### ISSUE THREAD

**Issue by Luzandro** [openstreetmap/iD#8470] opened 2021-04-23 11:27 UTC
There are countless of highways with width=0

I guess many of them result from entries using comma as decimal separator, like "0,5" which gets truncated by iD to "0" instead of getting converted to "0.5"

Besides that it's questionable why 0 is even accepted as valid value for e.g. width

**Comment by 1ec5** [comment] 2021-04-24 23:00
Thanks, this is a duplicate of #3615.

**Closed as completed by 1ec5** 2021-04-24 23:00 UTC
