### ISSUE TITLE
Add "Abort" button while upload is processing (saving)

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5542] opened 2018-12-01 23:19 UTC
Approximately once or twice per week I noticed that an upload couldn't finished for any reason, after pressing the "save"-button.
(I don't know why, maybe it's a bit related to the amount of the changes per changeset.)
Then I try to refresh the entire iD-Editor browser tab, after this app 50% of the cases iD offers to recover my last (not uploaded) changes and for the rest of the other 50% all changes are lost, because there is no data recovering dialog coming up.... 

Anyway, I don't want to have the need to refresh the endless running upload iD browser tab, I prefer to have an option at least to get back UI-access and stop this action to maybe store the changes as *.osc file. So could you add an ABORT button for this screen/action, see here:
![id-upload](https://user-images.githubusercontent.com/27923772/49333753-be4e5580-f5c4-11e8-8cff-378d975b7899.png)

Maybe create a similar option like https://overpass-turbo.eu/ offers for their query process, see here:
![op query abort](https://user-images.githubusercontent.com/27923772/49333765-f8b7f280-f5c4-11e8-979c-ffe7b4e2db3f.png)
:

**Comment by bhousel** [comment] 2018-12-02 02:03
Thanks, this is a duplicate of #4717

**Closed by bhousel** 2018-12-02 02:03 UTC
