### ISSUE TITLE
Tab-Button does not jump to the right spot after a tag is added

### ISSUE THREAD

**Issue by rebio** [openstreetmap/iD#4494] opened 2017-11-01 16:44 UTC
A pretty weird bug that I yet don't know how to exactly reproduce.

I edit a way/node/area and type in any key and press Tab to go to the tag. I enter the tag and press tab again to go to the next key. Instead of saving the tag and going to the new key field it does delete the inserted tag and jumps right to the tags field of the new key.

![bug example](https://user-images.githubusercontent.com/10911084/32285796-b5fd3dea-bf2b-11e7-91ef-eabcd83305be.jpg)

In the image above you see what it looks like. I created the area, wanted to insert area=yes. I entered "area", pressed tab. It jumped to the tag. I inserted "yes" and pressed tab again so that it jumps to the next key. On screen you can see the current cursor position.

**Comment by bhousel** [comment] 2017-11-01 18:32
Thanks for reporting @rebio - do you see this issue on http://preview.ideditor.com/master/ ?
It looks similar to #4424, which was fixed already.

**Comment by rebio** [comment] 2017-11-01 19:47
I can test it with the tip version. However, I have no idea when or why the bug occurs.

It is not bound to an area or the area=yes tag though. I got the same bug while adding information to nodes and ways and also more than one way (so not a specific one, but random ways) a few times today. Since it's not a bug that appears once every full moon, I should get it sooner than later.

**Comment by 1ec5** [comment] 2017-11-01 23:25
Thanks for reporting this issue! I've been reproducing this issue in Firefox on the Mac for years, but it comes and goes from month to month for me, and I'm not sure whether it's iD's fault or Firefox's. I've gotten used to avoiding the Tab key in favor of clicking in the margin beside the textbox, which can be pretty inconvenient.

**Comment by bhousel** [comment] 2017-11-06 02:26
If this is intermittent, I wonder if it's related to a slow network connection fetching autocomplete values from taginfo and then trying to focus on the wrong field.. Like #2876

**Comment by rebio** [comment] 2017-11-06 20:44
I had this problem on various PCs with different internet connections (range from 2-125 MBit). So it is possible that it is related to the speed, but I don't think so.
I may thought that iD is stumbles over too fast editing (so you write faster than iD can search for the terms and you just press tab before iD can list the suggestions)

I have done a few edits with the latest builds now. I noticed that they are painfully slow, but I have not seen this bug so far. But since the bug appeared out  of nowhere I'm not sure if it's really gone for good.

**Comment by rebio** [comment] 2017-11-14 19:41
I'm just editing with 2.5.0 and the bug still exists.
I wanted to add addr:street, pressed TAB. then Ctrl + V to insert the street name, then TAB again. And I got the bug as described above.

**Comment by boothym** [comment] 2017-12-18 00:36
I've also encountered this bug, and it's present on the master version. However it is intermittent, though it can occur on points, lines and areas; on any row of the tag list; and it doesn't matter if a tag value is suggested or not.

If you want to try and reproduce it: draw an area, select natural > wetland preset. Click the + below all tags, type in "wet" and press tab. Type in "ti" so tidalflat appears then press tab. It should to the second box on the third line.

**Comment by 1ec5** [comment] 2018-04-25 00:10
Reverse-duplicate of #4991, which is now fixed. 🎉

**Closed by 1ec5** 2018-04-25 00:10 UTC
Labels: usability
