### ISSUE TITLE
Drawing inner road first causes disconnected warning

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#10019] opened 2023-12-05 04:53 UTC
Super easy to reproduce.
First draw the inner road (the crooked white one here.)
Then join the connecting road (the straight white one here.)
You'll get the warning upon trying to save.

Everything will be OK if you instead draw the inner road last.

Anyway, as you see from the grey nodes, or when right clicking on them,
they are indeed connected.

![20231205T124707](https://github.com/openstreetmap/iD/assets/1230959/87544759-5acd-4eb0-b95a-16057af93f36)

Released version at openstreetmap.org/edit

**Comment by Dimitar5555** [comment] 2023-12-05 10:06
Duplicate of #8900

**Comment by nickrsan** [comment] 2023-12-05 20:00
Yes, agreed - closing as duplicate of #8900. Thanks for the report.

**Closed as not planned by nickrsan** 2023-12-05 20:00 UTC
Labels: duplicate
