### ISSUE TITLE
Traffic lights directions shown on ways that are not `highways` (junctions, curbs, etc.)

### ISSUE THREAD

**Issue by jaller94** [openstreetmap/iD#10536] opened 2024-11-13 13:00 UTC
### URL

https://www.openstreetmap.org/node/3517810431

### How to reproduce the issue?

1. Draw a `highway` line.
2. Draw a junction, curb or other non-road line that crosses the highway.
3. Connect them with traffic signals.

```
highway=traffic_signals
traffic_signals=signal
traffic_signals:direction=forward
```

## Expected
One indicator of the direction based on the highway.

## Actual
Two indicators of directions based on the highway and the way that isn't a highway.

### Screenshot(s) or anything else?

![2024-11-13_12-00](https://github.com/user-attachments/assets/b1f6a323-01a7-4ecf-9e69-ba0caa2b8221)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

**Comment by tordans** [comment] 2024-11-13 13:23
This is a duplicate of the closed issue https://github.com/openstreetmap/iD/issues/5634

**Comment by tyrasd** [comment] 2024-12-03 09:45
duplicate of #9013

**Closed as completed by tyrasd** 2024-12-03 09:45 UTC
Labels: duplicate
