### ISSUE TITLE
Distinguish iD entries in chrome://history/ 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9617] opened 2023-04-30 23:47 UTC
### Description

Just the other day I was looking in e.g., chrome://history/ 
and well, it would be nice to be able to tell which entries are _definitely_ from iD without needing to hover the mouse upon each and every one!

### Screenshots

![20230501T074418](https://user-images.githubusercontent.com/1230959/235381609-140ffae1-5203-4cc2-97c7-3933bbc35857.jpg)

**Comment by 1ec5** [comment] 2023-05-01 00:23
Duplicate of #8202.

**Closed as not planned by 1ec5** 2023-05-01 00:23 UTC
Labels: duplicate
