### ISSUE TITLE
Map features select all toggle

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3288] opened 2016-07-27 19:50 UTC
Add the option to deselect all of the map features, instead of having to deselect each of them individually. 
Something like this image - the text could change to select all once the check box is ticked, or have two separate options.
 ![untitled-1](https://cloud.githubusercontent.com/assets/16965772/17189880/80dd93be-543b-11e6-943f-fff3791510cd.jpg)

Useful when editing an area with lots of objects or where you don't want the way/area you are drawing to snap to another object.

**Comment by bhousel** [comment] 2016-07-27 19:52
Thanks! this is a duplicate of #2904

**Closed by bhousel** 2016-07-27 19:52 UTC
