### ISSUE TITLE
on mobile browser : double left click cause zoom instead of adding points

### ISSUE THREAD

**Issue by jlmalet** [openstreetmap/iD#4179] opened 2017-07-25 16:42 UTC
Hi!
your online editor is really great and almost working on mobile browser.
however I can't finish the tutorial even with "computer mode activated" on Google chrome because for clicks on map cause a zoom in and not a "enter edit mode"
could be great to avoid map zoom on mobile device on double click
could be great to add also modifying entries in context menu since this one can be poped out by long press...
thanks and regards

**Comment by bhousel** [comment] 2017-07-25 17:36
Thanks @jlmalet!  I know that our mobile support is not good, and we make a bunch of assumptions in the code about mouse events which don't work the same way on a mobile device.  The situation is a bit better than it used to be in the past, since we've upgraded to D3 v4, but there is still a bunch of work to do in other parts of the code around clicking, drawing, selecting things.

This is something I'd love to improve, but just don't have the time and resources right now.  I'll this issue open for now until we can get to it.

**Comment by bhousel** [comment] 2017-07-26 03:09
Closing as duplicate of #2677

**Closed by bhousel** 2017-07-26 03:09 UTC
Labels: touch-mobile-tablet
