### ISSUE TITLE
Node moved to a different way without user interaction

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#6071] opened 2019-03-20 18:28 UTC
I've noticed on a recent edit that a node on a way got moved to a different way without me actually doing it.

Here's the node: https://www.openstreetmap.org/node/60290267/history
It got moved from [Rue Joffre](https://www.openstreetmap.org/way/30281874) to [Rue Basse Sauvenière](https://www.openstreetmap.org/way/223727056).

I didn't even know there was a way to move a node from a way to a different one.

All I did was to move the view to the left then back to the right to see if I would get errors I got during the previous edit.

**Comment by bhousel** [comment] 2019-03-21 14:20
There's not a lot to go on with this bug report.. 
I'm tempted to just blame #5996 which caused certain edits to mess with the `childNodes` array.

**Comment by quincylvania** [comment] 2019-03-27 21:45
Closing this since there's been no further details and it likely has been fixed. @tbertels please comment if you can still reproduce the problem!

**Closed by quincylvania** 2019-03-27 21:45 UTC
Labels: bug-cant-reproduce
