### ISSUE TITLE
1 unconnected Road generates a Warning, but once connected keeps the Warning until you move a terminal node

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#9814] opened 2023-08-04 17:51 UTC
### URL

https://www.openstreetmap.org/edit?way=1006880090#map=18/-17.25117/-68.05175

### How to reproduce the issue?

1) Draw any line and tag as any highway (needs to be connected to the network (Road A)
2) Nearby draw another highway (Road B) but do not connect to the network (You will get a Warning)
3) Draw a highway (Road C) that connect Road A to Road B... The Warning do not dissapear, whatever the 3 roads are correctly connected.
4) To remove the Warning you need will to move at least 1 terminal (connecting) node in Road A and Road B or both ends in Road C.

That 4 step should Not be needed and Warning should dissapear when A, B and C are connected.

### Screenshot(s) or anything else?

![Screenshot (15)](https://github.com/openstreetmap/iD/assets/22849578/e3a3cfee-118c-4516-9898-789ee47d987c)
![Screenshot (14)](https://github.com/openstreetmap/iD/assets/22849578/003ee9d7-6412-4e8f-9442-ee1198e27a86)

### What version numbers does this issue effect?

2.26.2

### Which browsers are you seeing this problem on?

Chrome

**Comment by k-yle** [comment] 2023-08-04 23:32
This was fixed over a year ago in #8911 but that PR hasn't been merged yet

**Comment by nickrsan** [comment] 2023-08-08 23:52
Thanks k-yle (both for fixing it in the PR and for notifying us that this is pending). I'm going to close this as a duplicate of #8911 and #8758 and also hope for that PR to get merged - I run into this bug regularly too!

**Closed as not planned by nickrsan** 2023-08-08 23:52 UTC
Labels: duplicate

**Comment by jjiglesiasg** [comment] 2023-08-15 00:27
By the way this issue produces a permanent Routing issue as well in OSMI
