### ISSUE TITLE
Remember background imagery

### ISSUE THREAD

**Issue by wernerschka** [openstreetmap/iD#2825] opened 2015-11-05 22:29 UTC
Dear iD-Team,

could you please make iD to remember my last used background Imagery source? Right each time I start iD, Bing is used and nor my favourite source. I don't wanna have to change it each time, sometimes I also forget and using the less actual Bing Imagery.

The same I ask for the opacity-value, I'm not sure if it is remembered right now.

**Comment by bhousel** [comment] 2015-11-05 22:34
Yes, this is a duplicate of #1756 
We already do remember the user's background opacity value.

**Closed by bhousel** 2015-11-05 22:34 UTC
