### ISSUE TITLE
Bug when adding new tag after deleting tag(s)

### ISSUE THREAD

**Issue by Thorwynn** [openstreetmap/iD#6610] opened 2019-07-03 02:51 UTC
I think this started in v2.15.1 - not sure, its taken me some time to this pin down. If you delete one or more tags on an object, when you thereafter press the + box to add a new tag, the new empty tag box appears at the position of the last deleted tag, but the cursor jumps to the bottom key. This has caused me to inadvertently alter the text already in the bottom key when I start typing the new key name. Previously the new empty key would appear at the bottom of the list and I would start typing without looking. Example:
![image](https://user-images.githubusercontent.com/47923400/60559741-7559ad80-9d1b-11e9-9f1c-dba57007cba5.png)

**Comment by sun-geo** [comment] 2019-07-05 22:26
Thanks for reporting this. :-)
I noticed sometimes the same behavior, but I couldn't really easy reproduce it.
Now it seems always happened, when at least two lines are deleted before pressing the big "+" button.

**Comment by quincylvania** [comment] 2019-12-10 16:36
Whoops, turns out #7087 was a duplicate of this but it was fixed 👍

**Closed by quincylvania** 2019-12-10 16:36 UTC
Labels: bug
