### ISSUE TITLE
Show addr:housenumbers

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8744] opened 2021-10-10 06:47 UTC
Got an idea!:
Instead of just [empty white markers that all look the same](https://www.openstreetmap.org/edit#map=20/24.23851/120.83489),
![20211010T144415](https://user-images.githubusercontent.com/1230959/136685679-2239b7e3-18d0-4e20-bc4c-00ec0f351271.jpg)
how about also showing their addr:housenumber next to each one?!

**Comment by tordans** [comment] 2021-10-10 11:02
There is some discussion about this at https://github.com/openstreetmap/iD/issues/1524#issuecomment-482778889

**Comment by bhousel** [comment] 2021-11-10 18:51
Yes this is a duplicate of #1524, thanks @tordans 👍

**Closed as completed by bhousel** 2021-11-10 18:51 UTC
