### ISSUE TITLE
Rotate doesn't complete

### ISSUE THREAD

**Issue by Stalfur** [openstreetmap/iD#4053] opened 2017-05-17 23:20 UTC
Another issue in Chrome (Version 58.0.3029.110 (64-bit)).

When I click right-menu and select Rotate I can spin the object around but clicking on mouse does not complete rotation, right click only shows normal Chrome right-click menu and only way to exit rotation mode is to click ESC - leaving the item unrotated.

See video https://youtu.be/zN3Z_xNcAks

**Comment by bhousel** [comment] 2017-05-18 16:59
Thanks for the report @Stalfur..
I'm having trouble reproducing the issue, using Windows 10 and Chrome 58.0.3029.110.

Few questions:
* Does this happen every time, or is it a behavior that you get stuck in sometimes?
* Does pressing <kbd>Enter</kbd> complete the rotation?

**Comment by Stalfur** [comment] 2017-05-18 21:04
As for previous bugs - it is temperamental and only displays itself on occassions. At the moment I can rotate without problems. Next time this happens I'll check for the Enter thing.

**Comment by Stalfur** [comment] 2017-05-26 10:08
A repeat, different PC, same browser and os. Pressing Enter completes rotation.

**Comment by Stalfur** [comment] 2017-06-11 00:05
Chrome Version 59.0.3071.86 (Official Build) (64-bit) on Windows 10 still showing bug. Enter completes, this goes for moving as well as rotation.

**Comment by quincylvania** [comment] 2020-05-13 16:09
Closing this since it's been a few years and lots has changed with iD that could have addressed this bug. @Stalfur Let us know if you're still seeing this or something like it!

**Closed by quincylvania** 2020-05-13 16:09 UTC
Labels: bug, bug-browser-specific
