### ISSUE TITLE
Weird behaviour when copy/pasting wikidata items

### ISSUE THREAD

**Issue by Virtakuono** [openstreetmap/iD#2876] opened 2015-12-14 15:13 UTC
I repeatedly witness the following problem that manifests itself when I try to add a wikidata item to OSM:
1. I go to wikidata and copy the wikidata item (cmd+c) onto the clipboard
2. On iD, I select the object in question and click the plus symbol to add a new field
3. I type wikidata, press tab to move the cursor to the right column at the table and paste (cmd+v)
4. As a result, the wikidata identifier is appended to the string "wikidata" on the left column, not as a separate entity on the right column where I'd want it.

Running Google Chrome 47.0.2526.73 (64-bit) on OSX 10.11.1 (15B42)

**Comment by bhousel** [comment] 2015-12-14 15:30
Weird, I have the exact same versions of the Chrome and OSX and I don't see this at all.  
Is it possible you might have a browser plugin that is messing with your copy/paste?


![wikidata](https://cloud.githubusercontent.com/assets/38784/11785023/9109668c-a24d-11e5-9ec4-6b1c6d535945.gif)

**Comment by tyrasd** [comment] 2015-12-14 16:08
I've seen this behaviour too a couple of times (on random tags, not only wikidata ones), but only occasionally and never more than once per editing session. ([record.ogv.zip](https://github.com/openstreetmap/iD/files/61424/record.ogv.zip))

Now, I've played around a bit more and here's a way to replicate this somewhat reliably: 1) Hard-reload iD making sure all relevant caches are cleared. 2) Enable network throttling in the developer tools and set it to something very slow. 3) add a new tag key, hit tab and then type some characters until you see the cursor switching randomly between the key and value input boxes.

Just a wild guess: Could it be related to taginfo autocomplete requests sometimes not being returned in correct order on slow network connections?

**Comment by bhousel** [comment] 2015-12-14 16:10
> Could it be related to taginfo autocomplete requests sometimes not being returned in correct order on slow network connections?

Oh, yeah this definitely.  Probably the focus has changed by the time the callback is called.

**Comment by quincylvania** [comment] 2019-12-10 17:11
I was unable to reproduce this issue even with extreme network throttling. A lot has changed in browsers and in this code since 2015 so it must be fixed by now.

**Closed by quincylvania** 2019-12-10 17:11 UTC
Labels: bug
