### ISSUE TITLE
Wikidata field preview just displays [object Object]

### ISSUE THREAD

**Issue by nc011** [openstreetmap/iD#9190] opened 2022-06-29 15:16 UTC
### How to reproduce the issue?

1. Edit an object
2. Select Wikidata from Add field drop-down
3. Add a Wikidata identifier

### Screenshot(s) or anything else?

![Screenshot from 2022-06-29 16-11-39](https://user-images.githubusercontent.com/63111813/176472783-0d48a34d-493b-4ebe-9018-cf4eeb67351d.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment] 2022-06-29 17:26
Hi, this is a duplicate of #9067, which is fixed, but the fix has not been released yet. In the meantime, if you already know the QID, you can add the `wikidata` tag manually in the Tags section below.

**Closed as not planned by 1ec5** 2022-06-29 17:26 UTC

**Comment by nc011** [comment] 2022-06-30 07:44
Thanks. Need to remember not just to search the open issues!
