### ISSUE TITLE
Faulty change XML's produced when exporting

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4794] opened 2018-02-13 17:38 UTC
I recently made a large changeset with iD, but because of performance issues I then exported the OSM change XML. Later I uploaded my changeset with iD and everything worked fine. But when I compared it to the formerly exported file using JOSM the result was the following:
![faulty xml](https://user-images.githubusercontent.com/31667811/36164162-d28b44ae-10eb-11e8-9af6-4c2563d29371.png)
Most of the ways I had drawn were not exported, but their nodes were and they didn't even have any tags. Nodes and relations were created correctly, but for some reason ways were not. It could of course be a JOSM issue but I don't believe that since the JOSM files can be read without any problems. It is also not the first time this bug occurs to me. Has anyone else also experienced this error? And if possible, can it be fixed?

**Comment by bhousel** [comment] 2018-02-13 17:58
I've never actually tried this feature, but if you still have the file maybe somebody can take a look at what might be wrong with it?

**Comment by hikemaniac** [comment] 2018-02-13 18:08
Sure! Here it is:
https://gist.github.com/hikemaniac/36428a2e044d89168ffb5b79bb38a2e2

Sorry, but it's formated to be only one line. 😥

**Comment by mmd-osm** [comment] 2018-02-14 17:27
.osc files are really not meant for visualization purposes, as they depend on information which is only available on the OSM database. Take a look at the new way "-3", which references already existing nodes on the database, like 2533420692, 4769801695, etc. The actual lat/lon information for those existing nodes is not included in the .osc file.

`<way id="-3" version="0"><nd ref="4769801711"/><nd ref="-10"/><nd ref="-11"/><nd ref="-24"/><nd ref="-25"/><nd ref="-26"/><nd ref="2533420692"/><nd ref="4769801695"/><nd ref="1113123869"/><nd ref="4769801696"/><nd ref="4769801713"/><nd ref="4769801712"/><nd ref="4769801711"/><tag k="landuse" v="residential"/></way>`

To me, this is that really a works as designed. If you want changeset visualization, other formats like Augmented Diffs would be needed.

https://overpass-api.de/achavi/?changeset=56269894

**Comment by bhousel** [comment] 2018-02-14 18:57
> To me, this is a works as designed. If you need changeset visualization, other formats like Augmented Diffs would be needed.

Thanks for digging into this @mmd-osm  - it makes sense now.  I'll close this since it is working as expected.

**Closed by bhousel** 2018-02-14 18:57 UTC
Labels: bug

**Comment by hikemaniac** [comment] 2018-02-14 19:46
What you say makes sense. I will try to verify the correctness of the XML with one of my next changesets. Thanks for investigating! 😊

**Comment by mmd-osm** [comment] 2018-02-14 19:50
BTW: josm complains about many missing nodes when opening your osc file. Keep an eye on the console output next time.
