### ISSUE TITLE
Telecom medium validation

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#7389] opened 2020-02-26 20:46 UTC
Dear maintainers,

It comes to my attention that mappers can add ;-lists as values for ​telecom:medium key on ​telecom=exchange or ​telecom=connection_point features.

Although it's not intended to cause any harm to the db, it's often not correct to do so, because exchanges or connection_point only have a single medium.
Using several values in medium key means you merge two independent feature in one. This because you see them in the same building but they should be independent.

As to encourage people to split such features, is it possible to raise a warning and stating they may have merge several features please?

**Comment by quincylvania** [comment] 2020-02-26 23:40
Hi @flacombe. I'm looking at the [usage](https://taginfo.openstreetmap.org/keys/telecom%3Amedium#values) of `telecom:medium` and only see about a dozen tags with multiple values. 

<img width="507" alt="Screen Shot 2020-02-26 at 3 36 06 PM" src="https://user-images.githubusercontent.com/2046746/75398238-e3a43f00-58ad-11ea-8a85-bab7ec5f4cc9.png">

We really only add validation rules for common data issues, so I'm closing this as low impact. We can still do #6780 to help people map these correctly.

**Closed as completed by quincylvania** 2020-02-26 23:40 UTC
Labels: validation, wontfix-low-impact

**Comment by flacombe** [comment] 2020-02-26 23:59
Hi Quincy

Low usage of multiple values is because we spend time to clean up them once they appear (at least in my area)
I won't be able to do so in other countries, it would be great iD helps us for that

All the best

**Comment by quincylvania** [comment] 2020-02-27 00:13
> Low usage of multiple values is because we spend time to clean up them once they appear (at least in my area)

@flacombe Thanks for this work!

> it would be great iD helps us for that

The problem is that there's not a clear tag upgrade path, so we can't use iD's existing outdated tags validation rule. We'd have to add a custom rule, which we only do if an issue is widespread. I doubt that thousands of these are getting added. Plus if they're not added with iD then the validation rule wouldn't help much anyway.

I recommend addressing this problem at the source by contacting whatever mappers or tool maintainers employ this pattern.

**Comment by flacombe** [comment] 2020-02-28 20:44
Understood, thank you

I'm more familiar with JOSM logic for validation rules and I may have mistaken the extent of current rules in iD
Instead a validation rule, is it possible to display a hint when using telecom:medium to remind mappers that multiple values are discouraged for this key?

**Comment by quincylvania** [comment] 2020-03-02 17:35
> Instead a validation rule, is it possible to display a hint when using telecom:medium to remind mappers that multiple values are discouraged for this key?

The hint is that iD's field only takes one value. You can edit the tag's wiki and wikibase documentation as needed.
