### ISSUE TITLE
Localization - Missing strings

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#4054] opened 2017-05-18 11:42 UTC
Hi,
The following strings are not available for translation in Transifex.
- 'OpenStreetMap GPS Traces'
- 'Public GPS traces uploaded to OpenStreetMap' 
- 'Locator Overlay'
- 'Shows major features to help orient you'

I attached two screenshots "in Spanish".

![screenshot](https://cloud.githubusercontent.com/assets/13091755/26200671/a9346b24-3ba5-11e7-91da-7f9a0023df4b.png)

![image](https://cloud.githubusercontent.com/assets/13091755/26200745/08bb6ba6-3ba6-11e7-887f-26242144eac1.png)

**Comment by bhousel** [comment] 2017-05-18 11:55
Thanks for the report, and for translating!
This is a duplicate of #4034.

**Closed by bhousel** 2017-05-18 11:55 UTC
