### ISSUE TITLE
Can't see my track(s) in Editor ID

### ISSUE THREAD

**Issue by tkansgar** [openstreetmap/iD#3819] opened 2017-02-05 12:57 UTC
Hi,

I just wanted to load my new GPS track from today in ID editor to correct some streets and paths like I do every weekend. When I click on the link "edit" ("bearbeiten" in German) provided for each track in my track list and then on the link "edit" in the ID section of the displayed window, normally the track is displayed as a pink line in the satelite picture in ID. But today there is no pink line. This applies to all my tracks, also the old ones I edited in ID in the past. What is wrong here? Who can help?

[Edit] In Potlatch the track is visible (a very slim blue line). But I want to use ID. When I switch back to ID, there is no line showing my track.

tkansgar

(Question copied from the [OpenStreetMap Forum](https://forum.openstreetmap.org/viewtopic.php?id=57234))

**Comment by bhousel** [comment] 2017-02-05 17:52
Thanks for the report, I'm going to look what is going on with gpx traces. I'm marking this as a duplicate of #3820 👍

**Closed by bhousel** 2017-02-05 17:52 UTC
