### ISSUE TITLE
2.6.0 greets a user with brightness on 50%

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/iD#4723] opened 2018-01-22 07:22 UTC
Haven't used iD for a while, opened it just now. I have a Bing layer by default, and it looks too dark. Turns out, the recent feature of adjusting imagery parameters backfired: it had brightness on 50% be default. I certainly did not set it by myself. Could you please check default settings?

Firefox 57.0.4, Fedora Linux.

**Comment by bhousel** [comment] 2018-01-22 12:18
Thanks for reporting, yes it should default to 100%

**Comment by bhousel** [comment] 2018-01-22 14:38
Hey @Zverik I'm having trouble reproducing this issue.. I do see the default brightness set to 100% on a first time run (I've tried this on both Firefox and Chrome).  If you did use iD even a very long time ago, it would have remembered the value from before.

Anyway I will leave this open for a little while in case other people report an issue..

**Comment by Zverik** [comment] 2018-01-22 14:44
I think the configuration key for brightness might have clashed with some other key, e.g. for imagery offset. I get the same 50% brightness on my work mac here. Can I help you with debugging this somehow?

**Comment by bhousel** [comment] 2018-01-22 15:20
> Can I help you with debugging this somehow?

Yes!  It's a lot easier to debug on http://preview.ideditor.com/master/ (because it is not embedded in an iframe like on openstreetmap.org) 

The best thing to do is to start iD, (hopefully the brightness is wrong here), then open the developer tools and see what iD thinks the value should be for "background-opacity".

Under Chrome Dev Tools, the tab is called "Application" 

![screenshot 2018-01-22 10 12 33](https://user-images.githubusercontent.com/38784/35227724-cac6c6a8-ff5c-11e7-994d-4cff0e585061.png)

Under Firefox Dev Tools, the tab is called "Storage"
![screenshot 2018-01-22 10 14 47](https://user-images.githubusercontent.com/38784/35227822-260ca9a6-ff5d-11e7-8de8-16674c049722.png)

Ping me on IRC and we'll work through it...

**Comment by mmd-osm** [comment] 2018-01-22 22:02
Here's a very old commit setting background-opacity to 0.5 as default: https://github.com/openstreetmap/iD/commit/b73028029ede6556fc639a53bc62f231efde727c

Not sure if this relevant here, as it's already a few years old.

**Comment by bhousel** [comment] 2018-03-03 01:41
Going to close this, I think it was a onetime issue with reading back a very old value..

**Closed by bhousel** 2018-03-03 01:41 UTC
Labels: bug-cant-reproduce
