### ISSUE TITLE
Can't edit anything because spinner won't stop spinning

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4551] opened 2017-11-21 03:24 UTC
Can't edit anything because spinner won't stop spinning
http://www.openstreetmap.org/edit#map=19/24.16167/120.69314

**Comment by bhousel** [comment] 2017-11-21 03:29
Seems like a duplicate of #4542 / #4547

**Closed by bhousel** 2017-11-21 03:29 UTC

**Comment by jidanni** [comment] 2017-11-21 04:04
Seen in both epiphany-browser and chromium, Debian Linux. Didn't try other browsers.
