### ISSUE TITLE
Remember user's most used presets for nodes, ways and areas

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#4125] opened 2017-07-02 09:23 UTC
When adding a node, a way or an area, the user should be shown features suggestions based on what he adds the most, not just based on Taginfo (#3709). Taginfo shows the most added features _in the past_ by _all users everywhere in the world_, so a feature may actually be very frequent now but not be added anymore because it has already been added, or may never be used by the actual user.

It could be based on the last 100 edits or so.
This could be done by storing (#3002):
- the most used features in the last 100 edits (group "recent")
- the same but the 100 edits before (group "old").
Once the group "recent" reaches 100, the group "old" is removed, and the group "recent" becomes the group "old".
With those 2 groups for nodes, ways and areas, so 6 groups in total.

It might be best to add an id number to each preset to reduce the size of the preferences.
The maximum storage use would be 3 x 2 x 100 x 4 (max feature id size 999 + the ";" character) x 3 (max 100 uses for each feature + the ":" character) = 7200 characters.
But hopefully less if the user uses some features more than once.

https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user says that we can upload maximum 150 preferences at once (255 characters each) (total of 38250 characters), but it doesn't say if we can store more in total.

![id features](https://user-images.githubusercontent.com/3265870/27782101-58e275a8-5fd1-11e7-94a6-8ca4ed5f378b.jpg)

**Comment by bhousel** [comment] 2017-07-02 12:33
iD already does push recently used presets to the top of the preset list.  It doesn't persist these recently used presets between sessions (see #590 for discussion)

iD only uses taginfo for filling suggestions of dropdown fields.

Can you share a screenshot of which part of iD you mean?

**Comment by tbertels** [comment] 2017-07-03 07:26
Screenshot added. ;)

**Comment by bhousel** [comment] 2017-07-03 15:34
@tbertels Thanks for the screenshot - as you edit, do your recently used presets appear at the top of this list? 

Is this issue just that you want them to persist between sessions?

**Comment by tbertels** [comment] 2017-07-04 07:25
I'd like them persist and, instead of showing just the last 4 used:
- to be sorted by x times used
- to show more than the 4 most used
- to replace less useful presets shown below (Park, Hospital Grounds, etc. (why are these shown?) which should be put into existing or new groups, to be always shown at the bottom)

**Comment by bhousel** [comment] 2017-07-07 17:34
Thanks for the clarification @tbertels, I'm going to close here as a duplicate of #590.
What I'd really like to do is add some kind of configurable "Favorites" preset screen that persists between sessions, allows the user to put whatever presets they want there in whatever order, and even assign keyboard shortcuts to them.  Look for this soon!

**Closed by bhousel** 2017-07-07 17:34 UTC
