### ISSUE TITLE
Feature labels disappear sometimes in Firefox

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7132] opened 2019-12-17 19:22 UTC
I've noticed labels behave strangely in iD 2.16.0 on Firefox 70. One consistent bug is that all feature labels disappear upon selecting a feature and only reappear upon a redraw, triggered for example by panning the map or resizing the window. Could not reproduce this in Safari.

![firefox label bug](https://user-images.githubusercontent.com/2046746/71027139-a4e95000-20d8-11ea-9def-d0148f15f1af.gif)

**Comment by karlcow** [comment] 2020-09-08 00:15
This can be reproduced in Firefox Nightly 82

**Comment by karlcow** [comment] 2020-09-08 00:53
This is happening before the click, because when setting a breakpoint on the click, all labels have already disappeared.  Once the selection is made a zoom in/zoom out  or moving the map makes the label reappears while keeping the item selected. Also without clicking a `hover` a specific label makes it disappear. 


the pointer not on top of the label.

```html
<text class="pointlabel-halo point tag-tourism n6630299764" x="705.0164586752653" y="619.2783916816115" style="text-anchor: start;">The Quaker</text>
```

The pointer on top of the label

```html
<text class="pointlabel-halo point tag-tourism n6630299764 nolabel" x="705.0164586752653" y="619.2783916816115" style="text-anchor: start;">The Quaker</text>
```

but when selecting a specific item it doesn't add nolabel to all items in the map. So that looks like more a painting issue with SVG?
When selecting it seems to reassign all the labels by rewriting them in the DOM.

This is calling 

```js
  function textFunction(t) {
    return function () {
      var e = t.apply(this, arguments);
      this.textContent = null == e ? '' : e
    }
  }

```

and it is going through each of them… and remove them

```js
  function selection_each(e) {
    for (var t = this._groups, n = 0, r = t.length; n < r; ++n) for (var i, o = t[n], a = 0, s = o.length; a < s; ++a) (i = o[a]) && e.call(i, i.__data__, a, o);
    return this
  }
```

which is strange because the value is really the text for example `e` == `The Quaker`

<img width="766" alt="Capture d’écran 2020-09-08 à 09 47 17" src="https://user-images.githubusercontent.com/505230/92422426-4dd06180-f1b8-11ea-90a8-b675fc616a54.png">


ah I wonder if it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=725221

@quincylvania maybe just checking if textContent already exists with the same content, and if it does do not overwrite. Maybe that would work.

**Comment by tyrasd** [comment] 2022-02-01 18:26
I can't reproduce this issue using Firefox version 96. Seems like it was either fixed in Firefox or by some other change in iD.

**Closed by tyrasd** 2022-02-01 18:26 UTC
Labels: bug-browser-specific, help wanted
