### ISSUE TITLE
Creating point feature using coordinates

### ISSUE THREAD

**Issue by pedjas** [openstreetmap/iD#8399] opened 2021-03-12 21:15 UTC
It happens that user has to create point feature on the map but he has only latitude and longitude of the object. There is no option to do that.

When user enter coordinates in search, marker is displayed on the coordinate position but it is temporary. It vanishes as soon as user moves the mouse.

There should be option for user to set point by manually typing in latitude and longitude coordinates. It would also be good to have option to manually edit coordinates on existing point.

**Comment by mmd-osm** [comment] 2021-03-12 21:18
Lots of similar issues on this topic, see #6819, et al. All of them have been closed.

**Comment by jidanni** [comment] 2021-05-02 00:28
Today I wanted to put a weather station at a certain point.
E.g., using this list https://e-service.cwb.gov.tw/wdps/obs/state.htm
I now have the coordinates of my favorite point.

Alas, iD's inability to show the user where a given longitude and latitude
are, instead just showing the general area, forces the user to have to
use Google Maps to locate which building's colored roof is next to the given point.



All I know is it is year 2021, and "exact locations are not for amateur mappers" or whatever is getting rather dated. 

Or e.g., we are in the field, and copy down the exact coordinates of a thing, expecting to be able to map it when back at home out of the rain, etc. where there is Internet, etc.

**Comment by 1ec5** [comment] 2021-05-02 05:29
> When user enter coordinates in search, marker is displayed on the coordinate position but it is temporary. It vanishes as soon as user moves the mouse.

I think you’re referring to the search feature on openstreetmap.org, not iD itself. (iD is embedded in openstreetmap.org but has its own search feature while editing.) There’s some discussion about persisting the marker for searched coordinates in openstreetmap/openstreetmap-website#2197 openstreetmap/openstreetmap-website#1607.

> iD's inability to show the user where a given longitude and latitude are

As you may know, the Location Panel displays the latitude and longitude of the selected feature or mouse cursor, allowing you to place a point at the desired coordinate with enough patience. Whenever you don’t have the patience for that, there’s always [level0](http://level0.osmz.ru/). iD may be the default editor but it isn’t the only one you have to use.

> All I know is it is year 2021, and "exact locations are not for amateur mappers" or whatever is getting rather dated.
> Or e.g., we are in the field, and copy down the exact coordinates of a thing, expecting to be able to map it when back at home out of the rain, etc. where there is Internet, etc.

It isn’t about amateur or professional… you may be in the field but it’s unlikely that you’ve found a sign with the exact coordinates printed on it. Consider using a mobile editor such as Vespucci or Go Map!! (For example, in Go Map!!, it takes two taps to center the map on your location and place a point there, and then you can put your phone away and head back home. No need to copy the exact coordinates of anything.)

**Comment by jidanni** [comment] 2021-05-02 06:08
Fine, but let's say the other day I met some professional surveyors with that expensive equipment and they copied down  exact coordinates of a  monument and  gave me the sheet of paper...

Just like for telephone numbers. Sometimes somebody just hands you one on a piece of paper.

Or maybe somebody reads you one over the telephone.

I think the problem is some people I have built up this very big ego problem that they can't give in now because they've invested so much time in the position that it's not good for users to get too close to those dangerous coordinates! Coordinates are things that are only good for missiles and that's too dangerous!

**Comment by 1ec5** [comment] 2021-05-02 06:20
@jidanni, everyone following this repository knows how deeply you care about coordinate input, but your numerous requests for it haven’t persuaded anyone to go out of their way to implement it. Rather than playing what-if, let’s let others try to make a more compelling case for it. In the meantime, you have your workarounds. ✌️

**Comment by jidanni** [comment] 2021-05-02 06:24
Another option for ID users is just to place the object right there somewhere in the apparent center of the screen that the latitude and longitude search gives them, and add a FixMe note saying "I sure hope somebody moves this to the correct coordinates, which are..."
At least that would allow  users to finish their  mapping project before nightfall.

**Comment by jidanni** [comment] 2021-05-02 06:31
I got it! Have a default amateur beginner mode that helps the user find the exact spot where are the coordinates he enters are.

And add an  Advanced Professional Expert Super-Pro++ mode (that requires toggling it on in the settings), that would give the current "somewhere in the center of the screen" search results the experts need to keep their egos intact!

**Comment by pedjas** [comment] 2021-05-02 08:13
> 
> Fine, but let's say the other day I met some professional surveyors with that expensive equipment and they copied down exact coordinates of a monument and gave me the sheet of paper...
> 
> Just like for telephone numbers. Sometimes somebody just hands you one on a piece of paper.
> 
> Or maybe somebody reads you one over the telephone.
> 
> I think the problem is some people I have built up this very big ego problem that they can't give in now because they've invested so much time in the position that it's not good for users to get too close to those dangerous coordinates! Coordinates are things that are only good for missiles and that's too dangerous!

I am pretty sure they understand the issue but they do not care. Their position is that if you have coordinates in non digital form, then it must be you stole them.

For the same reason almost all OSM editing tools are crippled. They are willing to sacrifice speed and easy of use to prevent (supposed) abuse.

After all, they do not have to care about time and effort tagged to do some job, as they do not pay for them. So it does not matter if you can do that in few clicks or have to spend time to go through more complex routine.

**Comment by 1ec5** [comment] 2021-05-02 08:27
> Their position is that if you have coordinates in non digital form, then it must be you stole them.

Of course not. Personally, I add POIs from GNIS all the time, positioning them based on the coordinates on that public domain website. I use exactly the workarounds I’ve been recommending in these discussions: search for a coordinate and use the Location Panel to get the point to within a reasonable distance of the GNIS coordinate. That’s precise enough for most of the GNIS entries, but sometimes if I need to, I’ll open level0 to refine the coordinate further.

Melodrama won’t get the feature implemented faster.

**Comment by mmd-osm** [comment] 2021-05-02 10:38
In case you don't want to / can't use Level0, there's also an "Add Node" feature available in JOSM: (Tools -> Add Node...). 
 
![add_node](https://user-images.githubusercontent.com/5842757/116810238-00d43d80-ab43-11eb-95ce-9d8b8e3702b9.png)

**Comment by jidanni** [comment] 2021-05-02 22:03
https://www.facebook.com/groups/TaiwanMapNuts/permalink/1003375510199259/ has pictures of my professional surveyor friends visiting my house. They gave me the exact coordinates of my house to the millimetre. But as their expensive equipment is rather closed / shuttered. So they had to copy the reading off the screen with a pen, onto a piece of paper to give to me.

**Comment by jidanni** [comment] 2021-05-02 23:03
Wait! If I click `Show my location` I get a precise blue dot!:
![20210503T070113](https://user-images.githubusercontent.com/1230959/116830528-71c83380-abdd-11eb-9c52-113956c3c32c.jpg)
Now all I have to do is install a browser extension to override where the browser thinks I am (can't find a working one on chrome yet.)

**Comment by iandees** [comment] 2021-05-02 23:14
Closing as dupe of https://github.com/openstreetmap/iD/issues/4197.

**Closed as completed by iandees** 2021-05-02 23:14 UTC

**Comment by jidanni** [comment] 2021-05-02 23:19
> I use exactly the workarounds I’ve been recommending in these discussions: search for a coordinate and use the Location Panel to get the point to within a reasonable distance of the GNIS coordinate. That’s precise enough for most of the GNIS entries, but sometimes if I need to, I’ll open level0 to refine the coordinate further.

Oh, you are talking about:
![20210503T070800](https://user-images.githubusercontent.com/1230959/116830821-91139080-abde-11eb-92ef-e09432deb664.jpg)
which gives
![20210503T070825](https://user-images.githubusercontent.com/1230959/116830837-9ec91600-abde-11eb-9441-d591dd7e517e.jpg)

OK, but what if you put the beryllium deposits at
18.79294245,156.88948023
instead of
18.79294245,156.89948023 ?
"At such depths resurveying might be costly."

And how many such operations could one complete in one day before one's
eyes lose concentration?
