### ISSUE TITLE
scaleExtent of custom overlay not respected

### ISSUE THREAD

**Issue by olafveerman** [openstreetmap/iD#2558] opened 2015-03-20 15:28 UTC
We have an issue where a custom overlay is not abiding to the max zoom level of the `scaleExtent` that we set in `imagery.json`.

Removing `!source.isLocatorOverlay() || ` from this line: 
https://github.com/openstreetmap/iD/blob/master/js/id/renderer/background_source.js#L61
seems to solve the issue. Why is it doing this check in the first place?

**Comment by bhousel** [comment] 2015-03-23 14:57
cc @jfirebaugh

**Comment by jfirebaugh** [comment] 2015-03-23 17:14
There was some reason the locator overlay needed to be excluded from this check, but it looks like the condition is backward. I think `||` should be `&&`.

**Comment by olafveerman** [comment] 2015-03-23 23:07
Thanks @jfirebaugh . Condition changed in the above commit.

**Comment by olafveerman** [comment] 2015-03-24 11:42
The first commit introduced a problem with the Locator Overlay. PR #2562 contains a new fix that should address `validZoom` for the Locator Overlay and all other overlays.
The PR also contains two tests.

**Comment by jfirebaugh** [comment] 2015-03-24 16:43
I went back and looked at the history here and now I remember why the condition is `!source.isLocatorOverlay() || source.scaleExtent[1] > z`. The intent is that normal imagery sources should be overzoomed when you go past the maximum scale extent, except for the locator overlay, which shouldn't be shown past z16. So the existing code is in fact behaving as intended.

@olafveerman Can you be more specific about the problem you are seeing?

**Comment by olafveerman** [comment] 2015-03-24 17:00
That might be the issue then. We assumed that overlays would behave as the Locator Overlay and disappear past the max extent. It does explain why its called `scaleExtent` and not something like `visibilityExtent`.

Thanks for looking into it. @jfirebaugh

**Comment by jfirebaugh** [comment] 2015-03-24 17:26
If you need the behavior like the locator overlay for a custom overlay we can add a proper attribute for that in the imagery JSON. `"overzoom": false` for example.

**Comment by olafveerman** [comment] 2015-03-25 14:19
Sounds good @jfirebaugh . Implemented in: #2568

**Comment by bhousel** [comment] 2015-03-28 01:11
closing, thanks for the patch @olafveerman

**Closed by bhousel** 2015-03-28 01:11 UTC
Labels: question
