### ISSUE TITLE
give shop/amenity priority over building=commercial

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2795] opened 2015-10-03 19:40 UTC
I added a commercial building and wanted to add a car_repair to it (small building). 
After adding `building=commercial` via preset and `shop=car_repair` by hand iD gave me no special interface for the car repair.

Retagging to `building=yes` gives me the whole beauty back...

**Comment by bhousel** [comment] 2015-10-13 13:39
I don't really understand what you're trying to do - can you attach a screenshot?

If it's one building, I would probably tag a place like this as `building=retail` and place point nodes inside there for the various tenants and shops (including the car repair place).  `building=commercial` is more for an office or corporate park.

If it's separate attached buildings, I'd make separate areas for each one.

**Comment by HolgerJeromin** [comment] 2015-10-13 20:47
See attached screenshot. 
With `building=yes` i have a nice interface for Betreiber/`operator`. With `building=retail` even the tagged Öffnungszeiten/`opening_hours` is hidden!
Same with building=retail and shop=supermarket. There are especially supermarkets which fills the whole building, so adding a node in it is at least not the only valid tagging.

![github](https://cloud.githubusercontent.com/assets/2410353/10467702/90a56308-71fb-11e5-8699-3340e66c18c3.png)

**Comment by bhousel** [comment] 2015-10-21 03:37
Thanks, I understand now.. This is a duplicate of #2793

**Closed by bhousel** 2015-10-21 03:37 UTC
Labels: presets

**Comment by HolgerJeromin** [comment] 2015-10-21 08:27
Thanks
