### ISSUE TITLE
Spurious "Areas cannot cross over themselves."

### ISSUE THREAD

**Issue by ManDay** [openstreetmap/iD#9951] opened 2023-10-26 14:44 UTC
### URL

https://www.openstreetmap.org/edit#map=20/47.49719/9.74947

### How to reproduce the issue?

iD bars the user from moving the vertex of an area by "Areas cannot cross over themselves". The area does not seem to exhibit any particular issues from visual inspection. If there is some sort of obscure topological artefact somehow which causes it to cross into itself, then it's already there and hasn't been prevented earlier.

Since this blocks all edits, the situation can not be resolved without deleting the entire polygon.

There should be a way to bypass the (faulty?) detection.

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/1059827/4a39893c-1d7b-4feb-a0d5-ca9c1817d732)

None of the selected vertices can be moved. Others can be moved.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by ManDay** [comment] 2023-10-26 16:16
After working a bit more with building parts, this appears to be a recurring problem. I found this again at different building. With almost certainty, the error message is entirely wrong. I suggest to disable whatever detection is involved as it can quickly bring any editing session to a frustrating halt.

**Comment by nickrsan** [comment] 2023-10-27 04:22
Hi there - I'm able to reproduce the behavior, but am doing a bit more research to see if this is expected based on the tagging or a true bug. Thanks for reporting this.

For posterity, I started a discussion in the OSM US Slack at https://osmus.slack.com/archives/C2VJAJCS0/p1698380403864669 - I'll report back here with any conclusions from discussion there.

**Comment by k-yle** [comment] 2023-10-27 05:04
This is a duplicate of #9777 right?

**Comment by nickrsan** [comment] 2023-10-27 05:19
Ahhh, thanks, and yes, it does seem to be. I got distracted by the building outline relation, but the other one does limit it to just two attached multipolygons. I'm going to close this as a duplicate, and we can leave #9777 open for further discussion. Thanks k-yle.

**Closed as completed by nickrsan** 2023-10-27 05:19 UTC
Labels: operation, duplicate
