### ISSUE TITLE
GNIS link does not work anymore after USGS upgrade

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8903] opened 2022-01-18 17:02 UTC
### How to reproduce the issue?

USGS upgraded GNIS last year. 

https://edits.nationalmap.gov/apps/gaz-domestic/static/media/GNIS_user_help.2a839ac1.pdf

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/686438/149983437-af7d50ba-27f1-4852-8f6f-34000474d6b5.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by Dimitar5555** [comment] 2022-01-18 18:35
Duplicate of https://github.com/openstreetmap/id-tagging-schema/issues/272

**Closed as completed** 2022-01-31 13:56 UTC
Labels: duplicate
