### ISSUE TITLE
Duplicate rendering bug when dragging a new note

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5937] opened 2019-02-22 20:28 UTC
When dragging a new note around, the rendering bugs out:
![image](https://user-images.githubusercontent.com/5459452/53269162-0ff80f00-36e0-11e9-948a-651380c4a46d.png)

If the note is then cancelled, these elements persist and clicking them has no effect.

**Comment by quincylvania** [comment] 2019-02-25 18:42
@SilentSpike I couldn't reproduce the issue. Do you have to save it or doing anything in particular or just add it and drag it? What browser?

**Comment by SilentSpike** [comment] 2019-02-25 19:22
@quincylvania 

Chrome Version 72.0.3626.119 (Official Build) (64-bit)

When I encountered it I made sure to reproduce a few times by just adding and dragging (even occurred after refreshing the page). However, upon testing again I can't reproduce this either 🤔

**Comment by quincylvania** [comment] 2019-02-25 19:23
>However, upon testing again I can't reproduce this either

Hmm this this was probably related to some other bug that we fixed in the meantime. If you see the issue again please reopen this!

**Closed by quincylvania** 2019-02-25 19:23 UTC
Labels: bug, renderer
