### ISSUE TITLE
Encourage smaller/more localised changesets?

### ISSUE THREAD

**Issue by smopucilowski** [openstreetmap/iD#8277] opened 2021-01-03 00:22 UTC
When reviewing history at osm.org, it is not uncommon to see changesets that span the entire world. Frequently these are made by the iD editor at osm.org. (Recent example: https://www.openstreetmap.org/changeset/96809971 )

Given changesets should be localised and small (experts will know when to violate this), it would be nice to suggest to commit changes before working on a different area: that is, track modifications and warn when it looks like they're far away.

**Comment by pnorman** [comment] 2021-01-03 03:38
My experience is that iD's workflow tends to encourage small changesets already

**Comment by maro-21** [comment] 2021-01-03 15:59
Duplicate of https://github.com/openstreetmap/iD/issues/7434

**Comment by quincylvania** [comment] 2021-01-05 14:26
> Duplicate of #7434

Yep, see this and #5424.

**Closed as completed by quincylvania** 2021-01-05 14:26 UTC
