### ISSUE TITLE
Stuck in the sand bunker

### ISSUE THREAD

**Issue by davidpnewton** [openstreetmap/iD#9000] opened 2022-02-26 12:49 UTC
### Description

There has been some progress on the issue of tagging for the renderer and golf features. The grass features have been dealt with by #8927, but that still leaves the issue of golf bunkers.

The wiki says, "A type of hazard, also known as a sand trap, which is a depression in the ground filled with sand. Recommended to also tag with surface=sand or natural=sand. Do not use natural=beach--it's not a beach!"

So at the moment like the issue with grass golf features iD appears to arguably not be following conventions. The renderer is not rendering bunkers without natural=sand as golf features in the editing portion. The validator is further suggesting that natural=sand be added so that both surface=sand and natural=sand are present.

This is causing people like DaveF to still go on a crusade to remove this tagging from bunkers and thus producing massive edits both in number of alterations and area covered:

https://www.openstreetmap.org/changeset/117492432

1722 affected ways in that edit covering essentially the whole of England.

In this case iD is nearer to the wiki in its treatment of the situation, but issues are still being caused and edit wars with massive, inappropriately-sized edits are occurring.

From a semantic point of view I'd argue that tagging natural=sand is not correct, but iD is not the only editor to do this. Vespucci also sets natural=sand for golf bunkers as does JOSM. So the case is less clear-cut than for tees, fairways and greens etc.

In any case I'd suggest that the editing renderer needs to be altered so that bunkers are shown in it as golf features merely when golf=bunker is present.

I'll open a separate ticket to look at the validator issue.

**Comment by tyrasd** [comment] 2022-10-11 12:41
duplicate of #409

**Closed as completed by tyrasd** 2022-10-11 12:41 UTC
