### ISSUE TITLE
Give info tooltip on hovering over "upgrade the tags"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7383] opened 2020-02-26 06:16 UTC
I forgot how can I get iD to show me what it is trying to do when it is showing unclear "upgrade the tags".

I finally remembered how to review this automatic edit, but I tried hovering over "Upgrade the tags".

Would it be possible to add tooltip there, among lines "Click info button to review this proposed edit"?

**Comment by quincylvania** [comment] 2020-02-26 18:30
Duplicate of #6408…

**Closed as completed by quincylvania** 2020-02-26 18:30 UTC
