### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by raindropsfromsky** [openstreetmap/iD#4760] opened 2018-01-31 10:47 UTC
I am using FireFox Quantum 58.0.1 (32-bit) on Win 10 (32-bit).

After editing OSm (90 changes), when I press **CTRL+S**, the left panel allows me to enter the Changeset comments. But after that, it does not show the final **Save** button.

![image](https://user-images.githubusercontent.com/9047168/35618848-221d6974-06a2-11e8-8bc5-cdd4e64d9365.png)

I tried to restart FireFox, but it does not help.

**Comment by bhousel** [comment] 2018-01-31 18:51
Thanks for reporting, this is a duplicate of #4108

**Closed by bhousel** 2018-01-31 18:51 UTC
