### ISSUE TITLE
Poor performance when autocompleting change summary

### ISSUE THREAD

**Issue by skylerbunny** [openstreetmap/iD#4587] opened 2017-12-03 20:14 UTC
I'm an editor that has a large number of edits, and presumably, a large number of changelog entries.

When I attempt to fill in a changelog, after editing, that is different from the previous one I've just done, I get a LONG delay with each autocomplete attempt. This can range from several seconds to as long as 1-2 minutes.

My suspicion is that an index is needed per username for changelog entries, to allow quicker fills of 'previously used change entries'; I'd guess a sequential scan is in play that looks like

'SELECT 'changelog entries' for username <USERNAME> with string '^Cha'

...or somesuch, that takes a very long time to return. Obviously I'm just spitballing here and haven't looked closely at the source, but since this hasn't been reported yet at all, as far as I can tell, I'm guessing that this is a problem that manifests in direct proportion to the number of previous changelog entries that must be scanned.

This might be solved either by indexing, or maybe limiting the select to 'the most recent 100 entries' or something like that.

**Comment by bhousel** [comment] 2017-12-03 20:31
iD is using [this](https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets) API call to get the changesets.  

The slowness is either from 1. the OSM API or 2. from iD just trying to put too many things into the d3.combobox around here:

https://github.com/openstreetmap/iD/blob/15ffc20424c1051d0354ce5ef43f95b81c194324/modules/ui/changeset_editor.js#L73-L91

Can you use the developer tools on your browser to help narrow down?  In the developer tools, there are ways to look at the network requests, and you'll see an XHR network request like GET `https://www.openstreetmap.org/api/0.6/changesets?user=nnnn` and be able to tell how long that takes.   I'm betting the problem is on the iD side and not the OSM side, but I just want to be sure.

**Comment by skylerbunny** [comment] 2017-12-03 20:51
Mine came back in about 7 seconds.

That said, what I'm further wondering based on the behavior I see is whether or not this query is made several times based on 'further and further string entry', meaning it crushes itself with queries.

**Comment by skylerbunny** [comment] 2017-12-03 20:53
Stalled 2.49 ms
DNS Lookup 1.05 ms
Initial connection 160.13 ms
Request/Response		TIME
Request sent 0.10 ms
Waiting (TTFB) 5.34 s
Content Download 14.87 ms
Total 5.51 s

**Comment by bhousel** [comment] 2017-12-04 05:10
Thanks for the details @skylerbunny !
I just did a bit of local testing.. It looks like it takes about 5 seconds to fetch the changesets for my account also.  The OSM API only returns the most recent 100, so it's not like there are too many to put into the dropdown.  I'll open an issue upstream to see if this call can be made a bit faster.

I think the best thing we can do for now is to try to eagerly load this list so that it's already available when the user attempts to save.

**Comment by bhousel** [comment] 2017-12-04 19:42
Hey @skylerbunny, it looks like @tomhughes made an improvement on the `openstreetmap-website` side that speeds up the response times significantly.   From my own testing it looks like the TTFB went from about 5sec down to under half a second.  Can you check also - if it looks good, I think we can close this.

**Comment by skylerbunny** [comment] 2017-12-05 13:35
Yeah, definitely better. 1.36 seconds.

**Closed** 2017-12-05 14:01 UTC
Labels: performance
