### ISSUE TITLE
Load own presets

### ISSUE THREAD

**Issue by Stalfur** [openstreetmap/iD#6170] opened 2019-04-10 22:04 UTC
An [idea by Rory McCann](https://lists.openstreetmap.org/pipermail/talk/2019-April/082385.html) on the OSM-talk mailing list is as follows:

> -  people could have their personal tagging presets "saved" somehow
> - maybe one could "load other presets from a remote address" via a URL parameter, allowing 
one to "load a preset with a link". 
>
>Then each iD user wouldn't be able to complain to the iD developers.

**Comment by althio** [comment] 2019-04-10 22:13
duplicate of https://github.com/openstreetmap/iD/issues/3470
work in progress at https://github.com/openstreetmap/iD/issues/5049

**Comment by Stalfur** [comment] 2019-04-10 22:20
My bad, searched for preset for open issues and neither of those showed up

**Comment by bhousel** [comment] 2019-04-10 22:24
Have you tried out the maprules integration that we shipped a few months ago? (#5617)
This should allow anyone to run iD with their own custom presets and tag validations.

**Closed** 2019-04-10 22:30 UTC

**Comment by jidanni** [comment] 2019-10-05 13:43
https://github.com/openstreetmap/iD/pull/5617#issuecomment-481965963 makes maprules sound tough.

Anyway, I was going to open an issue:

Idea: let's say the user often wants to enter areas tagged
```
building=yes
man_made=storage_tank
content=water
material=metal
```
but not often enough to simply use CTRL+C CTRL+V.

So how about in the panel allow him to define
- User preset area 1
- User preset area 2...
- User preset point 1
- User preset point 2...

Or even make aliases for his often used amalgamations.
All I found was http://rdc.moabi.org/presets-and-id/en/

**Comment by quincylvania** [comment] 2019-10-07 07:33
@jidanni MapRules is for advanced use cases like setting up targeted mapping campaigns. Eventually I'd also like to find a good, simpler way reuse tag combinations like you said.
