### ISSUE TITLE
Incorrect node is selected when disconnecting lines

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3783] opened 2017-01-20 21:07 UTC
1. Split a line
2. Select one of the lines
3. Hold Shift and click on the node when the line was split at
4. Click Disconnect
Result: The lines are diconnected but the node of the unselected line is selected.
Expected: The node of the selected line is selected.

**Comment by bhousel** [comment] 2017-01-21 19:19
Thanks, this looks like a duplicate of #2206

**Closed by bhousel** 2017-01-21 19:19 UTC
