### ISSUE TITLE
Args mismatch on preset.unsetTags(...)

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#9707] opened 2023-06-22 13:28 UTC
Seems bad 💥 

https://github.com/openstreetmap/iD/blob/446133d1a468611cd374cdfa95ab080217c85db0/modules/actions/change_preset.js#L25

vs

https://github.com/openstreetmap/iD/blob/446133d1a468611cd374cdfa95ab080217c85db0/modules/presets/preset.js#L221

**Comment by nickrsan** [comment] 2023-06-30 06:06
I just added the release blocker label as a way to elevate the visibility of this issue. The more I think about it/reproduce/see other reports, the more serious it seems. This bug could lead to lots of unintended data being put into the database without a way to track it down. This should be fixed ASAP.

**Comment by nickrsan** [comment] 2023-06-30 06:08
@tyrasd just wanted to raise this issue to your attention.  See openstreetmap/id-tagging-schema#951 for a concrete example that I think is linked to this. 

@1ec5 might be worth your input here too.

**Closed as completed** 2023-07-07 16:58 UTC
Labels: bug-release-blocker

**Comment by tyrasd** [comment] 2023-07-07 17:07
thanks, good catch @bhousel :bow:  But could you please help me with one question: do you recall why you added the `skipFieldDefaults` parameter to the `unsetTags` method in 0357c2b80cbe4a97f0d4a29056f3dbf7f44b25c2 ? As far as I can see the parameter was never actually used anywhere in the code and I can't spontaneously think of a situation where it would be required…

**Comment by bhousel** [comment] 2023-07-07 19:24
> do you recall why you added the `skipFieldDefaults` parameter to the `unsetTags` method in [0357c2b](https://github.com/openstreetmap/iD/commit/0357c2b80cbe4a97f0d4a29056f3dbf7f44b25c2) ? As far as I can see the parameter was never actually used anywhere in the code and I can't spontaneously think of a situation where it would be required…

I'm not sure - It was probably just to keep `setTags` and `unsetTags` as the inverse of each other.
I think it's only called by [`actionChangePreset`](https://github.com/openstreetmap/iD/blob/develop/modules/actions/change_preset.js).
