### ISSUE TITLE
name=* is automatically locked when name:etymology:wikidata=* is used

### ISSUE THREAD

**Issue by pristinewaves** [openstreetmap/iD#10484] opened 2024-10-04 03:13 UTC
### URL

https://www.openstreetmap.org/edit?way=622572893

### How to reproduce the issue?

1. Use `name:etymology:wikidata=*` on a feature without a `wikidata=*` tag

### Screenshot(s) or anything else?

![opera_PabDBIdRO3](https://github.com/user-attachments/assets/e4146901-6c93-4f99-b950-8f454a61dd94)
This should only pop up when `wikidata=*` is used.

![Screenshot 2024-10-04 105525](https://github.com/user-attachments/assets/35ae85b1-1987-4cee-88bd-d9791e87d02e)
`wikidata=*` is not used on chosen feature.

Things I use: Opera 113.0.5230.142

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.3

### Which browsers are you seeing this problem on?

Opera

**Comment by 1ec5** [comment] 2024-10-04 03:15
Duplicate of #8870

**Closed as not planned by 1ec5** 2024-10-04 03:15 UTC
