### ISSUE TITLE
Issue with Tag Conversion and Auto-modification of Elements

### ISSUE THREAD

**Issue by Lancelotance** [openstreetmap/iD#9775] opened 2023-07-13 09:44 UTC
### URL

No response

### How to reproduce the issue?

1. Convert a list of tags to text.
2. Observe that the tags within the list disappear and the original elements lose their attributes.
3. Copy the tag text.
4. Notice that certain elements in the viewport are automatically modified to match the copied tag without any editing being performed.

### Screenshot(s) or anything else?

Uploading id 2.26.1.mp4…

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.26.1

### Which browsers are you seeing this problem on?

Chrome

**Comment by sun-geo** [comment] 2023-07-13 09:54
Duplicate of #9774?

**Comment by Lancelotance** [comment] 2023-07-13 10:01
> Duplicate of #9774?

Well, they are not completely the same. At least, I have not encountered situation like the picture in #9774 .

https://github.com/openstreetmap/iD/assets/109858688/cea62ac8-40e3-4d74-9bf8-4cc1369b20bc

Here's the video failed to upload above.

**Comment by RudyTheDev** [comment] 2023-07-13 10:03
It's probably same as #9762. It just need a hotfix pushed now.

**Comment by k-yle** [comment] 2023-07-13 11:13
This was fixed in #9766

**Comment by nickrsan** [comment] 2023-07-13 18:41
k-yle and tyrasd fixed and deployed as 2.26.2 earlier. Closing this issue, but please let us know if you continue to see similar behavior.

**Closed as completed by nickrsan** 2023-07-13 18:41 UTC
