### ISSUE TITLE
better handle editing API failures

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4431] opened 2017-10-12 18:30 UTC
currently something is wrong with editing API.

Vespucci shows "unable to connect" or something about error code 500

JOSM showed

![selection_001](https://user-images.githubusercontent.com/899988/31512678-1fd3388c-af8c-11e7-81a6-fa50960d10b8.png)

iD just displayed empty area without data.

In case of editing API failure it would be better to show an error rather inviting editors to duplicate data.

**Comment by bhousel** [comment] 2017-10-12 18:36
I agree - this is a duplicate of #4072

**Closed by bhousel** 2017-10-12 18:36 UTC
