### ISSUE TITLE
New elements and edits disappear during edit session.

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/iD#3155] opened 2016-06-10 10:32 UTC
During an edit session I had experienced some weird disappearances of new elements and changes i made but i was blaming myself for undoing/redoing too fast with the shortkeys. But now i am sure!  I just experienced this phenomenon again they just disappear from the editor, map and undo/redo history!

The only thing i can recall that i did in between is that i zoomed out/in and moved a bit, not even out of visual range.

Experienced this on Firefox 47 and i believed also prior the last update.

**Comment by bhousel** [comment] 2016-06-10 11:56
Hey @SHARCRASH, I've noticed this too.  I think what's happening is that:
1. when you start dragging or moving an element it remembers the initial projection so it can position it properly throughout the move
2. since e6c440c it is now possible to redraw while moving, throwing off the projection
3. all subsequent moves/drags will be displaced weirdly

An easy way to trigger it is to start dragging a midpoint or point and then do a mousewheel zoom while dragging.

**Comment by SHARCRASH** [comment] 2016-06-14 08:15
Hmm... I had tried as you suggested, it didn't trigger.

But I experienced again the problem a couple of minutes ago. I think what happened really is that the editing history of the session came back to an earlier state, some of the new lines disappeared and other elements came back to an earlier state, even some new lines not saved yet came back to an earlier state. This happened after i had selected with the lasso selection tool some of their nodes along other "old nodes" already in the database and moving them to reposition correctly. I hope you understand the details i'm giving here, trying to be precise as much as possible.

**Comment by SHARCRASH** [comment] 2016-06-14 08:26
Yeap! Did it again! But not sure anymore for the "coming back to an earlier state". I was trying to finish my edits, selected again several nodes+moved and a new single line got cut in the process, it had never been 2 separated lines... Odd!

**Comment by SHARCRASH** [comment] 2016-06-28 00:51
Dear lord... this is driving me crazy. It happens so often! It's such a waste of time when these edits disappear... 
Noticed something new though: i was editing, i believe nothing was selected, i just moved the map, no mousewheeling, all of a sudden the new elements disappeared, but the number of edits were still at the right number... Then i don't know what happened exactly, moved the map or pushed again the undo arrow, the count of edits went down to 14 whereas it was at 75... Old elements i had erased or moved reappeared at their initial state and the new elements disappeared. Clearly the editor went backward for whatever buggy reason. No way to recover the edits.

**Comment by arschficken** [comment] 2016-07-05 06:25
I've hit this several times now, lost a lot of work.

Both times I had selected multiple items (once individually with Shift, once with the lasso) and moved them, then hit undo. All (or all but the first two or so) changes were lost, undo showed 3 or fewer past changes and none to redo (undoing those past changes also removed them from the redo history).

@bhousel do you have enough information to assign this bug?

**Comment by bhousel** [comment] 2016-07-05 20:31
> do you have enough information to assign this bug?

I think so.. This is helpful, thank you.

**Comment by SHARCRASH** [comment] 2016-07-08 16:31
Yep, i was going to suggest there is some sort of conflict with different lines interconnected. In the past, sometimes when we were trying to move connected node to different lines, the selection couldn't be moved and it seems like that now whenever we move these connected nodes, the bug triggers.

**Comment by arschficken** [comment] 2016-07-16 01:42
Here's how to reproduce the issue. Even from a clean load of the editor.

1. Open https://www.openstreetmap.org/edit#map=20/-37.79400/144.98100
2. Select the Swimming Pool Facility and the short section of wall connected to its north-east corner
3. Move them

This fails with "TypeError: _.all is not a function" and erases the entire session's edit history. Also happens if you select that wall and the wall connected to its south.

Who's got the JavaScript skills to fix this?

**Comment by bhousel** [comment] 2016-07-16 03:35
This will get fixed as part of #3180, but it's probably worth making a patch release with the fix, rather than waiting for whenever iD v2 is done.

**Comment by arschficken** [comment] 2016-07-16 03:46
I would greatly appreciate that!

**Comment by bhousel** [comment] 2016-07-16 04:26
cool, this was fixed already in 50bae40..
I'm making a `1.9.x` branch that we can use to push out a patch release.

**Comment by SHARCRASH** [comment] 2016-07-16 13:57
I don't know if it's related to the same bug but i've experienced now for the 2nd time elements which disappear from the database! So i think this is quite serious!

1st case...
One year ago i had created a MP for heath areas being inner of a forest in this region: http://www.openstreetmap.org/#map=16/49.6677/5.9016
About one week ago, i was making changes in there and noticed that the fill area of that heath wasn't shown in iD, then i clicked on one of its lines to check the relation, not hosting it neither, which was weird because the history of the line in the database was still showing it. I even refreshed the browser several times outside iD to update the tiles and they were still rendered. So i had assumed it was a weird bug... The day after, i continued on the same region and noticed that the tiles were being updated with empty areas instead of the heath. I check the history of the lines but no trace of the "once upon a time" that heath. 

I had taken printscreens of the partial new rendering to have proof it once existed. A few days ago, i recreated it...

2nd case... which happened a few minutes ago.
I was checking, adding details, reconstructing errors, removing temporary names of MP (apparently Potlatch is quite confusing regarding the handling of MPs)... One [footway](http://www.openstreetmap.org/way/390283185) going around a cemetery in a forest was defining the perimeter between both.  I was editing... and all of a sudden that way just disappeared... not sure i moved the map or not. I tried to undo/redo the history, the way hadn't been erased by mistake. I assumed again a weird bug. So I went out of iD, came back in to check if the way would reload, not at all. Got out again and checked the map data like here below and finally could see that it was really erased from the database! I didn't make any save in between...
http://www.openstreetmap.org/#map=19/49.56830/5.84551&layers=D
You can still see the uncorrected cemetery rendered partially.
I see though that it was erased as part of a previous changeset but i didn't erase it and saved. I'm sure! The deleted way doesn't even close the ring totally. I was just erasing obsolete nodes on straight lines, so certainly not erasing the final node...

**Comment by bhousel** [comment] 2016-07-16 14:12
Ok, I think we fixed this, I'm going to release a new version of iD this weekend that includes the patch.

**Comment by SHARCRASH** [comment] 2016-07-16 14:13
Awesome for the new iD! Eager to check it! :)

**Closed by bhousel** 2016-07-16 14:12 UTC
Labels: bug

**Comment by bhousel** [comment] 2016-07-16 15:59
I just made a 1.9.7 release.  Can you try editing with this version of iD, to see if the bug is fixed?
You can test it here:  https://openstreetmap.us/iD/release/

**Comment by SHARCRASH** [comment] 2016-07-16 18:22
Seems working fine... but just did a few edits here and there. By the way, how come some connected nodes move, others not?

**Comment by bhousel** [comment] 2016-07-16 19:23
> By the way, how come some connected nodes move, others not?

I don't know yet.. That's #3195

**Comment by arschficken** [comment] 2016-07-16 23:46
Thanks @bhousel, this seems to be fixed based on the test case I posted earlier.

By the way, isn't it strange that now the URL has latitude and longitude reversed? I.e. the same coordinates on the release candidate server are:
https://openstreetmap.us/iD/release/#background=Bing&map=20.00/144.98100/-37.79400

Why would we specify easting before northing? That's not the way other online map services work.

**Comment by bhousel** [comment] 2016-07-17 00:34
> By the way, isn't it strange that now the URL has latitude and longitude reversed? I.e. the same coordinates on the release candidate server are:
> https://openstreetmap.us/iD/release/#background=Bing&map=20.00/144.98100/-37.79400
> 
> Why would we specify easting before northing? That's not the way other online map services work.

Yeah unfortunately I don't have a good answer for that.  iD uses `lng,lat` internally so our API expects it that way.  The openstreetmap.org server uses `lat,lng` because most other online mapping sites have it that way (and it has special JavaScript code to coordinate their url params with iD's params).

It's frustrating 😕
