### ISSUE TITLE
Mapillary Street Images - forward backward arrows transparent

### ISSUE THREAD

**Issue by tastrax** [openstreetmap/iD#7920] opened 2020-08-22 06:44 UTC
![MapillaryButtons](https://user-images.githubusercontent.com/8775395/90950605-9c7ebb80-e496-11ea-91ee-1c02e795ca9e.JPG)

Backwards/ Stop /Forward button images appear to be transparent

**Comment by brokemyspoke** [comment] 2020-08-29 21:56
Hi @tastrax, are you able to reproduce this consistently.  Do they eventually render?  Also, what browser are you using?  Thanks.

**Comment by tastrax** [comment] 2020-08-29 22:54
Pretty consistent on the latest version of chrome. They never seem to render at all.

**Comment by tastrax** [comment] 2020-08-31 10:37
Identical result on the latest versions of Edge, Opera and Firefox @brokemyspoke

**Comment by brokemyspoke** [comment] 2020-09-01 13:27
There is definitely a bug, but I think it is actually with the OpenStreetMap-website: https://github.com/openstreetmap/openstreetmap-website.  I noticed recent changes in the handling of 'assets' that might provide a clue.  

On the OpenStreetMap.org site, the svg files are no longer being packaged, they could have been overlooked as Mapillary assets are manually copied into dist.  I have not seen any issue/changes in the way iD is building/copying those svg to dist which is why it leads me to conclude the issue is with the downstream consumer of iD.

Hi @quincylvania, I'm not sure the relationship between iD and OpenStreetMap-website development teams, but I can open an issue with them and/or look to resolve the build issue if you agree with my assessment.

**Comment by brokemyspoke** [comment] 2020-09-01 15:07
The css/js were added to app/assets/config/manifest.js, so might be that the svg refs are needed as well.  I haven't explored it too much, so I'll pull the project and check it out.

**Comment by cbeddow** [comment] 2020-09-10 15:48
Updating the MapillaryJS version in the next week will be a first step here to see if the CSS conflict is resolved, but then troubleshoot from there. I'll post here when it's updated.

**Comment by quincylvania** [comment] 2020-09-10 16:25
So I'm pretty sure this is due to #7437. We started scoping iD's CSS under the `.ideditor` class, but the photo viewer plugins like Mapillary have separate CSS which isn't namespaced, and so may be ignored sometimes…

**Comment by cbeddow** [comment] 2020-10-22 23:14
Still an issue here 
![image](https://user-images.githubusercontent.com/10554922/96939315-f6e1cb80-1489-11eb-8149-c5fa387f0c23.png)

@quincylvania is there anything we can do on Mapillary side that would help this?

**Comment by tordans** [comment] 2020-10-23 04:44
Some input on this:

On **Preview** it works https://ideditor.netlify.app/#background=EsriWorldImagery&disable_features=boundaries&map=19.35/52.47242/13.44613&photo=mapillary/4t3r1XIpQoMSrgt1y1S2H4&photo_overlay=mapillary. The css uses a base64 svg for the right-arrow-icon:
```
.SequenceStepNext .SequenceComponentIcon, … {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOS44NzUgOEw0LjM1MyAyLjA1M2ExLjIgMS4yIDAgMDEwLTEuNzAxIDEuMjA2IDEuMjA2IDAgMDExLjcwNCAwbDYuNzMyIDYuNzk2YTEuMjAyIDEuMjAyIDAgMDEwIDEuNzAzbC02LjczMiA2Ljc5NmExLjIwMyAxLjIwMyAwIDExLTEuNzA0LTEuNzAxTDkuODc1IDh6IiBmaWxsPSIjRkZGIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz48L3N2Zz4=);
}
```
(Via https://ideditor.netlify.app/mapillary-js/mapillary.min.css)

On **OSM.org** / https://www.openstreetmap.org/edit#map=19/52.47238/13.44523 (+ mapillary active) it fails. The CSS references an asset which responds with an error 500 at https://www.openstreetmap.org/assets/iD/mapillary-js/stepper-right.svg.
```
.SequenceStepNext .SequenceComponentIcon…{
    background-image: url(stepper-right.svg);
}
```
(Via https://www.openstreetmap.org/assets/iD/mapillary-js/mapillary.min-918915ac7ae00abd861b753d5771b01c7964223f83a8dfa47048c88eab33d6b1.css)

To me, it does not look like a css-scoping issue (https://github.com/openstreetmap/iD/issues/7920#issuecomment-690447021), but an issue of missing files.

---

To me, it looks like this might already be fixed by using the base64 SVG which means, it would be fixed with the next release of ID, right?

**Comment by quincylvania** [comment] 2020-10-23 13:23
@tordans Thanks for investigating this. Looks like they inlined the SVG files in mapillary-js v2.21.0 (#8063), so that must have fixed it 👍

**Closed as completed by quincylvania** 2020-10-23 13:23 UTC
Labels: bug, usability, streetlevel
