### ISSUE TITLE
Closing a note with a comment requires two clicks

### ISSUE THREAD

**Issue by waldyrious** [openstreetmap/iD#9217] opened 2022-07-26 21:25 UTC
### URL

Any

### How to reproduce the issue?

1. Open the editor in an area of the map with an unresolved note
2. Address the note.
3. Click the "New Comment" box under the note's text
4. Enter some text
5. Click the "Close and Comment" button under the text box 
6. The note doesn't get closed, nor the comment added (the text box loses focus)
7. Click the "Close and Comment" button again
8. This time, the note is actually closed.

### Screenshot(s) or anything else?

Here's a short recording of the bug. I had written a comment, and was about to close the note with it.

![2zfuVj6G2b](https://user-images.githubusercontent.com/478237/181114233-41a60f89-e2b6-4626-9fcd-e6ad1d8d6510.gif)

Note that I first hovered the "Close and Comment" button, but didn't click it, because I realized I had lost focus of the text box when I started the screen recording. So to reproduce the issue, I clicked the text box again (notice how its background color becomes a slightly darker gray), and _then_ clicked the button. Since that didn't have the desired effect, I clicked the button a second time, and then the note was closed.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.21.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by waldyrious** [comment] 2022-07-26 21:27
By the way, note in the screen recording above how the "❌" and the "✔️" symbols are misaligned vertically inside the note's speech bubble icon. Not sure if that's something related to my own fonts configuration or something, but thought I'd mention it as well.

**Comment by Dimitar5555** [comment] 2022-12-11 15:00
@waldyrious is this bug still present? I can't seem to reproduce it.

**Comment by danieldegroot2** [comment] 2023-02-25 12:00
This issue is a duplicate of #8994.

> By the way, note in the screen recording above how the "❌" and the "✔️" symbols are misaligned vertically inside the note's speech bubble icon. Not sure if that's something related to my own fonts configuration or something, but thought I'd mention it as well.

This issue has since been fixed in https://github.com/openstreetmap/iD/commit/fe5aba78dc653a5565d69ce70b042368a23f4e5e.

cc: @tyrasd

**Closed as completed** 2023-02-26 15:39 UTC
Labels: duplicate
