### ISSUE TITLE
Handling of route relation membership

### ISSUE THREAD

**Issue by kreuzschnabel** [openstreetmap/iD#4334] opened 2017-09-09 18:32 UTC
In http://www.openstreetmap.org/changeset/50997639 (and others of same user), a route relation using tracks and paths has been decorated by several dead ends. 

This has been caused because the user combined linked ways without paying attention to the fact that one of these ways was member of a route relation while the other wasn’t, causing the route to "fork". See CS comments on further details and a sample screenshot. 

I just checked this behaviour on iD 2.4.1 and found the following:

1. I select one way which is part of the route relation
2. Holding SHIFT, I select another way linked to the first one which is not part of the route relation (the route turns off on the connecting node)
3. I right-click and select "Combine"
4. The ways are merged into a single one which is entirely part of the route now. 

This explains perfectly for the forking of the route relation observed. 

I suggest the following behaviour: 

1. Before combining two ways, they should be checked for relation memberships.
2. In case they are members of different relations, the user should be notified and told explicitly that this is most probably the reason why there are two linked ways instead of a single one, and that they should not be combined into one unless the user really knows what he/she is doing. 
3. The user should be given a list of all relations both of the ways are in, and asked which ones the new way should be member of (as in JOSM).
4. The user should be told that if he can’t make head or tail of this, the action should be canceled, leaving the two ways as they are. 

--ks

**Comment by slhh** [comment] 2017-09-10 00:37
I agree on this bug, and it isn't limited to routes, it is also breaking a multipolygon.
The merge should simply be prevented. I don't think the typical iD user would be able to use 3. of the suggested behavior well.

Issue #2935 is similar with tags instead of relation.

>This explains perfectly for the forking of the route relation observed.

Such a forking can also occur as a result of #2989.

**Comment by bhousel** [comment] 2017-09-10 01:13
Isn't this just a duplicate of #3825 ?

**Comment by kreuzschnabel** [comment] 2017-09-10 07:24
> Such a forking can also occur as a result of #2989.

I thought of that too but I couldn’t provoke that behaviour, it would always start a new way when starting on a node connecting several ways.

That’s why I referred to combining only. 

> Isn't this just a duplicate of #3825 ?

Seems to address the same bug but causing another kind of trouble, so I wouldn’t exactly call it a duplicate.

--ks

**Comment by kreuzschnabel** [comment] 2017-09-10 07:26
> I don't think the typical iD user would be able to use 3. of the suggested behavior well.

It is possible to jump from 2. to 4. :)

--ks

**Comment by slhh** [comment] 2017-09-10 12:36
@kreuzschnabel 
>>    Such a forking can also occur as a result of #2989.

>I thought of that too but I couldn’t provoke that behaviour, it would always start a new way when starting on a node connecting several ways.

Selecting the way and one end node I can easilily provoke that behavior using the "A" shortcut or using the continue operation from the edit menu. I have testet with the official version on osm.org and with the master deployment.


>>   I don't think the typical iD user would be able to use 3. of the suggested behavior well.

>It is possible to jump from 2. to 4. :)

Disabling the merge operation the standard behavior of iD would be to show the reason in the tooltip of the desabled icon, or to display it  in the the status bar in case of using the shortcut. I think this would be fine here.

**Comment by bhousel** [comment] 2017-09-10 13:32
Closing here, as these issues are tracked elsewhere:
#2989 is breakage caused by continue
#3825 is breakage caused by merge

**Closed by bhousel** 2017-09-10 13:32 UTC
