### ISSUE TITLE
KeepRight Issue UI displays nothing. Might be broken.

### ISSUE THREAD

**Issue by nontech** [openstreetmap/iD#9079] opened 2022-04-17 23:14 UTC
### URL

https://www.openstreetmap.org/edit#map=14/33.9882/-84.2575

### How to reproduce the issue?

1. Go to the link above
2. Click on 'Map Data' on the right (one of the several options on the right)
3. Under 'Data Layers', check the box 
:ballot_box_with_check:   KeepRight Issues
4. Select any colored (yellow, blue, red, etc) 'KeepRight' issue on the map
5. KeepRight view opens on the left

Might be related to a similar issue
#8928 

### Screenshot(s) or anything else?

![Screenshot 2022-04-18 01 12 28](https://user-images.githubusercontent.com/14184188/163735647-17a4ebab-3fc8-4d9d-bee4-c5d5678783b8.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by arch0345** [comment] 2022-04-18 15:10
This looks like a duplicate of #8963, seems to be working in the development version: https://ideditor.netlify.com/

**Comment by nontech** [comment] 2022-04-18 23:41
True @arch0345 . 

Just curious:
What's the difference between https://ideditor.netlify.com/ & https://www.openstreetmap.org/edit#map=14/33.9882/-84.2575?
And why does it not work on this link https://www.openstreetmap.org/edit#map=14/33.9882/-84.2575? Is it not the deployed online version?

Thanks for reading and commenting!

**Comment by arch0345** [comment] 2022-04-19 00:05
https://osm.org/edit/ is based on the [latest release](https://github.com/openstreetmap/iD/releases) while https://ideditor.netlify.com/ includes unreleased features/bug fixes listed in the [changelog](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md). Since the bug was fixed after the latest release, it won't be available on https://osm.org/edit until the next release comes around.

**Closed as completed** 2022-04-19 00:22 UTC
