### ISSUE TITLE
Four symbols lack mouseover explanations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4967] opened 2018-04-05 13:32 UTC
Without mouseover explanations,
![0](https://user-images.githubusercontent.com/1230959/38368676-81e17208-3918-11e8-9aa1-4745230dfaeb.jpg)
the user dares not use these.
In fact I almost "wrecked the map" by clicking the second one, only to find out it wasn't what I thought it was. Luckily Undo worked.

**Comment by bhousel** [comment] 2018-04-05 16:55
Weird - you don't see this when you mouse over those things?

![editmenu hover](https://user-images.githubusercontent.com/38784/38380055-96b5aa52-38d0-11e8-8fb1-9a3cd43508e3.gif)

**Comment by hikemaniac** [comment] 2018-04-05 19:35
On my computer with **macOS 10.13.13** with **Firefox 59.0.2** the explanations show as well.
![button explanation](https://user-images.githubusercontent.com/31667811/38372216-8eba9330-38ee-11e8-8c4c-164795bf4609.png)
Maybe it's a browser specific issue?

**Comment by bhousel** [comment] 2018-04-07 17:51
Closing, can't reproduce this

**Closed by bhousel** 2018-04-07 17:51 UTC
Labels: waitfor-info

**Comment by jidanni** [comment] 2018-04-08 01:11
OK sorry. It is working again today.
