### ISSUE TITLE
Doesn't seem to respect language settings

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#8413] opened 2021-03-18 13:24 UTC
Hi again. Still love all you do! :)

My iD editor is in Norwegian, even though my language settings in Firefox says to show me pages in English.

![Screenshot from 2021-03-18 11-09-05](https://user-images.githubusercontent.com/343561/111632668-02e17780-87f5-11eb-8048-6c3f71f14b49.png)
![Screenshot from 2021-03-18 11-09-32](https://user-images.githubusercontent.com/343561/111632729-1260c080-87f5-11eb-8545-1f5378abf164.png)
This isn't right, is it? I am currently in Norway and my OS is in Norwegian. Not sure if that's why, but it should still respect my language settings in the browser.

**Comment by mmd-osm** [comment] 2021-03-18 16:57
You need to set your "Preferred Languages" in your osm.org user profile to "en". This setting overrides your browser language preferences.

**Comment by forteller** [comment] 2021-03-18 18:07
I see. Not sure I agree this is the right way to do it, but thanks for the information!

**Comment by mmd-osm** [comment] 2021-03-19 14:46
In any case this seems like a duplicate of #2242, #1666, and others. There's also the option to override the language setting using an URL parameter, see #5644.

**Closed as completed** 2024-08-03 15:05 UTC
