### ISSUE TITLE
Bug highway=service/service=

### ISSUE THREAD

**Issue by DiogoBaptista98** [openstreetmap/iD#9376] opened 2022-11-15 19:43 UTC
### How to reproduce the issue?

There is a bug with service roads. (highway=service)

The specific type of service road box (service=) is not appearing when we have a defined type for a service road, it only appears when defining the service road with type in a normal service road (without service=).

Also when I reset a service road (which already has a defined type service=) into a normal service road (without service=), the service type is not deleted, there are two options, or in fact it is fixed to delete the specific type and just stay as service general (without service=) or the specific type is maintained and it is eliminated via a type option box that I said earlier is missing.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/54463127/202010759-502e3f3f-cd8b-4250-b8f8-2bbc226df951.png)
![image](https://user-images.githubusercontent.com/54463127/202010779-e301c287-7720-483b-a51d-0b021cb977d0.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Opera

**Comment by 1ec5** [comment] 2022-11-15 20:58
Duplicate of #9372, fixed in 21e54f956daa739a009be0dbd878e730562ce12f.

**Closed as completed by 1ec5** 2022-11-15 20:58 UTC
Labels: bug, duplicate
