### ISSUE TITLE
Suggestions for wikidata:  adjust display if wikidata missing, allow lookups from raw tag editor

### ISSUE THREAD

**Issue by brierjon** [openstreetmap/iD#3929] opened 2017-03-24 22:09 UTC
The ID editor should include checks to make sure an entry with an wikipedia entry has a wikidata entry too and if not add wikidata. I've come across OSM objects that have a wikipedia entry, but no attached wikidata field which may be a legacy data issue. There are other entries which have an existing wikipedia field, but there is no value in the fields content and adding a page name directly to the existing field value results in no wikidata to be added. Placing a check for wikidata entry before save on pages with a wikipedia entry would ensure that these legacy data issues are corrected and that wikidata entries are associated with all pages with a wikipedia field. See such an issue realized in the discussion of [https://www.openstreetmap.org/changeset/47082371](https://www.openstreetmap.org/changeset/47082371)

**Comment by bhousel** [comment] 2017-03-25 05:40
This is true - iD doesn't update existing tags.  It only adds new `wikidata` tags when the user actually modifies the `wikipedia` field.

We don't do any "silent" updating of tags because the OpenStreetMap community is not very accepting of [automated edits](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct).  There are good reasons for this - for example the existing `wikipedia` field might be wrong, so we wouldn't want to just fetch a corresponding `wikidata` value without a human actually reviewing what the field contains.

I agree with your point, and I'd also love to see all the features with Wikipedia values also contain Wikidata values.  But I don't want to add anything to silently set the tag, and I don't want to add any warnings or popups to alert mappers about the missing tag (most new mappers wouldn't care about this).  So I'm going to close this for now because this is a better feature for a data cleanup tool.

**Comment by nyurik** [comment] 2017-03-25 07:35
@bhousel I think there are cases when user changed an existing Wikipedia entry, in which case it would be good to add a new Wikidata item as well.  I think the behavior should be as follows:
* If used edits Wikipedia tag, auto add Wikidata tag
* If user simply views an object with Wikipedia but without Wikidata tag, show a bright red/yellow/suggestion icon to indicate that wikidata item CAN be added with a single click. It would also be good to show P31 (instance of) at all times, so that editor can verify that the wikipedia/wikidata item is correct.
* If wikidata and wikipedia tags mismatch, there should be a visual indication/warning as well

**Comment by pnorman** [comment] 2017-03-25 11:45
> show a bright red/yellow/suggestion icon to indicate that wikidata item CAN be added with a single click.

Isn't this just a warnings or popups to alert mappers about the missing tag?

**Comment by nyurik** [comment] 2017-03-25 16:27
@pnorman, not sure what you mean

**Comment by brierjon** [comment] 2017-03-25 17:16
> This is true - iD doesn't update existing tags. It only adds new wikidata tags when the user actually modifies the wikipedia field.

@bhousel This is an issue that the modification check is not working as expected in all cases of edits to the wikipedia tag and this wikidata entries are missing. Edits that do not use the dropdown for adding the wikipedia field, but only are a value change are missed from having a wikidata field appended with a value. The request is to make sure the wikidata automatic add function correctly handles the following two cases in addition to the dropdown.

The first situation I am experiencing is to get a wikidata entry for an existing Wikipedia field a user has to delete the existing correct Wikipedia entry to use the drop down to add the same entry again for the wikidata field to populate. 

The second situation is where a Wikipedia field exists, but the value is blank. Edits to this by adding a value do not populate a wikidata entry. This could be corrected with a check in ID for the edit or all objects with empty wikipedia fields should be removed from the objects. I'm not sure where the empty fields came from, but this is resulting in less complete data as ID does not auto populate a wikidata entry when a value is added.

ID should check if a field value was touched or query was made for the wikipedia lookup. If either of these cases occur then a wikidata entry should be attached. If this is the intended behavior it is not working in these cases. 

This issue is not a request for a silent update nor automated edits, but did include a related thought at the end which may have detracted from the main point and should be a separate feature suggestion. The QA features to prompt users to fix the erroneous data should be split into a separate issue to be addressed including the last two bullet points made by nyurik. Though they also could be another approach to addressing the issues highlighted above and would be valuable improvements to the ID QA functionality.

**Comment by bhousel** [comment] 2017-03-25 20:15
Sorry @brierjon I misread the intent of the original issue.. I'll reopen and we can discuss some more about what improvements we can make.

> Edits that do not use the dropdown for adding the wikipedia field, but only are a value change are missed from having a wikidata field appended with a value.

Yes, in the raw tag editor, whatever the user types is what gets saved.  iD doesn't do any extra processing on what the user inputs (aside from basic removal of whitespace and unprintable characters), and this is by design.  We expect that only advanced users who understand tags are using the raw tag editor.

> The first situation I am experiencing is to get a wikidata entry for an existing Wikipedia field a user has to delete the existing correct Wikipedia entry to use the drop down to add the same entry again for the wikidata field to populate.

Maybe we could add a display of the wikidata value below the wikipedia value and, if wikidata is missing, a button to allow the user to do a lookup.


> The second situation is where a Wikipedia field exists, but the value is blank. Edits to this by adding a value do not populate a wikidata entry. This could be corrected with a check in ID for the edit or all objects with empty wikipedia fields should be removed from the objects. I'm not sure where the empty fields came from, but this is resulting in less complete data as ID does not auto populate a wikidata entry when a value is added.

Ok, I just tried it and yes, this looks like a bug.  For a feature with an empty wikipedia value, I entered a wikipedia value, and it seemed to fill both wikipedia and wikidata tags, but upon leaving the feature and selecting it again, the wikidata value obviously didn't stick.

**Comment by brierjon** [comment] 2017-03-28 04:09
@bhouse The button solution for a missing wikipedia tag is simple and effective to correct the missing value and force a lookup. That and the correction to the behavior you confirmed we should be good.

When talking about displaying this button to generate a lookup in the "all fields" that sounds good. Following nyurik's suggestion I concur there needs to be color or other indicator that the value is missing and the button should be pushed. Once the wikidata value displays I'd recommend graying out the wikidata value and field so it can't be edited in the "all fields" view as it should be correct being generated from the wikipedia value.  While this still leaves editing possibility in the "all tags field".

Fixing the second part would solve the failure to stick wikidata issue.

As a complement to resovling the bad data with QA I put in a feature request in Osmose an issue for detecting and correcting objects missing either wikidata or wikipedia - [https://github.com/osm-fr/osmose-backend/issues/191](url)

**Comment by bhousel** [comment] 2017-06-23 18:14
There's a bunch going on here but the "bug" part of the lookup failing is #3987.

The rest of this issue is about letting the user know if wikidata is missing, letting them look it up, and considering adding special code to make wikidata lookup work in the raw tag editor.

**Comment by bhousel** [comment] 2017-10-02 12:29
moving to #4382

**Closed by bhousel** 2017-10-02 12:29 UTC
Labels: considering, field
