### ISSUE TITLE
can't upload changeset in google chrome 

### ISSUE THREAD

**Issue by Sirvanalie** [openstreetmap/iD#4311] opened 2017-09-05 05:20 UTC
I done 73 edit on my city , and now I want to save my changeset but I **can't uploaded** my changeset , upload button don't display in page, this is happen in google chrome.

**I upload below photo for show my problem.**

![capture](https://user-images.githubusercontent.com/13553285/30046487-5b7cfde8-9220-11e7-8778-6f8fe0c33125.PNG)

**Comment by tyrasd** [comment] 2017-09-05 12:45
That's odd. iD works on Chrome just fine for me. Which version of chrome do you use? Do you see any error messages displayed in the [javascript console](https://stackoverflow.com/a/5104475/1627467) after this happens?

**Comment by bhousel** [comment] 2017-09-06 01:43
I think this is a duplicate of #4108.. Let's leave both open, as this one is fresher and might still be traceable if @Sirvanalie can provide some specific details from the javascript console.. 

I do think there is a real bug in the commit ui code around where it is supposed to show the buttons.  It might be that the async OSM API call to fetch the user details failed?

**Comment by Sirvanalie** [comment] 2017-09-06 05:49
@tyrasd hi. This is my console. My google chrome version is 59.0.3070.115(Official Build) (64-bit).

![Uploading 12341.PNG…]()

**Comment by Sirvanalie** [comment] 2017-09-06 05:53
@tyrasd hi. This is my console. My google chrome Version 61.0.3163.79 (Official Build) (64-bit)

![12341](https://user-images.githubusercontent.com/13553285/30096396-6d505b5a-92ed-11e7-99dd-8fafd017fc4a.PNG)

**Comment by tyrasd** [comment] 2017-09-06 08:24
Thanks for the additional information. Looks indeed very much like the other issue on osm-help. Hmm, can you maybe try the "workaround" proposed in https://help.openstreetmap.org/questions/56164/save-button-disappeared/56626 and see if that one works for you, @Sirvanalie? Btw, do you remember editing [node/4727661429](http://www.openstreetmap.org/node/4727661429) (or anything in its vicinity) before this bug happened?

**Comment by Sirvanalie** [comment] 2017-09-07 05:53
@tyrasd dear I want to **save** my changeset , not to ignore them. I n help center they say :You must close the browser window, reopen, and choose not to restore. Then Save will work again. I don't want to delete my changeset. My problem is use this **73** changeset , NOT to ignore them 👎

**Comment by tyrasd** [comment] 2017-09-07 07:48
:question: I'm not sure whether I understand you correctly or not. But what I wanted you to try is the solution proposed by the user *GregRetro* on osm-help:

> FIX: Control-Z (or use the Undo button) for ALL of the changes that are cached in your session, until the Undo button is no longer lit. Then, CTRL-Y (or Redo) all of the changes over again. You may have to mash that button for quite a while... This will redo all of your edits in the current version of iD, and saving will be re-enabled.

(This procedure wouldn't get rid of your 73 changes.)

Does that not work for you?

**Comment by Sirvanalie** [comment] 2017-09-08 07:13
Thanks. I deleted my changeset :(. Now I should again to edit map . AND added oldest changeset .

**Comment by Sirvanalie** [comment] 2017-09-18 05:58
Thanks, finally its solved and I uploaded my changeset .

**Comment by tyrasd** [comment] 2017-09-18 09:57
> finally its solved

What did you do to solve the problem?

**Comment by Sirvanalie** [comment] 2017-09-19 05:58
Nothing, just after a few days, again I want upload my oldest changeset  without any hope for solved or not , but when open site and select Restore old changeset , I can uploaded .

**Comment by bhousel** [comment] 2017-09-19 11:15
Glad this is now working for you, @Sirvanalie 👍

**Closed by bhousel** 2017-09-19 11:15 UTC
Labels: bug
