### ISSUE TITLE
iD v3 alternative interface for beginners

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#6684] opened 2019-07-26 12:16 UTC
I've been following along with the amazing work by @quincylvania on the ribbon UI for v3. I think it will really speed up mapping for power users. I'm wondering though about how to continue to make iD accessible for new users. What we've really liked about the current iD interface is how simple it is for new users to pick up and learn. There are few buttons to select, and their function is easy to understand. In trainings of new users this has meant that it is much quicker than other tools for users to learn and start mapping. I think the ease-of-use is the result of a lot of thinking and design by several people, and in particular @bhousel who lays out their thoughts in https://github.com/openstreetmap/iD/issues/3123

I understand the needs of some users to speed up mapping, and how the new ribbon UI solves that challenge, but how can iD continue to serve beginners? Is there a way that v3 could incorporate both the v2 interface and the ribbon UI? Like a "beginner" and "advanced" mode? Maybe [generalizing iD](https://github.com/openstreetmap/iD/issues/6483) by splitting it into separate modules is the answer? I don't know the answers to these questions, and I know the ribbon UI is still in development so perhaps the focus should be on that and improving its accessibility for beginners. Hopefully this issue can serve as a place for production discussion about how to solve these issues.

**Comment by quincylvania** [comment] 2019-07-26 13:37
Thanks for bringing this up, @gmaclennan! The usability of iD for new and casual mappers has always been a top priority for us, including for the v3 release. I actually think the v3 ribbon is more approachable for beginners, so let me go into detail for anyone interested in this.

In v2.15 when you launch iD you see the basic Point/Line/Area buttons.

<img width="290" alt="Screen Shot 2019-07-26 at 8 53 36 AM" src="https://user-images.githubusercontent.com/2046746/61953057-6dd89d80-af83-11e9-9a68-df9361ddf76d.png">

Having just three options is simple, but the problem is that no one edits OpenStreetMap to add points, lines, or areas. People want to add restaurants, roads, and buildings. New mappers won't necessarily follow this abstraction or know which geometry to pick.

Contrast that with opening v3 for the first time:

<img width="755" alt="Screen Shot 2019-07-26 at 8 45 31 AM" src="https://user-images.githubusercontent.com/2046746/61953227-d9bb0600-af83-11e9-9587-de556617d085.png">

Just one button. When you want to add something you simply click it and search for what you want to add. All geometries are mixed, and if multiple geometries are allowed then you see options (I'd like to simplify this even further by having "preferred" geometries).

<img width="756" alt="Screen Shot 2019-07-26 at 8 47 36 AM" src="https://user-images.githubusercontent.com/2046746/61953374-361e2580-af84-11e9-8258-dd0053757771.png">

Here's the cool part. When you pick the preset you want, iD knows what you're drawing before you draw it. Thus we can guide new mappers by tailoring the UI with preset-specific instructions (#6119) as well as preventing invalid topologies like connecting power lines to rivers. None of that is possible with point/line/area buttons alone.

More buttons start appearing in the toolbar as a convenience only after you start adding things.

<img width="259" alt="Screen Shot 2019-07-26 at 8 49 12 AM" src="https://user-images.githubusercontent.com/2046746/61954195-4931f500-af86-11e9-84cb-451226d9ee32.png">

While the list can get much longer than three buttons, it grows organically via the user's own actions.

<img width="522" alt="Screen Shot 2019-07-26 at 9 18 45 AM" src="https://user-images.githubusercontent.com/2046746/61954283-84ccbf00-af86-11e9-8182-f11f3dc9db13.png">

As far as the other toolbars go, I admit that some have started to get crowded. This makes these commands more discoverable and mobile-friendly, but we'll have to see what people think in practice.

<img width="896" alt="Screen Shot 2019-07-26 at 9 23 42 AM" src="https://user-images.githubusercontent.com/2046746/61954615-2d7b1e80-af87-11e9-8410-29dbe79f01b7.png">

Overall, we've tried to make the v3 UI an upgrade for both new mappers and power mappers. We should keep this discussion going though. It's always useful to hear about places where iD should be more usable.

**Comment by quincylvania** [comment] 2019-07-31 19:15
Closing this since I'd really prefer not to have separate beginner and advanced modes. Instead I think we should continue to make iD as approachable as possible but still scalable to enable advanced workflows, as outlined above.

Please do open issues for any specific usability hurdles you find!

**Closed by quincylvania** 2019-07-31 19:15 UTC
Labels: usability
