### ISSUE TITLE
Selecting new Mapillary image does not show correct picture

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4560] opened 2017-11-23 19:50 UTC
When I selected one Mapillary image and then clicked the previous image of the track, the image didn't change. Also nothing happened when selecting other pictures.

![mapillary image stale](https://user-images.githubusercontent.com/31667811/33187101-a1131236-d08f-11e7-9336-0d6876ff79f8.gif)

**Comment by 1ec5** [comment] 2017-11-23 19:59
Duplicate of #4536.

**Closed by 1ec5** 2017-11-23 19:59 UTC
