### ISSUE TITLE
Ability to resize a selected area

### ISSUE THREAD

**Issue by Codain** [openstreetmap/iD#3372] opened 2016-08-22 17:06 UTC
When an area is selected, add the ability to resize the object.

This would be especially useful after pasting an area with the same shape but not the same size.

**Comment by bhousel** [comment] 2016-08-24 15:34
Well, I'll just copy and paste my other comment..

Yes, this is definitely possible. Transform/Resize is a tool that people are accustomed to seeing, from working with other vector drawing tools. This is not a priority for iD, but I'll leave this open as a "maybe someday".

**Comment by pnorman** [comment] 2016-08-25 22:12
Duplicate of #1793, implemented and rejected in #1802

**Comment by ianp5a** [comment] 2016-08-31 08:22
I have this need in the Missing Maps Project where we have thousands of houses that must be drawn. 
Many of these are rectangular. And have different sizes and proportions. 
We require:
**Scaling:** Enlargement or shrinking in all direction equally.
**Stretch:** Resize the selected object in a single direction.
This direction could be horizontal or vertical as you find in drawing and presentation programs.
But often a simple rectangle (house) that is at an angle, needs to be stretched along its own axis. 
Usually drawing programs display "handles" on the object, which can be dragged to define the amount.

**Comment by althio** [comment] 2016-08-31 09:11
@ianp5a There is work in progress for that I think https://github.com/openstreetmap/iD/pull/2699

**Comment by slhh** [comment] 2016-11-04 00:41
I don't see a real usecase of scaling existing objects, but in case of copying objects scaling could be useful. Some keys could have a special function in order to scale, rotate, or flip the copied object in the period between pressing Ctrl-V and placing the copied object by mouse click.

In case of a scale function for existing objects the risk of damaging data seems to be much higher than the benefit, but limiting it to the copy and paste process avoids the risk.

**Comment by Codain** [comment] 2016-11-05 09:33
Thank you all for your support on that one!

> I don't see a real usecase of scaling existing objects, but in case of copying objects scaling could be useful. 

Yes copying and pasting is one of the main reason to have this feature. Drawing a circle is cumbersome (even if it's already simplified), dupplicating an existing one and scaling it would be much more porwerfull (somes areas in the world have circular farm fields, storage tanks are often in groups but with various sizes...). 

> In case of a scale function for existing objects the risk of damaging data seems to be much higher than the benefit

Then do we also have to remove the translation ?! Between moving all nodes of a closed shape one by one and scaling the whole shape, I don't see any risk. On the contrary it will keep the overhaul shape consistent.

**Comment by 72ChevelleSS** [comment] 2019-05-13 12:09
Almost 3 years since this one was brought up. Any possibility of this being implemented for iD?

**Comment by quincylvania** [comment] 2019-05-13 13:38
@72ChevelleSS No active progress at the moment, but we'd like to add it eventually!

**Comment by quincylvania** [comment] 2020-09-21 14:43
We've continued to receive requests for this, particularly from HOT building mappers.

While a full scale/transform tool would be tricky to get right, I think we can start out with hotkeys. Advanced mappers can use them and everyone else can ignore them. While this doesn't serve non-keyboard mappers, something is better than nothing. 

Having done #7186 and #7976, we've developed a system where arrow keys are for panning, plus and minus are for zooming, holding <kbd>Shift</kbd> affects the selection instead of the map, and holding  <kbd>Alt</kbd> amplifies the effect. We can enable selection scaling by filling in the missing corner of the matrix.

|       | Arrow Keys | Plus/Minus Keys  |
| --- | --- | --- |
|  | Pan map | Zoom map |
| <kbd>**Alt**</kbd> | Pan map by a lot | Zoom map by a lot |
| <kbd>**Shift**</kbd> | Move selection | _*Scale selection_ |
| <kbd>**Shift**</kbd> **+** <kbd>**Alt**</kbd> | Move selection by a lot | _*Scale selection by a lot_ |

_*Proposed_

**Closed** 2020-09-21 18:47 UTC
Labels: new-feature, operation
