### ISSUE TITLE
wrong translation "Gangneung" to Korean 

### ISSUE THREAD

**Issue by ShinHayan** [openstreetmap/iD#8680] opened 2021-09-07 04:34 UTC
In Basic Map,  Gangneung is translated to 강릉. That's right.
But, in other Maps, Gangneung is translated to 가 ㅈ 릉.

Please fix it, Gang=> 강, Gan->간 
![gangneung](https://user-images.githubusercontent.com/7123912/132284725-fe69789d-8497-4c34-9792-c3e70f765f8e.PNG)

**Comment by matkoniecz** [comment] 2021-09-15 15:52
This appears to be about map data, not about iD editor.

The whole point of iD is that this data in OSM is editable using it.

Though if data is correct that is problem in this specific map style.

**Comment by LaoshuBaby** [comment] 2021-09-18 13:38
Hello, @ShinHayan 

The 2 city you draw in map maybe those 2 one

* [Gangneung-si](https://www.openstreetmap.org/relation/2537817#map=10/37.7805/128.9287)
<img src="https://user-images.githubusercontent.com/42690037/133890276-13b829f6-f9d4-4933-8d65-87018b73ef32.png" alt="图片" style="zoom: 33%;" />
The ```name``` and ```name:ko``` of it is ```강릉시``` in OSM database

* [Ganseong-eup](https://www.openstreetmap.org/relation/7578958#map=10/38.3181/128.5181)
<img src="https://user-images.githubusercontent.com/42690037/133890283-5405d3ca-f6b2-4f7c-b892-10d3e0e6ef3d.png" alt="图片" style="zoom:33%;" />
The ```name``` and ```name:ko``` of it is ```간성읍``` in OSM database

> In Basic Map, Gangneung is translated to 강릉. That's right.

Yes, Gangneung-si is using this 2 korean character in OSM database, database is using ```강릉시```

> Gang=> 강, Gan->간

Yes Gangneung-si currently using ```강``` in ```강릉시```, and Ganseong-eup using ```간``` in ```간성읍```

-------

So the database haven't have problem.

The problem is about different map layer's render technical details.

For Gangneung-si, the 6 map layer's render are at there

<img src="https://user-images.githubusercontent.com/42690037/133890433-2048e043-7b64-4ec3-bff5-f3c423232a03.png" alt="图片" style="zoom:67%;" />

For Ganseong-eup, the 6 map layer's render are at there

<img src="https://user-images.githubusercontent.com/42690037/133890508-31140f38-4fed-4dbf-b55d-14c57bd8e540.png" alt="图片" style="zoom:67%;" />

you can find only in those 2 map, "OpenCycleMap" and "Transport Map" have wrong render

[<img src="https://user-images.githubusercontent.com/42690037/133890538-e5fb238b-67b3-419a-8cfe-7820cc69fa3d.png" alt="图片" style="zoom:50%;" />](https://www.openstreetmap.org/#map=9/37.8944/128.4412&layers=T)  [<img src="https://user-images.githubusercontent.com/42690037/133890543-552dc331-65b7-4fb1-900c-62112f07a0b3.png" alt="图片" style="zoom:50%;" />](https://www.openstreetmap.org/#map=9/37.8889/128.3615&layers=C)

You can find that the source of those 2 style is Andy Allan, and website is  [https://www.thunderforest.com/](https://www.thunderforest.com/)

-------

So I search for this website, they are a tile provider and have different style.

This problem only find in thunderforest's tiles and all their tiles have this problem, even in this map style only for joke!

[<img src="https://user-images.githubusercontent.com/42690037/133890765-a309b5f0-fbf6-4f3f-b678-70bfba3ff82e.png" alt="图片" style="zoom:50%;" />](https://www.thunderforest.com/maps/spinal-map/)

--------

I sincerely suggest that you should go to contact this tile provider : support@thunderforest.com

[<img src="https://user-images.githubusercontent.com/42690037/133890771-4b27a65b-29f2-41f5-bbc5-9627fc2a17c8.png" alt="图片" style="zoom:33%;" />](https://www.thunderforest.com/contact/)

**Comment by gravitystorm** [comment] 2021-09-20 16:17
I can confirm that this is a problem with the fonts that we are currently using at Thunderforest, and I'm going to make some changes to fix this soon. But in the meantime this is not a problem with iD, so I'm going to close this issue.

**Closed as completed by gravitystorm** 2021-09-20 16:17 UTC
Labels: wontfix-not-iD
