### ISSUE TITLE
Visual Issue with Ways

### ISSUE THREAD

**Issue by telnettrauma** [openstreetmap/iD#8733] opened 2021-10-03 17:59 UTC
![10-03-13-57-30 3668-9](https://user-images.githubusercontent.com/50886841/135765804-a64c6fdf-461b-42a8-8b6d-88cee665a806.png)
![10-03-13-58-51 3669-C](https://user-images.githubusercontent.com/50886841/135765827-5963f7db-d92d-4a2b-a6a4-95cf8a6fa68d.png)
![10-03-13-59-13 3671-S](https://user-images.githubusercontent.com/50886841/135765828-0a9168d5-90e7-4931-9727-2b7e682998ac.gif)

I found this visual issue that seems to randomly appear. I have no idea how to recreate this issue, it happens at random. Dragging the map seems to fix it.

**Comment by bhousel** [comment] 2021-10-03 18:13
Yes, I've been seeing a lot of this too, both in iD and RapiD.  I'm pretty sure it's a rendering bug that showed up in Chrome 94.

(I tagged it as a wontfix, because I don't think it's an iD issue, but we can keep the issue open until we know what it is).

**Comment by k-yle** [comment] 2021-10-04 00:41
@bhousel do you think this is related to the fact that icons are occasionally rotated by 90deg, or is that a separate bug?
![a](https://user-images.githubusercontent.com/16009897/135779142-31faac45-652d-45ca-9366-9659d213fe30.png)

**Comment by bhousel** [comment] 2021-10-04 14:43
> @bhousel do you think this is related to the fact that icons are occasionally rotated by 90deg, or is that a separate bug?

I don't know -  I haven't seen that icon rotation bug yet 😆 
They're really different places in the code, so my gut says the issues are not related.

**Comment by Adamant36** [comment] 2021-10-05 16:44
I'm having a similar problem with green areas randomly showing up in the editor. I can't reproduce it in Firefox though. So it's pretty likely that Chrome is the culprit. 

https://www.openstreetmap.org/#map=17/39.06914/-122.17400

![Screenshot 2021-10-05 093632](https://user-images.githubusercontent.com/30259065/136066341-ab172c14-0d74-4309-86a3-ceb73d6574f5.png)

**Comment by bhousel** [comment] 2021-10-14 18:33
This issue goes away if you uncheck the "hardware acceleration" setting in Chrome:
<img width="723" alt="Screen Shot 2021-10-14 at 2 30 59 PM" src="https://user-images.githubusercontent.com/38784/137375567-28bc3258-6e2c-4ba1-aac3-1add218c3122.png">

This makes sense, since it the artifact looks like a bug in their pixel shader.

**Comment by bhousel** [comment] 2021-10-14 19:25
More info, these issues are present on both Chrome and Edge, so it's something to do with the Blink rendering engine.

The rotated icon (use path) appears to be this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1257978

I can't find an open issue for the road fading effect, so I opened one here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1260092

**Comment by bhousel** [comment] 2021-12-02 18:16
I'm closing this as it seems that the fix made it into Chrome 96.

**Closed as completed by bhousel** 2021-12-02 18:16 UTC
Labels: wontfix-not-iD
