### ISSUE TITLE
Navitation to relation members

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4882] opened 2018-03-13 22:03 UTC
It would be nice to have a possibility to navigate to any member of the currently selected relation.
E.g. you have a boundary relation with outer/inner and label members selected. You click on the label member and press some button to pan the map to it.

**Comment by bhousel** [comment] 2018-03-14 01:42
This is a duplicate of #3604

**Closed by bhousel** 2018-03-14 01:42 UTC
