### ISSUE TITLE
Fix highway=track

### ISSUE THREAD

**Issue by lxbarth** [openstreetmap/iD#2615] opened 2015-04-29 20:56 UTC
Ongoing Nepal mapping highlights the massive confusion around `highway=track`. 

> This tag represents roads for mostly agricultural use, forest tracks etc.; usually unpaved (unsealed) but may occasionally apply to paved tracks as well, that are suitable for two-track vehicles, such as tractors or jeeps.

[![screen shot 2015-04-29 at 4 54 56 pm](https://cloud.githubusercontent.com/assets/98233/7401238/8f464d9a-ee90-11e4-9cdf-697cb769ce54.png)](http://www.openstreetmap.org/#map=17/28.00016/84.62408
)

http://www.openstreetmap.org/#map=17/28.00016/84.62408

Can we call track "agricultural track"?

**Comment by jfirebaugh** [comment] 2015-04-29 21:01
What exactly is the confusion?

**Comment by bhousel** [comment] 2015-04-30 03:30
@lxbarth since the time you posted that, it looks like they have all been changed to "unclassified road"?

The HOT tasking manager does contain pretty detailed instructions on how to tag different roads, so I'm not sure how renaming Track to something else helps here.

**Comment by pnorman** [comment] 2015-04-30 04:06
> Can we call track "agricultural track"?

They're not purely agricultural - see forest tracks.

**Comment by lxbarth** [comment] 2015-04-30 18:25
> What exactly is the confusion?

All across OpenStreetMap and in the particular example above, dirt roads are tagged `highway=track` where they should be tagged `surface=unpaved` together with the appropriate road classification. `highway=track` is reserved for roads for agricultural or similar use.

> Do not use tracks to represent public unpaved roads in built-up areas [1], that would be considered tagging for the renderer. In this situation, classify them as usual according to the conventions in your country, and also provide a surface=* tag.

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack

**Comment by brycenesbitt** [comment] 2015-05-01 08:04
In the USA they are definitely not "agricultural track".
Many residential roads and hiking routes are marked highway=track.
The highway tag is a mess unfortunately.

**Comment by pmailkeey** [comment] 2015-05-09 14:47
Totally agree with you Bryce, the highway tag is a complete mess and I take it, it's the core of OSM.

lxbarth - tag the roads in Nepal as you think fit and is appropriate. Get a consensus among all Nepal map editors.

**Comment by RicoElectrico** [comment] 2015-05-16 08:27
This is a problem that really annoys me, frankly. It's more about tagging for the renderer and possibly bad translation. You would have to check specific locale of the user who added it. (which is possible from some time as locale is tagged in the changeset). 
I intentionally changed Polish translation to "droga polna lub leśna" (field or forest road) as people did in fact use track incorrectly and there is no direct translation for track ("droga gruntowa" means roughly unpaved road).
As per TFTR, please visit https://github.com/gravitystorm/openstreetmap-carto/issues/110 as some people acknowledge this is a shortcoming of the renderer.

**Comment by sebastian-philipp** [comment] 2015-05-21 11:59
This may also be caused by the HOT OSM tasking manager, which says in the instructions for e.g. [#1047](http://tasks.hotosm.org/project/1047) :

> highway=track Unpaved motorable tracks

IMO the  tasking manager should be consistent with the Wiki page. 

Btw, the German term for ```highway=track``` is "Waldweg / Feldweg" which can be roughly translated as "forest way / field way", which fits pretty good for this preset.

**Comment by brycenesbitt** [comment] 2015-05-21 18:50
Well... the American West uses highway=track for any dirt road a vehicle
can travel on, even if it's closed to vehicles.
It slots below highway=residential in priority.

**Comment by brianreavis** [comment] 2015-05-22 20:34
> Well... the American West uses highway=track for any dirt road a vehicle
can travel on, even if it's closed to vehicles.
It slots below highway=residential in priority.

@brycenesbitt I think I know what you're saying, but just want to comment that I've seen this applied a bit too liberally in places. Tracks are (to me) roads with two distinct tracks. Old forest service roads, old mining roads, tiny roads paralleling powerlines through sagebrush (although this could be ambiguous with service roads), and so on. Roads like this aren't tracks, are they?

![screen shot 2015-05-22 at 2 23 38 pm](https://cloud.githubusercontent.com/assets/118480/7779037/3a7778d8-008e-11e5-9427-c71283bb3dfa.png)

**Comment by pmailkeey** [comment] 2015-05-22 23:01
If something has done the same route as you're following, they have left a track. ALL routes except those where there's no track are tracks. There are animal tracks, pedestrian tracks and vehicular tracks (there are more but we're not likely interested in those).

There are at least 2 ways to look at the problem; locally and globally. Locally is good as it fits in with local descriptions. Globally is good as it displays comparability between countries.

OSM will need to decide what the solution is - but sadly is ill-equipped to make that decision.

**Comment by brycenesbitt** [comment] 2015-05-22 23:14
The image above I'd map as a highway=track / surface=dirt|gravel in the
western USA.

What I don't know how to map well is the difference between a pedestrian
walkway and a hiking track,
and between a dirt road for standard vehicles and a narrow track ATV road.

**Comment by pmailkeey** [comment] 2015-05-22 23:38
walkway,sidewalk & man-made = footpath.
Hiking over natural terrain = 'path' - that's what I've gone for.

As for the tracks, they may be the same type but need further detail like surface=

**Comment by brianreavis** [comment] 2015-05-23 00:26
@brycenesbitt I would not call that a track – it's a maintained/grated gravel road with washboards connecting parts of an oilfield. What would you call this? (I would consider this a `highway=track`)

![screen shot 2015-05-22 at 2 17 47 pm](https://cloud.githubusercontent.com/assets/118480/7781633/a4e8c840-00af-11e5-9a48-73fb7f556744.png)

**Comment by brycenesbitt** [comment] 2015-05-23 01:42
The whole scheme is buggered.
The right answer in a given area depends on what's already nearby.

I'd tag both of those as tracks.

**Comment by bhousel** [comment] 2015-05-23 02:10
OK let's talk about `highway=track`.  Most mappers seem pretty confused about this tag, but I know lots about these because I run trail ultramarathons.  I have probably run 100s of miles on roads like these. 

They are often just 2 ruts, but can be paved, pebbles, asphalt, dirt, or anything in between.  They generally don't have names (but some do).  There is a "track" near me that was a street with a name that was paved 50 years ago and went to a missile silo.  It is now behind locked gates, deteriorated and the woods has taken it over.

What I'm saying is:  you can not tell from looking at a single imagery tile if it is a `highway=track` or something else.  You need context. 

Here's the difference:
When it snows, when bridges go out, when trees fall across it, etc etc - does someone need to plow/clear/repair ASAP because somebody lives there and needs to get home or get their mail delivered?  Or is it a "we will get around to it whenever, or wait until spring or next year" sort of situation?   The latter are `highway=track`.  

Tracks are defined by 2 things:  *A vehicle can sometimes drive along it, and it is not used for anything urgent.*   

I only map `highway=track` from aerial imagery if it is clearly heading out into a farmyard or through a wooded area not near any buildings.  Anything else gets `highway=residential` or `highway=unclassified` if I really can't tell.

Anyway.. I'm closing this issue, as it's not something wrong with iD and renaming "Track" to something else would just make the situation more confusing.  Educating mappers is the solution, and maybe improvements to the [wiki page](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack) too.

**Closed by bhousel** 2015-05-23 02:10 UTC

**Comment by brianreavis** [comment] 2015-05-23 03:56
@bhousel The underlying point here is that there are way too many personal/convoluted definitions of what the things are. Educating mappers *is* the solution – but I'd argue this education should happen in iD. Many people use the descriptions of the types in iD as reference when making edits. Honing them a bit could help a bunch

**Comment by bhousel** [comment] 2015-05-26 18:09
@brianreavis I have changed slightly the wiki page for `highway=track`,  to say "Infrequently maintained minor roads for agricultural and forestry use etc."  This is the help text that is also shown in iD.

I think the HOT Task Manager should be updated also, but this is not something I can do.  For [Task #1018](http://tasks.hotosm.org/project/1018) it currently says "highway=track Unpaved motorable tracks" which is probably the source of some of the confusion.
