### ISSUE TITLE
[BUG] funny behaviour when connecting rail and road

### ISSUE THREAD

**Issue by sevku** [openstreetmap/iD#8682] opened 2021-09-08 09:53 UTC
Please feel free to update the title, idk how to describe this exactly.

![out](https://user-images.githubusercontent.com/23403917/132488122-b7f55bf8-bc5b-416d-a085-05da83d111bf.gif)

**Comment by bhousel** [comment] 2021-09-09 13:56
I believe #8663 fixes this.. Can you test in [RapiD](https://mapwith.ai/rapid) and see whether the issue is there?

**Comment by sevku** [comment] 2021-09-09 16:51
> I believe #8663 fixes this.. Can you test in [RapiD](https://mapwith.ai/rapid) and see whether the issue is there?

Certainly much better

**Comment by cicku** [comment] 2021-09-11 05:05
This is one of the many issues from 2.20.1…

another one seems to be caused by the same: when connecting a marked crossing with divided highways (x2), there is a 50/50 chance you will see 2 intersection nodes, a separate node next to the correct intersection node.

**Comment by mbrzakovic** [comment] 2021-09-14 13:08
Should be fixed now. Please double check if you can repro issues on dev endpoint now. https://ideditor.netlify.app/

**Closed as completed by mbrzakovic** 2021-09-14 13:08 UTC
