### ISSUE TITLE
Maxar (Premium) is not Maxar's Premium layer

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#8852] opened 2021-12-13 18:45 UTC
The layer in iD listed as 'Maxar Premium Imagery' seems to be using the layer that JOSM calls Maxar Standard Imagery, which has older imagery than a different layer that JOSM has as 'Maxar Premium Imagery'.

The following vintage layers seem to match JOSM's 'Premium' and 'Standard' layers respectively, and the second also seems to match iD's Premium.

<img src="https://user-images.githubusercontent.com/25139386/145869217-c238bdd3-404a-4948-b37b-8edbfe846a00.png" width=600>

<img src="https://user-images.githubusercontent.com/25139386/145869219-440d7510-857f-4e39-9e45-da6d9ef7f6df.png" width=600>

**Comment by tordans** [comment] 2021-12-13 21:08
Offtopic @rivermont: What is the URLs to those date visualizations?

**Comment by mvexel** [comment] 2021-12-14 15:21
@tordans (copying from Slack) 

>  https://discover.digitalglobe.com: filter by Type-Mosaic and Line-Vivid Standard, the two results seem to be what JOSM has, at least for the area I checked

**Comment by Mahabarata** [comment] 2022-01-14 00:31
see also [#1217](https://github.com/osmlab/editor-layer-index/issues/1217#issuecomment-907634207) and my next comment on 6 Nov 2021.

**Comment by maGIScian** [comment] 2022-02-01 20:41
I stopped eating my sausages and mash and drinking my beer to add to this.  That's how serious it is.  Validators are validating tasks mapped in standard, practically remapping everything.  This is happening in our projects in Mozambique and some areas of DRC...

**Comment by Jorieke** [comment] 2022-02-01 20:45
Yes, despite the beer and sausages of @maGIScian he is right, we are encountering the same issue with for example some of our mapping projects in Mozambique. In JOSM there is no issue, you have like usually the Maxar Standard layer and the Maxar Premium layer. It is only in ID that this is an problem. In ID you have listed Maxar Premium in the background layers, but it is thus actually Maxar Standard imagery. 

It looks thus that it is an issue with ID, because JOSM can do it, so I guess ID must be able to do it too?

**Comment by maGIScian** [comment] 2022-02-01 20:47
See some background information on how this affects us at https://hotosm.slack.com/archives/C4GLC45PY/p1642582282025900

**Comment by tyrasd** [comment] 2022-02-02 08:54
Hey all. I'm really sorry that resolving this takes longer than anticipated.

The problem is that Maxar communicated to us (@mbrzakovic) that the "Maxar Premium" layer in iD actually corresponds to the "Maxar Premium" product. I didn't want to change the layers without confirmation from Maxar, that there was indeed a mixup of the two products. Unfortunately, we didn't hear back from them when we asked for clarification shortly after this issue was raised here.

> In ID you have listed Maxar Premium in the background layers, but it is thus actually Maxar Standard imagery.

Can you please tell me how you came this this conclusion? I didn't find a way to definitely rule out the (unlikely) possibility that the layer is correct in iD and just reversed on JOSM's side.

**Comment by maGIScian** [comment] 2022-02-02 08:58
Hi Martin, I'd be happy to have a call with you to demonstrate how we came to this conclusion and how it affects us.  Please email me: andries.heyns@london.msf.org and we can set up a call, even today.  It's a serious issue and definitely not Premium everywhere as they say.

**Comment by Jorieke** [comment] 2022-02-02 09:07
@tyrasd many thanks for looking into this!!

**Comment by tyrasd** [comment] 2022-02-08 17:46
This was now fixed by Maxar. :tada: The iD profile should now return the most recent Maxar imagery (like in JOSM). PS: I noticed that in some locations the servers still have a few of the old tiles cached, but that should resolve itself relatively soon.

**Closed as completed by tyrasd** 2022-02-08 17:46 UTC
Labels: bug, question, priority

**Comment by rivermont** [comment] 2022-02-08 19:05
Can confirm that the area I had compared seems to have the newer stuff now!

**Comment by maGIScian** [comment] 2022-02-08 19:33
Yassssssssss thank you!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jorieke** [comment] 2022-02-09 08:37
Yesss,  it seems to work fine now!! 
Many thanks Martin and Maxar!!

**Comment by pedrito1414** [comment] 2022-02-09 10:56
Echoing thanks on resolving this!
