### ISSUE TITLE
Missing traffic signs in Mapillary traffic sign layer

### ISSUE THREAD

**Issue by eneerhut** [openstreetmap/iD#6721] opened 2019-08-05 08:34 UTC
iD Editor is not showing all the traffic signs that Mapillary has identified in given area.

Here you can see the same location on Mapillary, JOSM, and iD Editor.

**Mapillary**
![image (4)](https://user-images.githubusercontent.com/11349863/62450182-2c2fca00-b7af-11e9-948e-2cff3041ab03.png)

**JOSM**
![image (6)](https://user-images.githubusercontent.com/11349863/62450238-4d90b600-b7af-11e9-875b-cd4ba7b3d580.png)

**iD Editor**
![image (5)](https://user-images.githubusercontent.com/11349863/62450245-508ba680-b7af-11e9-8968-2dd6e341985f.png)

@ptpt has looked into the issue and summarised the following:

> 
> There are more than 1000 features in the bbox, so the rest features are truncated. I can see iD tries to paginate by page=1,2,3,4 but it’s wrong; it should follow the next url in the link header.
> 
> ELVA is using the vector tile paramter. When you zoom in you get smaller bbox in the request, so you see all features (edited) 
> 
> Here is API call in ELVA: https://a.mapillary.com/v3/map_features?tile=14/8783/5133&client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&layers=trafficsigns&per_page=1000

**Comment by cbeddow** [comment] 2019-08-05 21:49
I think this might be related to a variable in the iD code called `limit`. I am not sure exactly what this function is doing: https://github.com/openstreetmap/iD/blob/master/modules/services/mapillary.js#L233-L244

I see it's used here:

```
signs: function(projection) {
        var limit = 5;
        return searchLimited(limit, projection, _mlyCache.map_features.rtree);
    },
```

That aside, I think it's just that the pagination is wrong. I think @nickplesha may have added that originally somewhere here but not sure where it is being used now: https://github.com/openstreetmap/iD/blob/master/modules/services/mapillary.js#L202

I have some sample code for Mapillary pagination here:

```
function getNext(next_url) {
  $.ajax({
      dataType: "json",
      url: next_url,
      async: false,
      success: function(next_points, status, xhr) {
        console.log('fetching next page: ' + next_url);
        if (typeof next_points !== 'undefined' && next_points['features'].length > 0) {
          var next_features = next_points.features;
          for (f=0;f<next_features.length;f++) {
            output['features'].push(next_features[f]);
            report.innerHTML = 'Retrieving items...';
          }
          if (next_features.length == 1000) {
            paginate(xhr);
            report.innerHTML = 'Retrieving items... (' + output['features'].length + ' so far)';
          }
        }
      }
  });
}

function paginate(xhr) {
  var link = xhr.getResponseHeader('Link')
  let arrLink = link.split("link:");
  link = arrLink.length == 2? arrLink[1]: link;
  let parsed_link = {}
  arrLink= link.split(",");;
  for (l of arrLink){
      linkInfo = /<([^>]+)>;\s+rel="([^"]+)"/ig.exec(l)
      parsed_link[linkInfo[2]]=linkInfo[1]
  }
  if (typeof parsed_link['next'] !== 'undefined' && output['features'].length < limit) {
    var next_url = parsed_link['next'];
    getNext(next_url);
  }
  else if (typeof parsed_link['next'] == 'undefined') {
    console.log('no more detections');
  }
  else if (output['features'].length > limit) {
    alert('try a smaller area, too many detections');
  }
}
```

**Comment by quincylvania** [comment] 2019-09-24 07:46
Closing as duplicate of #6510

**Closed by quincylvania** 2019-09-24 07:46 UTC
Labels: bug
