### ISSUE TITLE
Surface drop-down menu spontaneously disappears

### ISSUE THREAD

**Issue by bborkmiller** [openstreetmap/iD#5035] opened 2018-05-14 12:27 UTC
The Surface drop-down on ways has an issue where it disappears a second or so after having clicked on it. The sequence is: Click on a way; click on the surface drop down; menu appears, then disappears quickly. After a second click, it will stay open:

![surface](https://user-images.githubusercontent.com/5290258/39997185-02c4b344-5750-11e8-9d39-2a27e7951c9d.gif)

I've noticed this in Safari on OS X and Chrome on Windows.

**Comment by dnguneratne** [comment] 2018-10-22 18:32
The first click runs a search on the combo box as if you were to type. The reason it appears to close in this case is because there's nothing else that matches 'compacted'. If there is a matching word it'll show up:

![on_click_search](https://user-images.githubusercontent.com/8231763/47311019-b46d2600-d606-11e8-820f-55bc407c1542.png)

@bhousel I am not sure if this is intended behavior. If you'd like to change it I'd like to work on this. If you do want to change it, do you have any tips on what causes the search to happen or where to get started?

**Comment by bhousel** [comment] 2018-12-13 05:18
I did a bunch of recent fixes to things in the dropdown control and this seems to be fixed now..

**Closed by bhousel** 2018-12-13 05:18 UTC
Labels: bug, help wanted
