### ISSUE TITLE
make `f` shortcut smarter

### ISSUE THREAD

**Issue by verhovsky** [openstreetmap/iD#10155] opened 2024-03-11 21:03 UTC
It is obvious which way I want to continue my white line

<img width="237" alt="Screenshot 2024-03-11 at 13 46 44" src="https://github.com/openstreetmap/iD/assets/5687998/7390ba11-4663-4ab8-a305-3c8f3ecc35f6">

Instead of requiring two points all the time and throwing a "This feature can't follow another feature because it isn't connected to enough consecutive points along another feature. Add another point manually to continue." error otherwise, when there's just one line I want to follow, `F` should calculate the angles of the intersecting points and pick the largest of the two. Statistically speaking, I'm sure that acute angles are probably less than 1% of all line angles in OSM. Making a mistake will 1% of the time will be more useful than just refusing to do anything at all. As long as it's predictable, people will quickly learn that it takes the largest angle and add the second point when it's actually needed.

Secondly, it's annoying when I've pressed `F` 10+ times on one line, then I get to a point where there's an offshoot of the line and it doesn't know where I want to go. I want to continue following the line that I've followed on the last press.

**Comment by 1ec5** [comment] 2024-03-12 15:24
> Secondly, it's annoying when I've pressed F 10+ times on one line, then I get to a point where there's an offshoot of the line and it doesn't know where I want to go. I want to continue following the line that I've followed on the last press.

#8750 would probably address this case, since the way you intended to follow is probably still selected for the purpose of vertex navigation.

**Comment by 1ec5** [comment] 2024-10-15 20:24
Duplicate of #8750

**Closed as not planned by 1ec5** 2024-10-15 20:24 UTC
