### ISSUE TITLE
Index imagery for Maxar

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#9147] opened 2022-06-04 16:09 UTC
### Description

Hi,

in transifex, we have almost all the imageries (name and description) but not Maxar Premium Imagery : could you add it ?

I had open an issue on editor-layer-index [#1451](https://github.com/osmlab/editor-layer-index/issues/1451) but it seems it is not the good place, I hope it is the good one here.

Best regards

### Screenshots

see this capture
![Capture d’écran 2022-03-12 125237](https://user-images.githubusercontent.com/3121119/158025094-63049ca7-ef0c-4f7a-be3d-111a16ed8ad9.png)

The first line is not in polish or english but in french because in transifex you have added the original text so we can translate it.
Same thing for the 2d, 3rd, 4th, 6th, 7th, 8th... in fact all the lines are not the original ones but a translation.

Except the line 5 (Maxar Premium Imagery) : the text is the original because the text is not in transifex so impossible to translate it.

Same thing with the texts under the mouse :
* for the first line, we have a translation :
![Capture d’écran 2022-03-12 130732](https://user-images.githubusercontent.com/3121119/158025675-85c6c881-3655-46ef-a6ba-beb29ef2a87f.png)

* same thing for the line 4 :
![Capture d’écran 2022-03-12 130754](https://user-images.githubusercontent.com/3121119/158025680-5263082c-9852-4947-a6f8-4a69c1a108de.png)

* same thing for the other lines

* but not for Maxar, the test is in english, not in transifex so impossible to translate it.
![Capture d’écran 2022-03-12 130848](https://user-images.githubusercontent.com/3121119/158025689-b7f26c8f-4187-42b2-a1dd-c342e31a8c5c.png)

My asking is to be able to translate the 3 texts about Maxar (name, description and attribution) like for all other lines.

**Comment by 1ec5** [comment] 2023-04-26 19:06
The string is currently hardcoded here:

https://github.com/openstreetmap/iD/blob/5f92841a8ee5bb371a7f3898725493a97aa5adca/data/manual_imagery.json#L4

This code looks like it tries to make the string localizable through Transifex:

https://github.com/openstreetmap/iD/blob/a15f6ff338dd7b1a1e64b90574afba0d67be96ce/scripts/build_data.js#L218

Not sure why it isn’t being exposed in the UI.

**Comment by Mahabarata** [comment] 2023-04-29 18:04
When I look at the line 236 in the build_data, the result of the writeEnJson function is written in the file en.min.json.

But in the directory iD/dist/[locales](https://github.com/openstreetmap/iD/tree/5f92841a8ee5bb371a7f3898725493a97aa5adca/dist/locales), the file is not present so I cannot look at it to see if imagery.Maxar is present (probably not).

Where is this file ?

**Comment by tyrasd** [comment] 2023-07-07 12:16
This is duplicate of #7724.

**Closed as not planned by tyrasd** 2023-07-07 12:16 UTC
Labels: localization, duplicate
