### ISSUE TITLE
Separating area

### ISSUE THREAD

**Issue by Alignitems** [openstreetmap/iD#9251] opened 2022-08-19 11:45 UTC
### I want...
the feature to separate area(or building)
### How does that work?
1. Select area that I want to separate
2. Click right mouse button(open menu)
3. Click 'Saparate building'(you can change the name) menu on the list
4. Input number(how many to separate)
5. Bam!
### Why I want this feature
In current version of ID editor, it's hard to separate areas like parking spaces.

+ Check it out [this](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Terracer) JOSM plugin!

**Comment by Dimitar5555** [comment] 2022-08-19 16:40
It is currently possible to separate areas. The thing that you are looking for is gridifying.

**Comment by danieldegroot2** [comment] 2022-08-19 22:23
@tyrasd Duplicate of #6988 .

**Comment by Curogrammer** [comment] 2022-08-23 05:30
Oh, I found a [https://kyle.kiwi/iD](fork of iD) that supports the feature!

**Comment by Curogrammer** [comment] 2022-08-23 05:31
Please close this issue.

**Comment by tordans** [comment] 2022-08-23 08:12
@Curogrammer can you share how to do this operation in https://kyle.kiwi/iD – I did not find it…

**Comment by Dimitar5555** [comment] 2022-08-24 07:10
1. Create a rectangle
2. Right click on it
3. Choose the second action from top to bottom (it has the same icon as the square tool)

**Comment by Alignitems** [comment] 2022-08-24 08:18
@Dimitar5555 Yeah that's right
+ Warning: do not turn off the red button thing. It will not road the osm data.

**Comment by 1ec5** [comment] 2022-08-24 09:16
> Oh, I found a [https://kyle.kiwi/iD](fork of iD) that supports the feature!

This is a demo @k-yle made for #9020. Please leave your feedback on that PR.

**Comment by 1ec5** [comment] 2022-08-24 09:16
Closing as a duplicate of #6988.

**Closed as not planned by 1ec5** 2022-08-24 09:16 UTC
