### ISSUE TITLE
Delete construction=* after choosing normal highway

### ISSUE THREAD

**Issue by CharlesMaZ** [openstreetmap/iD#8886] opened 2022-01-07 23:25 UTC
### URL

https://www.openstreetmap.org/edit

### How to reproduce the issue?

When in OSM there is a road in construction (highway = construction), but when the construction is finished and we change it to the normal road by choosing from templates, e.g. "Primary Road", then the tag "construction = * " remains. This blocks routings.
1. 
![image](https://user-images.githubusercontent.com/29873995/148619492-cd668ca9-3a42-4f1f-b3da-9f9a1045d359.png)
2.
![image](https://user-images.githubusercontent.com/29873995/148619558-5105b085-fee0-4dcc-afca-cfe089f4931a.png)
3.
![image](https://user-images.githubusercontent.com/29873995/148619583-bdb216d5-b6ce-4f7a-9717-16b615a64595.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by riQQ** [comment] 2022-01-08 09:47
Seems to be a duplicate of #8877.

**Closed as completed** 2022-05-12 08:32 UTC
Labels: duplicate
