### ISSUE TITLE
Entity not found

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#4094] opened 2017-06-08 05:29 UTC
Hi.
There is some errors in https://www.openstreetmap.org/edit#map=17/43.04349/131.82870.

```
Uncaught Error: entity w25656821 not found
    at rd.entity (id-31f62d9….js:61)
    at rd.parentWays (id-31f62d9….js:61)
    at t (id-31f62d9….js:4)
    at Object.Cd.i.rebase (id-31f62d9….js:4)
    at Object.merge (id-31f62d9….js:13)
    at n (id-31f62d9….js:14)
    at o (id-31f62d9….js:14)
    at id-31f62d9….js:63
    at t (id-31f62d9….js:63)
    at l (id-31f62d9….js:63)
Uncaught Error: entity w25656821 not found
    at rd.entity (id-31f62d9….js:61)
    at rd.parentWays (id-31f62d9….js:61)
    at t (id-31f62d9….js:4)
    at Object.Cd.i.rebase (id-31f62d9….js:4)
    at Object.merge (id-31f62d9….js:13)
    at n (id-31f62d9….js:14)
    at o (id-31f62d9….js:14)
    at id-31f62d9….js:63
    at t (id-31f62d9….js:63)
    at l (id-31f62d9….js:63)
id-31f62d9….js:61 Uncaught Error: entity w176022858 not found
    at rd.entity (id-31f62d9….js:61)
    at rd.parentWays (id-31f62d9….js:61)
    at t (id-31f62d9….js:4)
    at Object.Cd.i.rebase (id-31f62d9….js:4)
    at Object.merge (id-31f62d9….js:13)
    at n (id-31f62d9….js:14)
    at o (id-31f62d9….js:14)
    at id-31f62d9….js:63
    at t (id-31f62d9….js:63)
    at l (id-31f62d9….js:63)
```

Chrome 59.0.3071.86 x64 Ubuntu
No errors in Firefox 53.0.3 (64-bit)
No errors in Windows

**Comment by tyrasd** [comment] 2017-06-08 07:57
duplicate of #3973

**Closed by tyrasd** 2017-06-08 07:57 UTC
