### ISSUE TITLE
Add a confirmation dialog to the L keyboard shortcut

### ISSUE THREAD

**Issue by nighto** [openstreetmap/iD#8534] opened 2021-06-09 10:52 UTC
The keyboard shortcut `L` is assigned to finding your location (which might take some time) and then moving the visible viewport to that position. Sometimes when you are typing tags on the keyboard you might miss the `TAB` and if you type `L`, then the editor would be stuck into determining your position for a while then jump for a position different from the one you are editing. So it would be great to add a confirmation dialog, or another measure such as disabling the shortcut for a little bit after filing tags manually to avoid such hassle.

**Comment by 1ec5** [comment] 2021-06-12 00:23
Duplicate of #8474; see that issue for workarounds in the meantime.

**Closed as completed by 1ec5** 2021-06-12 00:23 UTC
