### ISSUE TITLE
Names of relations that something is part of are not displayed

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#10103] opened 2024-02-10 12:20 UTC
### How to reproduce the issue?

Navigate to https://www.openstreetmap.org/#map=20/52.51881/-2.07390
Edit in iD
Note that the top route name isn't displayed.
There appears to be no action that I can take to display it.
I need to know the full name because iD hides useful information about the relation (it's object iD) so when adding other things to it (such as to fill in the gap here) I need to use a "best guess" based on other attributes that iD does let me see, such as the name.
Unfortunately the name is truncated.

### Screenshot(s) or anything else?

![Screenshot_20240210_121413](https://github.com/openstreetmap/iD/assets/5311740/b96ae10f-7282-4d85-b21f-0428001b4d5c)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment] 2024-02-10 17:16
> Note that the top route name isn't displayed.

Can you clarify? Are you referring to the line that reads, “National Cycle Network National…”? This sounds a lot like #8313. You can resize the sidebar to see more of the relation’s label, though there really should be a tooltip here so you don’t have to.

Each of the bus route labels seen here would be cleaner if its `network` were to match a name-suggestion-index entry. Then it would say just “**West Midlands Bus** 11A”. osmlab/name-suggestion-index#4768 tracks adding highway route networks to NSI; cycling route networks would probably be a part of that effort.

**Comment by SomeoneElseOSM** [comment] 2024-02-14 22:19
Re the comment here, just to confirm, there is no tooltip showing details of relations.  There is no visual indicator showing that the panes on the screen can be dragged left and right, and if I do drag the window far enough to the right to see the full name (a) there's not much of the rest of the screen left and (b) it's still a bit esoteric because iD refuses to show the relation iD.

![Screenshot_20240214_221707](https://github.com/openstreetmap/iD/assets/5311740/1e476dca-f158-4fb0-a3b8-c9fdfc385292)

**Comment by 1ec5** [comment] 2024-02-14 22:29
Noted. I’m considering tagging this issue as a duplicate of #8313, since it covers the same usability issue. At a glance, I would expect implementing a tooltip to be quite straightforward, and it could even contain a relation ID for disambiguation purposes.

Meanwhile, getting this and other local bus companies into NSI would be another good next step, with benefits besides disambiguation. Someone with more local knowledge about how the various bus companies in this region are branded and structured would be in a good position to file an issue in that repository.

**Comment by SomeoneElseOSM** [comment] 2024-02-14 23:21
> duplicate of https://github.com/openstreetmap/iD/issues/8313,

Yes, it sounds like the same basic issue.

A tooltop would be better than nothing (why not just optionally display the relation number on screen?)  If iD is supposed to be useful beyond "someone's first three weeks in OSM" it seems essential to introduce them to object iDs - using the browse pages on the main site requires that.

**Comment by 1ec5** [comment] 2024-02-15 06:06
> why not just optionally display the relation number on screen?

As I mentioned in https://github.com/openstreetmap/iD/issues/9349#issuecomment-1769114994, it would be great if the membership editor would show the relation IDs when two relations have otherwise identical labels, as the dropdown menu already does. The case above, where the relation is only labeled by its preset, would be another reasonable opportunity to show relation IDs.

Showing relation IDs more generally would be problematic for a couple reasons. One is what you just pointed out: that labels already easily get cut off when the sidebar is at a reasonable width, so it doesn’t necessarily solve any problems that a tooltip wouldn’t solve.

Another reason is that relation IDs these days tend to be rather long. It can result in information overload in conjunction with all the other information that can already go into the label. Unlike the relation ID in the History or Measurement panel or a openstreetmap-website relation page, the relation label isn’t selectable, so the only purpose is to cross-reference it with something in another tab, which makes glanceability pretty important. If we do end up displaying relation IDs in general here, I would even go so far as to suggest formatting the numbers with digit grouping characters for readability.

Anyways, #9349 is already tracking showing the relation IDs, so we should continue that discussion there.

**Comment by 1ec5** [comment] 2024-02-15 06:06
Duplicate of #8313

**Closed as not planned by 1ec5** 2024-02-15 06:06 UTC
