### ISSUE TITLE
Suggest alternate imagery based on map location

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#2826] opened 2015-11-06 14:05 UTC
Recent investigations into the [data issues in Japan](https://www.openstreetmap.org/user/PlaneMad/diary/36058) revealed the Bing imagery is poorly orthorectified with both distortions and offsets that vary throughout the country. Data traced from Bing requires correction which is a very resource intensive effort.

New mappers who join OSM are completely unaware of these issues and start putting in a lot of effort to essentially contribute data that requires rework, which is a massive waste of community resources. Another issue is new users realigning correct data to incorrect imagery.

If iD can have a database for alternate imagery to be used for different regions, we could prompt the mapper to use the correct background layer. Otherwise there is no mechanism to inform the user who is bound to be confused on why there is a mismatch between the imagery and data.

![](https://cloud.githubusercontent.com/assets/126868/10997540/dd8e612c-84b3-11e5-969f-2e0e53a29fed.gif)
*Imagery distrotions in Bing*

cc @bhousel @lxbarth @mikel

**Comment by lxbarth** [comment] 2015-11-06 14:38
> If iD can have a database for alternate imagery to be used for different regions, we could prompt the mapper to use the correct background layer. 

Such a db should be available to any editor. See also https://github.com/osmlab/editor-imagery-index cc @tmcw

**Comment by bhousel** [comment] 2015-11-06 15:28
There is a very old issue for this in #1124 .. @Zverik what's the status of this?  I assume the Imagery Offset Database isn't "upcoming" anymore?

Agree that this really needs tie-in with `editor-imagery-index` so that we can pick the best imagery for the user's loc/zoom.  (yes, zoom matters)

**Comment by Zverik** [comment] 2015-11-06 15:35
The offset database does not provide alternative imagery information, but it is very active for 2.5 years with more than 11 thousand offsets recorded.

**Comment by bhousel** [comment] 2015-11-06 16:22
Hey @Zverik I did some looking through the [API documentation](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database/API) and it looks like a decent initial attempt at recording offsets.

Some questions:
* Can you make the source available for the server component?
* Will you continue to host this server, or does it make more sense for OSM's OWG to host it somewhere (obviously if iD starts auto-adjusting all its imagery based on your offset database, it could generate a ton of traffic)
* [`/get`](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database/API#Getting_an_Offsets_List) shows example of `lat`, `lon`, `imagery` and `radius`.   I would suggest to replace `radius` with `zoom`, because the quality of Bing imagery varies widely depending on which zoom we are fetching.

**Comment by Zverik** [comment] 2015-11-06 16:28
1. https://github.com/Zverik/iodb
2. I will, along my other projects. It doesn't require much resources. Of course, it can be moved elsewhere, if needed: I can provide with a copy of a database (for now, there are daily backups).
3. The offset database works for any layer, not only Bing. And you might be misunderstanding the meaning of radius: it's a lookup radius for finding offsets, in kilometers.

**Comment by matkoniecz** [comment] 2015-11-20 11:36
See #1310 and  #2261

**Comment by pnorman** [comment] 2015-11-20 19:22
> There is a very old issue for this in #1124 .. @Zverik what's the status of this? I assume the Imagery Offset Database isn't "upcoming" anymore?

That issue is about offsets, this issue is about choosing the best imagery, and is a duplicate of #1310.

**Comment by bhousel** [comment] 2015-11-20 19:33
Oh thanks @pnorman & @matkoniecz ..  Didn't know about #1310 
It looks like [the `best` property](https://github.com/osmlab/editor-imagery-index/blob/52ec6b3fe2c4868c27d35cbcdc37f74867875be9/schema.json#L40-L43) is what we want.

**Comment by pnorman** [comment] 2015-11-20 19:39
note https://github.com/openstreetmap/iD/issues/1310#issuecomment-24593211 and https://github.com/openstreetmap/iD/issues/1310#issuecomment-50732249 specifically

**Comment by bhousel** [comment] 2015-11-20 19:43
I'm reading @tmcw's comment as:  we shouldn't switch backgrounds on a user if they happen to scroll into a place with better imagery - not that he is opposed to picking the best imagery when the map initially loads.

**Closed** 2015-11-25 04:43 UTC
