### ISSUE TITLE
Add History button to bottom of feature editor

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4152] opened 2017-07-13 04:15 UTC
The History inspector is really handy; about 90% of the time, it has what I would normally go to osm.org’s browse page for. The bottom of the feature editor should include a History button that opens the History inspector. It could go right next to the existing link to the feature’s browse page on osm.org.

**Comment by 1ec5** [comment] 2017-07-13 04:16
If this placement would be too prominent, an alternative could be the bottom of the feature’s context menu.

**Comment by bhousel** [comment] 2017-07-13 14:01
For right now, I'd prefer to keep the info panels as a somewhat hidden "pro" feature.  They are discoverable on the keyboard shortcuts screen.  This keeps iD simple and friendly for new users.   _I might change my mind about this later._

Some backstory - everything you find in an Info Panel is something that a few years ago would have been considered "out of scope" for iD.  We almost didn't build the original <kbd>⌘I</kbd> measurement panel, and when it was built, we intentionally didn't tell anybody about it.  Notice that these new panel commands (all by design):
1. Use more complicated modifier combos (<kbd>⌘</kbd>+<kbd>⇧</kbd>+`key`  vs <kbd>⌘</kbd>+`key`)
2. Appear _last_ on the keyboard shortcuts screen after simpler commands.
3. Use more jargon ("centroid", "changeset", "tiles", "vintage").

As users spend time editing, they will eventually find their way to the keyboard shortcuts screen and learn about the advanced features.  Some people call this "progressive disclosure" or "progressive revelation".  It's great because users who don't care about the feature don't need to be bothered by having extra buttons around.  

Some really excellent things have been written on the UX Stack Exchange about this:  https://ux.stackexchange.com/questions/12622/design-patterns-for-discoverability

This applies to most of iD's users.  iD is designed primarily for someone who does not care about maps and has never mapped before and doesn't know what OpenStreetMap is.  This is not you or me or anybody who hangs out on GitHub or an OSM mailing list.  My goal is to get them through the first 10 edits or so and convert them into someone who does care about maps.

**Closed by bhousel** 2017-07-13 14:01 UTC

**Comment by 1ec5** [comment] 2017-07-13 22:56
That’s reasonable. I thought the omission of a button was an oversight, but if it’s intentional, then I’m glad you’re making the call as to what’s a power tool and not me. 😉
