### ISSUE TITLE
Version mismatch even after conflict resolution prompts

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/iD#2803] opened 2015-10-13 08:39 UTC
Once again today I got a set of prompt selections for conflicts but this time with myself (5 in total) during a not so long edit (109 edits). I should have realise this was coming since i had previously worked on the same area and i encountered empty lines i was working with in the process at that previous time. 

After having compared all prompts in my favor, I encountered an error message saying:
Version mismatch: Provided 2, server had: 3 of Node 983104871.
Server returned status code 409

So I saved the XML... and plan to upload it via JOSM. I haven't done it yet because maybe you would like to check something i'm not aware of to solve this bug... and i haven't closed the iD window on Firefox. So I'm waiting for your concert.

**Comment by pnorman** [comment] 2015-10-13 18:16
Conflicting with yourself could be an occurrence of #1646

**Comment by bhousel** [comment] 2015-10-13 18:31
> So I saved the XML... and plan to upload it via JOSM. I haven't done it yet because maybe you would like to check something i'm not aware of to solve this bug... and i haven't closed the iD window on Firefox. So I'm waiting for your concert.

In this case it might work best to close the iD window, then reopen it, choose to restore your unsaved changes, then try to save again.  You'll have fresh tiles from the server, and the conflict resolution prompts *should* be able to bump the version ahead to the number that the API expects.  

Let me know if that works...

**Comment by SHARCRASH** [comment] 2015-10-13 19:29
I tried to close and reopen, nah still the same problem.

**Comment by pnorman** [comment] 2015-10-13 19:47
> conflict resolution prompts should be able to bump the version ahead to the number that the API expects

If he's moved the same node differently in both his original changeset and the new one, it won't be able to resolve it, will it?

For reference, the node is https://www.openstreetmap.org/node/983104871/history

**Comment by bhousel** [comment] 2015-10-13 20:11
> If he's moved the same node differently in both his original changeset and the new one, it won't be able to resolve it, will it?

It should be able to handle it - I tested this scenario pretty extensively.  For each locally modified element, we ask the server for the latest version.

My best guess is that he saved a changeset, then the refresh happened but #1646 caused his changes to not appear locally, and then he redid the same edit?  The base nodes (which we persist to local storage) are not right, so conflict resolution doesn't know what to do.   Again this is a guess.

@SHARCRASH, since this is your own edit, and there are only a few (5?) conflicts, can you just accept the remote version when conflict resolution prompts to pick a version?

**Comment by pnorman** [comment] 2015-10-13 22:29
> It should be able to handle it - I tested this scenario pretty extensively. For each locally modified element, we ask the server for the latest version.

How does it handle it if you've modified v1 of a node to move from position A to position B, and another changeset (which happens to be by the same user, in this case) has modified v1 of a node to move from position A to position C? Even if B and C are intended to be the same position, they will almost certainly differ slightly.

This is one of the standard examples of a conflict which cannot be resolved mechanically, since you have no way of knowing which to prefer.

**Comment by bhousel** [comment] 2015-10-14 01:15
> This is one of the standard examples of a conflict which cannot be resolved mechanically, since you have no way of knowing which to prefer.

Right, it is supposed to show the prompt in that situation, not try to resolve it mechanically.

**Comment by SHARCRASH** [comment] 2015-10-14 07:50
I tried to do as you say Bryan, I'm unlucky... the temporary changeset doesn't load anymore. I had tried different combinations to give favor to the remote version on some unimportant elements, not all though and this happened to load a second session of conflicts leading to the same problem. After I've made my last try of prompt resolution and reloaded the changeset, I think i clicked outside the Restore button in the rush, not even on the Reset button but on the map.

**Comment by bhousel** [comment] 2015-10-21 03:43
> After I've made my last try of prompt resolution and reloaded the changeset, I think i clicked outside the Restore button in the rush, not even on the Reset button but on the map.

I'm sorry that you lost some work - but let me know if it happens again, especially if it turns out to be a repeatable set of editing steps that we can use to reproduce the issue.  I'll close it for now since there doesn't seem to be anything actionable on my end..

**Closed by bhousel** 2015-10-21 03:43 UTC
