### ISSUE TITLE
Unexpected behavior in new turn restriction editor

### ISSUE THREAD

**Issue by zlavergne** [openstreetmap/iD#4848] opened 2018-03-05 23:42 UTC
@bhousel Correct me if I'm wrong but this wasn't the expected behavior to me.

<img width="1135" alt="screen shot 2018-03-05 at 3 49 02 pm" src="https://user-images.githubusercontent.com/9849118/37004197-df404220-208c-11e8-886e-ecb2d2080db4.png">

[https://www.openstreetmap.org/edit#map=20/-36.81697/-73.04610](https://www.openstreetmap.org/edit#map=20/-36.81697/-73.04610)

When adding a simple `no_right_turn` from the eastbound secondary to the northbound primary, the resulting changeset is 40 changes when I expected just one change.  

<img width="360" alt="screen shot 2018-03-05 at 4 18 13 pm" src="https://user-images.githubusercontent.com/9849118/37005307-e4521dfc-2090-11e8-96d9-c9b335df21c9.png">

I expect to only create one change because:
- Both ways are already split at the intersection
- The ways are only members to already standing turn restrictions (shouldn't modify a current relation)

After I edit the restriction, there is a bunch of changes including creating and modifying the ways involved but also modifying the 27 different bus routes whose members are the two `alleys` in splitting the primary ways. 

<img width="199" alt="screen shot 2018-03-05 at 4 14 24 pm" src="https://user-images.githubusercontent.com/9849118/37005170-4f7caee0-2090-11e8-8693-45d166a1d589.png">

I noticed that after I made the restriction, the `to` way was split every time the way had a connecting node that was displayed in the turn restriction viewport which gave me a hunch and I found something I thought was interesting. It appears that any way that's displayed within the turn restriction viewport is modified. If I increase the viewport distance, the changes increase and vice-versa. 

It almost looks like any split or way modification made to accommodate the viewport is transferred back to the main graph. Is this the expected behavior?

PS: I haven't been able to look at the code yet.

**Comment by bhousel** [comment] 2018-03-06 04:16
> It almost looks like any split or way modification made to accommodate the viewport is transferred back to the main graph. Is this the expected behavior?

Hey @zlavergne - yes, what you described is exactly what it does, and I understand that it's unexpected.  There were some things that surprised me when I implemented this feature that I'd love to share.   

#### How it works 
The turn restriction editor displays a "fake" intersection in which all the ways already are split up.  When a user changes something in that intersection, all those splits are applied before the restriction is added.

#### Before
iD's previous turn restriction editor only allowed via-node restrictions, so it was fairly straightforward for the code that added the restriction to also perform the splitting at the via node if needed.

#### After
Via-way restrictions make this impossible to do because there can be several paths from a FROM to a TO, (in an intersection with cycles) so we need to 1. specify the via way path unambiguously.  2. that means those segments need stable identifiers  3. that means those segments need to be split already before we add the restriction  4. that means that the splits must be performed _idempotently_ (splitting on a vertex in the mini editor should also split the road in exactly the same way in the main graph after the user clicks).

#### My favorite bug ever 🐛 
This last point was the source of a fascinating bug.
https://twitter.com/bhousel/status/924115710942629888

_One would think_ that when you split a way in the mini editor and split a way in the main map, that the same thing would happen, right?  Post-split, you end up with part of the way having the original id and part of the way having a new id, and it should probably be the same half that is chosen to be the new one?  Turns out not to be true.  The splitting code iterates over all parent ways at that vertex.  On the main map, those parent ways are added to the array in _whatever order they happened to be fetched from the OSM API_, and on the mini map, those parent ways are added to the array in _whatever order we walk the graph_ depending on the starting vertex that the user clicked.  

Most of the time it would do the right thing when a user clicked, but occasionally the turn restriction would get added with the wrong TO.  And it would depend completely on where you clicked and how data happened to get fetched from the API.  This was a wild bug to track down.

#### So we split ✂️ 
SO, the result of all that is - I decided to just apply all the graph modifications from the restriction editor on to the main map, in order to guarantee stability in the ids.  When we say `FROM w1234 VIA w-2 TO w-3`, we know for sure what `w-2` and `w-3` are.  This can generate more splits than is strictly necessary, but having the splits there doesn't actually break anything in OSM.

> PS: I haven't been able to look at the code yet.

I encourage you to check it out!  The code for modeling an intersection is here:
https://github.com/openstreetmap/iD/blob/master/modules/osm/intersection.js
And the code for the restriction editor component is here:
https://github.com/openstreetmap/iD/blob/master/modules/ui/fields/restrictions.js

I've tried to comment the code really well.  It's unusually complicated code with some surprises, and I will need to maintain it somehow...

I'm going to close this here, but we can revisit or open follow-on issues if we discover any bugs caused by this unexpected behavior.

**Closed by bhousel** 2018-03-06 04:16 UTC
Labels: question

**Comment by zlavergne** [comment] 2018-03-21 16:52
Thanks for the explanation. It makes a lot more sense now!
