### ISSUE TITLE
Merge splitted building

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#3855] opened 2017-02-23 10:41 UTC
I'm not sure if iD should be able to deal with it (or even if it already handles it), but (at least in France) buildings are often broken in several parts on cadastral parcels limit. So for instance you may end up with [this](http://www.openstreetmap.org/way/158392612) : 

![image](https://cloud.githubusercontent.com/assets/1451988/23255662/c4ea82d4-f9bc-11e6-9756-ae1f330b29b2.png)

The "merge" operation on iD when selecting both polygons does merge them, but the split line is still present and I don't get how they are actually merged; I would expect this operation to merge "along the axis" and remove it?

**Comment by althio** [comment] 2017-02-23 11:04
> the split line is still present and I don't get how they are actually merged

They are merged as in:
- create a _relation_ `type=multipolygon `
- put attributes on the relation (`building=yes`, ...)
- keep existing geometries as lines (2 separated _relation members_ as outer)

This is not an "expected" merge for contiguous area objects.

**Comment by althio** [comment] 2017-02-23 11:11
and for reference:
potential duplicate of https://github.com/openstreetmap/iD/issues/435#issuecomment-211945299

**Comment by bhousel** [comment] 2017-02-23 14:19
Yes this is a duplicate of #435 
We'll add polygon operations to iD once turf.js has sorted out their JSTS issues.
We're definitely open to contributions on the turf.js side!

**Closed by bhousel** 2017-02-23 14:19 UTC
