### ISSUE TITLE
Enhancement: Record radial menu actions in local history, as confirmation

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2572] opened 2015-04-01 23:55 UTC
Here's an example iD editing error: http://www.openstreetmap.org/changeset/22493168

Potential way to prevent this:
Have iD record locally radial menu actions.  So rather than iD saying:
   * **Modified Apartments: The Whitmore**

It could say

  * **Made Circular; Modified; Rotated Apartments: The Whitmore**

The goal is to catch some mistakes people make with inadvertent actions on the radial menu.

**Comment by jfirebaugh** [comment] 2015-04-01 23:58
This is a duplicate of #1735, yeah?

**Comment by brycenesbitt** [comment] 2015-04-02 00:08
Heh, lightning strikes twice.
Sorry I'd forgotten this came up before.
Implementing this by the undo buffer comment is actually a better solution :-).

**Closed** 2015-05-19 20:42 UTC
